/**
 * AQWELIA — App Store / Play Store preparation page (internal).
 *
 * URL: /store
 *
 * Server component. Provides a single dashboard for the product team to track
 * what's ready vs missing before submitting to Apple App Store + Google Play.
 * Lists assets, metadata, native project state, and links to the docs.
 *
 * No client interactivity required (pure status board). The page is NOT
 * linked from the landing or app navigation — it is intended for internal use
 * only (accessed via direct URL).
 */
import Link from 'next/link'
import type { Metadata } from 'next'
import { getTranslations } from 'next-intl/server'
import { Check, X, AlertTriangle, ArrowRight, Apple, Smartphone, FileText } from 'lucide-react'

export const metadata: Metadata = {
  title: 'App Store / Play Store preparation — AQWELIA',
  description: 'Internal dashboard tracking native app submission readiness.',
  robots: { index: false, follow: false },
}

type Status = 'ready' | 'missing' | 'partial'

interface CheckItem {
  label: string
  status: Status
  detail?: string
}

interface Section {
  id: string
  title: string
  icon: typeof Apple
  items: CheckItem[]
}

const SECTIONS: Section[] = [
  {
    id: 'capacitor',
    title: 'Capacitor wrapper layer',
    icon: Apple,
    items: [
      { label: 'capacitor.config.ts (appId, appName, webDir)', status: 'ready', detail: 'com.aqwelia.app · Aqwelia · out/' },
      { label: 'All required plugins in package.json', status: 'ready', detail: '11 required + 2 extras (browser, network)' },
      { label: 'Native wrappers (src/lib/native/*)', status: 'ready', detail: '14 modules + 1 barrel — SSR-safe + web fallback' },
      { label: 'Mobile UI shell (header, bottom tabs, 5 screens)', status: 'ready', detail: 'src/components/mobile/*' },
      { label: 'RevenueCat billing wrapper', status: 'ready', detail: 'src/lib/billing/revenuecat.ts — SSR-safe' },
      { label: 'Safe-area + notch handling', status: 'ready', detail: 'env(safe-area-inset-*) in globals.css' },
      { label: 'next.config.mobile.ts (static export)', status: 'ready', detail: 'output: "export" → out/' },
    ],
  },
  {
    id: 'native-projects',
    title: 'Native project scaffolding (macOS / Android Studio required)',
    icon: Smartphone,
    items: [
      { label: 'ios/ native project', status: 'missing', detail: 'Run `npx cap add ios` on a macOS + Xcode 15+ machine' },
      { label: 'android/ native project', status: 'missing', detail: 'Run `npx cap add android` on a machine with Android Studio' },
      { label: 'cap sync (web assets + plugins)', status: 'missing', detail: 'Run `npx cap sync ios android` after the projects exist' },
      { label: 'App Store Connect app record', status: 'missing', detail: 'https://appstoreconnect.apple.com → create new app (com.aqwelia.app)' },
      { label: 'Google Play Console app record', status: 'missing', detail: 'https://play.google.com/console → create new app (com.aqwelia.app)' },
    ],
  },
  {
    id: 'metadata',
    title: 'Store metadata (App Store + Play Store)',
    icon: FileText,
    items: [
      { label: 'docs/APP_STORE_METADATA.md', status: 'ready', detail: 'App name, subtitle, description (FR+EN), keywords, screenshots, review notes' },
      { label: 'docs/PLAY_STORE_METADATA.md', status: 'ready', detail: 'App name, short/full description, screenshots, data safety form' },
      { label: 'STORE_READINESS.md (legacy)', status: 'ready', detail: 'Pre-Capacitor audit — kept for reference' },
      { label: 'docs/MOBILE_READINESS.md', status: 'ready', detail: 'Current Capacitor layer status (post P4-MOBILE)' },
      { label: 'Privacy policy URL', status: 'ready', detail: '/legal/privacy — already deployed with the web app' },
      { label: 'Support URL', status: 'ready', detail: '/legal/support — already deployed with the web app' },
      { label: 'Demo account credentials (review notes)', status: 'ready', detail: 'Documented in APP_STORE_METADATA.md §review-notes' },
    ],
  },
  {
    id: 'assets-ios',
    title: 'iOS assets (public/mobile/ios/)',
    icon: Apple,
    items: [
      { label: 'App icon 1024×1024 (App Store)', status: 'ready', detail: 'icon-1024.png · 1024×1024' },
      { label: 'App icon 60pt (120×120 = @2x)', status: 'ready', detail: 'icon-60pt.png · @2x scale present, @1x/@3x auto-generated by cap sync' },
      { label: 'App icon 76pt (iPad, 152×152 = @2x)', status: 'ready', detail: 'icon-76pt.png · @2x scale present' },
      { label: 'App icon 83.5pt (iPad Pro 12.9, 167×167 = @2x)', status: 'ready', detail: 'icon-83.5pt.png · @2x scale present' },
      { label: 'App icon 40pt (Spotlight, 80×80 = @2x)', status: 'ready', detail: 'icon-40pt.png · @2x scale present' },
      { label: 'App icon 29pt (Settings, 58×58 = @2x)', status: 'ready', detail: 'icon-29pt.png · @2x scale present' },
      { label: 'App icon 20pt (Notification, 40×40 = @2x)', status: 'ready', detail: 'icon-20pt.png · @2x scale present' },
      { label: 'App icon 50pt (Mac, 100×100)', status: 'missing', detail: 'Optional — only required if submitting to Mac App Store' },
      { label: 'Splash 750×1334 (iPhone 6/7/8)', status: 'ready', detail: 'splash-750x1334.png' },
      { label: 'Splash 1170×2532 (iPhone 12/13/14)', status: 'ready', detail: 'splash-1170x2532.png' },
      { label: 'Splash 1284×2778 (iPhone 12/13/14 Pro Max)', status: 'ready', detail: 'splash-1284x2778.png' },
      { label: 'Splash 1125×2436 (iPhone X/XS/11 Pro)', status: 'missing', detail: 'Generate from 1170×2532 source (different aspect)' },
      { label: 'Splash 1242×2688 (iPhone XS Max / 11 Pro Max)', status: 'missing', detail: 'Generate from 1284×2778 source (different aspect)' },
      { label: 'Splash 828×1792 (iPhone XR / 11)', status: 'missing', detail: 'Generate from 750×1334 source (different aspect)' },
      { label: 'iPad splash (landscape 2732×2048, portrait 2048×2732)', status: 'missing', detail: 'Required only if iPad is targeted (stage 2)' },
      { label: 'App Store screenshots (6.7" + 6.5" + 5.5")', status: 'missing', detail: 'See APP_STORE_METADATA.md §screenshots — 8 storyboard frames defined' },
      { label: 'App Preview video (15-30s, optional)', status: 'missing', detail: 'Optional but recommended — boosts conversion' },
    ],
  },
  {
    id: 'assets-android',
    title: 'Android assets (public/mobile/android/)',
    icon: Smartphone,
    items: [
      { label: 'Launcher icon mdpi (48×48)', status: 'ready', detail: 'mdpi.png · 48×48' },
      { label: 'Launcher icon hdpi (72×72)', status: 'ready', detail: 'hdpi.png · 72×72' },
      { label: 'Launcher icon xhdpi (96×96)', status: 'ready', detail: 'xhdpi.png · 96×96' },
      { label: 'Launcher icon xxhdpi (144×144)', status: 'ready', detail: 'xxhdpi.png · 144×144' },
      { label: 'Launcher icon xxxhdpi (192×192)', status: 'ready', detail: 'xxxhdpi.png · 192×192' },
      { label: 'ic_launcher_foreground.png (adaptive icon, 432×432)', status: 'ready', detail: 'Foreground layer for adaptive icons (Android 8+)' },
      { label: 'ic_launcher_background (color or PNG)', status: 'partial', detail: 'Background color is set in capacitor.config.ts (#003B4A). PNG background optional.' },
      { label: 'Splash image (1080×1920)', status: 'ready', detail: 'splash.png · 1080×1920 (FHD portrait)' },
      { label: 'Feature graphic 1024×500 (Play Store banner)', status: 'missing', detail: 'Required for Play Store listing' },
      { label: 'Play Store screenshots (1080×1920 min, 2-8 frames)', status: 'missing', detail: 'See PLAY_STORE_METADATA.md §screenshots' },
      { label: 'Play Store app preview video (YouTube URL, optional)', status: 'missing', detail: 'Optional, 30s-2min' },
    ],
  },
  {
    id: 'env',
    title: 'Environment variables (production mobile)',
    icon: AlertTriangle,
    items: [
      { label: 'NEXT_PUBLIC_API_BASE_URL', status: 'partial', detail: 'Must point to deployed backend (not localhost) before mobile build' },
      { label: 'NEXT_PUBLIC_REVENUECAT_IOS_KEY', status: 'partial', detail: 'Placeholder `appl_xxx` in .env.example — create RC project + copy key' },
      { label: 'NEXT_PUBLIC_REVENUECAT_ANDROID_KEY', status: 'partial', detail: 'Placeholder `goog_xxx` in .env.example — create RC project + copy key' },
      { label: 'REVENUECAT_WEBHOOK_SECRET', status: 'partial', detail: 'Configure in RC dashboard → Webhooks' },
      { label: 'STRIPE_SECRET_KEY + STRIPE_WEBHOOK_SECRET', status: 'partial', detail: 'Already used by web flow — reuse for mobile web fallback' },
      { label: 'SMTP_HOST / SMTP_PORT / SMTP_USER / SMTP_PASS / EMAIL_FROM', status: 'partial', detail: 'Required for transactional emails (welcome, lead notifications). See src/lib/email.ts' },
    ],
  },
]

function StatusIcon({ status }: { status: Status }) {
  if (status === 'ready') return <Check className="h-4 w-4 text-emerald-500" aria-label="Ready" />
  if (status === 'missing') return <X className="h-4 w-4 text-red-500" aria-label="Missing" />
  return <AlertTriangle className="h-4 w-4 text-amber-500" aria-label="Partial" />
}

const STATUS_LABEL: Record<Status, string> = {
  ready: 'Ready',
  missing: 'Missing',
  partial: 'Partial',
}

const STATUS_BADGE_CLASS: Record<Status, string> = {
  ready: 'border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-400',
  missing: 'border-red-500/30 bg-red-500/10 text-red-700 dark:text-red-400',
  partial: 'border-amber-500/30 bg-amber-500/10 text-amber-700 dark:text-amber-400',
}

function countStatus(items: CheckItem[]): { ready: number; missing: number; partial: number; total: number } {
  return {
    ready: items.filter((i) => i.status === 'ready').length,
    missing: items.filter((i) => i.status === 'missing').length,
    partial: items.filter((i) => i.status === 'partial').length,
    total: items.length,
  }
}

export default async function StorePrepPage() {
  const t = await getTranslations('common')
  const appName = t('appName')

  // Global progress
  const all = SECTIONS.flatMap((s) => s.items)
  const globalStats = countStatus(all)
  const readyPct = Math.round((globalStats.ready / globalStats.total) * 100)

  return (
    <div className="relative min-h-screen bg-background">
      <header className="safe-area-top sticky top-0 z-40 border-b border-gold/20 bg-background/85 backdrop-blur-2xl">
        <div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-4 sm:px-6">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-muted-foreground transition-colors hover:text-foreground"
          >
            <ArrowRight className="h-3.5 w-3.5 rotate-180" />
            Retour à l'accueil
          </Link>
          <div className="flex items-center gap-2">
            <span className="font-display text-base font-bold tracking-tight">
              <span className="aqua-text-gradient">{appName}</span>
            </span>
            <span className="rounded-full border border-gold/40 bg-gold/10 px-2 py-0.5 text-[10px] font-bold uppercase tracking-widest text-gold">
              Internal
            </span>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 sm:py-14">
        {/* Hero */}
        <div className="rounded-3xl border border-white/40 bg-white/60 p-6 backdrop-blur-xl dark:border-white/10 dark:bg-white/[0.03] sm:p-8">
          <p className="text-xs font-semibold uppercase tracking-widest text-gold">App Store / Play Store</p>
          <h1 className="mt-2 font-display text-3xl font-bold sm:text-4xl">Préparation au lancement natif</h1>
          <p className="mt-3 max-w-2xl text-sm text-muted-foreground sm:text-base">
            État d'avancement de la soumission AQWELIA sur l'App Store (iOS) et le Play Store (Android).
            La couche Capacitor est complète ; il reste à scaffolder les projets natifs sur une machine
            macOS + Xcode (iOS) et Android Studio (Android), puis à générer les captures d'écran store.
          </p>

          {/* Global progress */}
          <div className="mt-6 flex flex-wrap items-center gap-4">
            <div className="min-w-[200px] flex-1">
              <div className="flex items-center justify-between text-xs text-muted-foreground">
                <span>Progression globale</span>
                <span className="font-mono font-bold text-foreground">{readyPct}%</span>
              </div>
              <div className="mt-1 h-2 overflow-hidden rounded-full bg-muted">
                <div
                  className="h-full rounded-full bg-gradient-to-r from-gold to-[oklch(0.55_0.10_195)] transition-all"
                  style={{ width: `${readyPct}%` }}
                />
              </div>
            </div>
            <div className="flex items-center gap-3 text-xs">
              <span className="inline-flex items-center gap-1"><Check className="h-3.5 w-3.5 text-emerald-500" /> {globalStats.ready} ready</span>
              <span className="inline-flex items-center gap-1"><AlertTriangle className="h-3.5 w-3.5 text-amber-500" /> {globalStats.partial} partial</span>
              <span className="inline-flex items-center gap-1"><X className="h-3.5 w-3.5 text-red-500" /> {globalStats.missing} missing</span>
            </div>
          </div>

          {/* Quick links */}
          <div className="mt-6 flex flex-wrap gap-2">
            <Link
              href="/legal/privacy"
              className="inline-flex items-center gap-1.5 rounded-full border border-gold/40 bg-gold/10 px-3 py-1.5 text-xs font-semibold text-gold hover:bg-gold/20"
            >
              <Apple className="h-3.5 w-3.5" />
              Voir APP_STORE_METADATA.md (repo)
            </Link>
            <Link
              href="/legal/support"
              className="inline-flex items-center gap-1.5 rounded-full border border-gold/40 bg-gold/10 px-3 py-1.5 text-xs font-semibold text-gold hover:bg-gold/20"
            >
              <Smartphone className="h-3.5 w-3.5" />
              Voir PLAY_STORE_METADATA.md (repo)
            </Link>
            <a
              href="https://appstoreconnect.apple.com"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 rounded-full border border-white/40 bg-white/60 px-3 py-1.5 text-xs font-semibold text-foreground hover:bg-white/80 dark:border-white/10 dark:bg-white/[0.04]"
            >
              <FileText className="h-3.5 w-3.5" />
              App Store Connect
            </a>
          </div>
        </div>

        {/* Sections */}
        <div className="mt-8 space-y-6">
          {SECTIONS.map((section) => {
            const stats = countStatus(section.items)
            const Icon = section.icon
            return (
              <section
                key={section.id}
                className="overflow-hidden rounded-2xl border border-white/40 bg-white/60 backdrop-blur-xl dark:border-white/10 dark:bg-white/[0.03]"
              >
                <header className="flex items-center justify-between border-b border-white/30 bg-white/40 px-5 py-3 dark:border-white/5 dark:bg-white/[0.02]">
                  <div className="flex items-center gap-2.5">
                    <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-primary/15 to-gold/15">
                      <Icon className="h-4 w-4 text-primary" />
                    </div>
                    <h2 className="font-display text-base font-bold">{section.title}</h2>
                  </div>
                  <span className="font-mono text-xs text-muted-foreground">
                    {stats.ready}/{stats.total} ready
                  </span>
                </header>
                <ul className="divide-y divide-white/20 dark:divide-white/5">
                  {section.items.map((item) => (
                    <li key={item.label} className="flex items-start gap-3 px-5 py-3">
                      <span className="mt-0.5">
                        <StatusIcon status={item.status} />
                      </span>
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <p className="text-sm font-medium text-foreground">{item.label}</p>
                          <span
                            className={`rounded-full border px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-wide ${STATUS_BADGE_CLASS[item.status]}`}
                          >
                            {STATUS_LABEL[item.status]}
                          </span>
                        </div>
                        {item.detail && (
                          <p className="mt-0.5 font-mono text-[11px] text-muted-foreground">{item.detail}</p>
                        )}
                      </div>
                    </li>
                  ))}
                </ul>
              </section>
            )
          })}
        </div>

        {/* Footer note */}
        <p className="mt-8 text-center text-xs text-muted-foreground">
          Page interne — ne pas indexer. <code className="rounded bg-muted px-1 py-0.5">robots: noindex, nofollow</code>
        </p>
      </main>
    </div>
  )
}
