'use client'

import { useCallback, useEffect, useState } from 'react'
import Link from 'next/link'
import { Calendar, Loader2, RefreshCw } from 'lucide-react'

type Appointment = { id: string; startTime: string; endTime: string; status: string; notes?: string | null; lead: { id: string; firstName: string; lastName: string; city?: string | null; phone?: string | null } }
const statuses = ['proposed','confirmed','completed','cancelled','no_show']
export default function GrowthAppointmentsPage() {
  const [rows, setRows] = useState<Appointment[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  const load = useCallback(async () => { setLoading(true); const r = await fetch('/api/growth/appointments', { cache: 'no-store' }); if (r.ok) setRows((await r.json()).appointments ?? []); setLoading(false) }, [])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  async function update(id: string, status: string) { const r = await fetch(`/api/growth/appointments/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); setMessage(r.ok ? 'Rendez-vous mis à jour.' : 'Mise à jour impossible.'); if (r.ok) void load() }
  return <div className="space-y-6"><Header icon={<Calendar className="h-3 w-3" />} title="Rendez-vous" subtitle="Créneaux proposés, confirmations et suivi des visites." onRefresh={load} />{message && <Notice text={message} />}{loading ? <Spinner /> : rows.length === 0 ? <Empty text="Aucun rendez-vous. Créez-en depuis une fiche lead." /> : <div className="space-y-3">{rows.map((a) => <div key={a.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/40 bg-white/60 p-4 dark:border-white/10 dark:bg-white/[0.04]"><div><Link href={`/growth/app/leads/${a.lead.id}`} className="font-semibold hover:text-gold">{a.lead.firstName} {a.lead.lastName}</Link><p className="text-xs text-muted-foreground">{new Date(a.startTime).toLocaleString('fr-FR')} → {new Date(a.endTime).toLocaleTimeString('fr-FR')} · {a.lead.city || 'Zone non précisée'}</p></div><select value={a.status} onChange={(e) => void update(a.id, e.target.value)} className="rounded-xl border border-border bg-background p-2 text-xs">{statuses.map((s) => <option key={s} value={s}>{s}</option>)}</select></div>)}</div>}</div>
}
function Header({ icon,title,subtitle,onRefresh }: { icon: React.ReactNode; title:string; subtitle:string; onRefresh:()=>void }) { return <div className="flex flex-wrap items-end justify-between gap-3"><div><span className="section-label">{icon} Growth Inbox Beta</span><h1 className="mt-2 font-display text-3xl font-bold sm:text-4xl">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{subtitle}</p></div><button onClick={onRefresh} className="inline-flex items-center gap-2 rounded-full border border-border px-3 py-2 text-xs"><RefreshCw className="h-3.5 w-3.5" />Actualiser</button></div> }
function Spinner(){return <div className="flex justify-center py-14"><Loader2 className="h-6 w-6 animate-spin" /></div>} function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">{text}</div>} function Notice({text}:{text:string}){return <div className="rounded-xl border border-primary/30 bg-primary/10 p-3 text-sm">{text}</div>}
