#!/usr/bin/env python3
"""Build Italian translation file for it-part2 worksheet."""
import json
from pathlib import Path

WORKSHEET = Path('/home/z/my-project/.tmp/worksheets/it-part2.json')
OUTPUT = Path('/home/z/my-project/.tmp/translated/it-part2.json')

# Translations keyed by dotted key path (same order as worksheet)
TRANSLATIONS = {
    # ===== guidesData.reminder_* (20) =====
    "guidesData.reminder_retest_after_product_action": "Azione per retest_after_product",
    "guidesData.reminder_retest_after_product_detail": "Dettaglio per retest_after_product",
    "guidesData.reminder_retest_after_product_title": "Re-test dopo prodotto",
    "guidesData.reminder_shock_treatment_action": "Azione per shock_treatment",
    "guidesData.reminder_shock_treatment_detail": "Dettaglio per shock_treatment",
    "guidesData.reminder_shock_treatment_title": "Trattamento shock",
    "guidesData.reminder_skimmer": "Controllare skimmer e cestello",
    "guidesData.reminder_skimmer_action": "Svuotare il cestello dello skimmer e quello della pompa.",
    "guidesData.reminder_skimmer_check_action": "Svuotare il cestello dello skimmer e quello della pompa.",
    "guidesData.reminder_skimmer_check_detail": "Detriti, foglie, insetti da rimuovere regolarmente.",
    "guidesData.reminder_skimmer_check_title": "Controllare skimmer e cestello",
    "guidesData.reminder_skimmer_desc": "Detriti, foglie, insetti da rimuovere regolarmente.",
    "guidesData.reminder_test_water_action": "Esegui un test completo (pH, cloro, TAC).",
    "guidesData.reminder_test_water_detail": "È il momento di testare la tua acqua.",
    "guidesData.reminder_test_water_title": "Test dell'acqua",
    "guidesData.reminder_winterize_action": "Azione per winterize",
    "guidesData.reminder_winterize_detail": "Dettaglio per winterize",
    "guidesData.reminder_winterize_title": "Invernalizzazione",

    # ===== guidesData.salt-system-basics.* (13) =====
    "guidesData.salt-system-basics.steps.1.detail": "Il sale (NaCl) viene elettrolizzato in cloro attivo in situ. Nessuno stoccaggio di cloro, acqua più dolce.",
    "guidesData.salt-system-basics.steps.1.title": "Il principio",
    "guidesData.salt-system-basics.steps.2.detail": "In base al modello: generalmente 3-7 g/L. Verifica il manuale. Troppo basso = nessuna produzione; troppo alto = sovraconsumo.",
    "guidesData.salt-system-basics.steps.2.title": "Livello di sale richiesto",
    "guidesData.salt-system-basics.steps.3.detail": "Senza stabilizzante, il cloro prodotto viene distrutto dal sole in 2h.",
    "guidesData.salt-system-basics.steps.3.title": "Stabilizzante (CYA) indispensabile",
    "guidesData.salt-system-basics.steps.4.detail": "L'elettrolizzatore fa salire il pH. Regolazione frequente necessaria.",
    "guidesData.salt-system-basics.steps.4.title": "Monitorare il pH",
    "guidesData.salt-system-basics.steps.5.detail": "In acqua fredda (< 15°C), la produzione cala. Non preoccuparsi in inverno.",
    "guidesData.salt-system-basics.steps.5.title": "Produzione in base alla temperatura",
    "guidesData.salt-system-basics.steps.6.detail": "Pulizia acida ogni 3-6 mesi a seconda della durezza dell'acqua.",
    "guidesData.salt-system-basics.steps.6.title": "Manutenzione cellula",
    "guidesData.salt-system-basics.summary": "Principio, livello di sale, produzione, manutenzione ordinaria.",
    "guidesData.salt-system-basics.title": "Comprendere il proprio elettrolizzatore a sale",

    # ===== guidesData.startup.* (15) =====
    "guidesData.startup.steps.1.detail": "Rimuovere foglie e detriti accumulati.",
    "guidesData.startup.steps.1.title": "Rimuovere la copertura e pulire",
    "guidesData.startup.steps.2.detail": "Ripristinare il livello.",
    "guidesData.startup.steps.2.title": "Riempire se il livello è basso",
    "guidesData.startup.steps.3.detail": "Controllare il filtro (backwash se necessario).",
    "guidesData.startup.steps.3.title": "Avviare la filtrazione",
    "guidesData.startup.steps.4.detail": "pH, cloro, TAC, stabilizzante.",
    "guidesData.startup.steps.4.title": "Testare l'acqua",
    "guidesData.startup.steps.5.detail": "TAC → pH → cloro. Nessuna fretta.",
    "guidesData.startup.steps.5.title": "Equilibrare gradualmente",
    "guidesData.startup.steps.6.detail": "Per ripartire da una base sana.",
    "guidesData.startup.steps.6.title": "Eseguire un trattamento shock",
    "guidesData.startup.steps.7.detail": "Pompa, elettrolizzatore, guarnizioni, manometro.",
    "guidesData.startup.steps.7.title": "Controllare le attrezzature",
    "guidesData.startup.summary": "Risvegliare la piscina dopo l'inverno dolcemente.",
    "guidesData.startup.title": "Riavvio primaverile",

    # ===== guidesData.swim-safety.* (13) =====
    "guidesData.swim-safety.steps.1.detail": "Fuori da questo range: possibile irritazione.",
    "guidesData.swim-safety.steps.1.title": "pH tra 7.0 e 7.6",
    "guidesData.swim-safety.steps.2.detail": "Meno = disinfezione insufficiente. Più = irritazione.",
    "guidesData.swim-safety.steps.2.title": "Cloro libero tra 1 e 3 mg/L",
    "guidesData.swim-safety.steps.3.detail": "Sopra: odore forte, occhi che bruciano.",
    "guidesData.swim-safety.steps.3.title": "Cloro combinato < 0.4 mg/L",
    "guidesData.swim-safety.steps.4.detail": "2h dopo pH, 8h dopo cloro shock.",
    "guidesData.swim-safety.steps.4.title": "Rispettare i tempi dopo il trattamento",
    "guidesData.swim-safety.steps.5.detail": "Meglio attendere un test che entrare in acqua dubbia.",
    "guidesData.swim-safety.steps.5.title": "In caso di dubbio: non nuotare",
    "guidesData.swim-safety.summary": "Criteri di sicurezza per un bagno senza rischi.",
    "guidesData.swim-safety.title": "Sicurezza bagno: quando si può nuotare?",

    # ===== guidesData.tac-control.* (13) =====
    "guidesData.tac-control.steps.1.detail": "Il TAC (alcalinità totale) stabilizza il pH. Senza di esso, il pH salta a ogni aggiunta di prodotto.",
    "guidesData.tac-control.steps.1.title": "Ruolo del TAC",
    "guidesData.tac-control.steps.2.detail": "Obiettivo 100 mg/L.",
    "guidesData.tac-control.steps.2.title": "Range ideale 80-120 mg/L",
    "guidesData.tac-control.steps.3.detail": "Equilibrare sempre prima il TAC, altrimenti il pH non si manterrà.",
    "guidesData.tac-control.steps.3.title": "Regolare PRIMA del pH",
    "guidesData.tac-control.steps.4.detail": "Diluire, distribuire, filtrazione 3h.",
    "guidesData.tac-control.steps.4.title": "Per alzare: bicarbonato di sodio",
    "guidesData.tac-control.steps.5.detail": "Più complesso, da fare lentamente con un pH-.",
    "guidesData.tac-control.steps.5.title": "Per abbassare: acido",
    "guidesData.tac-control.summary": "Il TAC è il tampone del pH. Senza un buon TAC, il pH diventa instabile.",
    "guidesData.tac-control.title": "Comprendere l'alcalinità (TAC)",

    # ===== guidesData.tag_* (16) =====
    "guidesData.tag_algues": "alghe",
    "guidesData.tag_backwash": "backwash",
    "guidesData.tag_cartouche": "cartuccia",
    "guidesData.tag_chloramines": "clorammine",
    "guidesData.tag_chlore": "cloro",
    "guidesData.tag_choc": "shock",
    "guidesData.tag_debutant": "principiante",
    "guidesData.tag_electrolyseur": "elettrolizzatore",
    "guidesData.tag_filtration": "filtrazione",
    "guidesData.tag_filtre": "filtro",
    "guidesData.tag_floculant": "flocculante",
    "guidesData.tag_odeur": "odore",
    "guidesData.tag_securite": "sicurezza",
    "guidesData.tag_sel": "sale",
    "guidesData.tag_trouble": "torbida",
    "guidesData.tag_vert": "verde",
    "guidesData.tag_yeux": "occhi",

    # ===== guidesData.vacation-mode.* (15) =====
    "guidesData.vacation-mode.steps.1.detail": "Equilibrare tutto prima della partenza: pH, cloro, TAC.",
    "guidesData.vacation-mode.steps.1.title": "Eseguire un test completo",
    "guidesData.vacation-mode.steps.2.detail": "Disinfettare in profondità.",
    "guidesData.vacation-mode.steps.2.title": "Cloro shock la vigilia",
    "guidesData.vacation-mode.steps.3.detail": "Per un'assenza < 1 settimana.",
    "guidesData.vacation-mode.steps.3.title": "Riempire il distributore di cloro lento",
    "guidesData.vacation-mode.steps.4.detail": "Almeno 4-6h/giorno, preferibilmente di notte.",
    "guidesData.vacation-mode.steps.4.title": "Impostare il timer di filtrazione",
    "guidesData.vacation-mode.steps.5.detail": "Telo o copertura: limita detriti ed evaporazione.",
    "guidesData.vacation-mode.steps.5.title": "Coprire la piscina",
    "guidesData.vacation-mode.steps.6.detail": "Fatti fare un controllo o installa un robot.",
    "guidesData.vacation-mode.steps.6.title": "Per un'assenza lunga: vicino o robot",
    "guidesData.vacation-mode.steps.7.detail": "In estate, una filtrazione ridotta basta. In inverno, invernalizzazione completa.",
    "guidesData.vacation-mode.steps.7.title": "In base alla stagione: invernalizzazione attiva o passiva",
    "guidesData.vacation-mode.summary": "Preparare la piscina per un'assenza di diversi giorni/settimane.",
    "guidesData.vacation-mode.title": "Prima di partire in vacanza",

    # ===== guidesData.winterization.* (15) =====
    "guidesData.winterization.steps.1.detail": "Attiva: filtrazione ridotta. Passiva: arresto totale. Dipende dal clima.",
    "guidesData.winterization.steps.1.title": "Scegliere invernalizzazione attiva o passiva",
    "guidesData.winterization.steps.2.detail": "Acqua, pareti, fondo, filtro, linea di galleggiamento.",
    "guidesData.winterization.steps.2.title": "Pulizia profonda",
    "guidesData.winterization.steps.3.detail": "Prodotto di invernalizzazione, anti-alghe e anti-calcare.",
    "guidesData.winterization.steps.3.title": "Eseguire un trattamento invernale",
    "guidesData.winterization.steps.4.detail": "10-15 cm sotto gli ugelli per la passiva.",
    "guidesData.winterization.steps.4.title": "Abbassare il livello dell'acqua",
    "guidesData.winterization.steps.5.detail": "Proteggere dal gelo.",
    "guidesData.winterization.steps.5.title": "Svuotare le tubazioni sensibili",
    "guidesData.winterization.steps.6.detail": "Telo invernale o copertura.",
    "guidesData.winterization.steps.6.title": "Coprire la piscina",
    "guidesData.winterization.steps.7.detail": "Soprattutto durante i periodi di gelo.",
    "guidesData.winterization.steps.7.title": "Invernalizzazione attiva: filtrazione 2-3h/giorno",
    "guidesData.winterization.summary": "Mettere la piscina in invernalizzazione per l'inverno senza danneggiare le attrezzature.",
    "guidesData.winterization.title": "Invernalisare la piscina",

    # ===== landing.* (12) =====
    "landing.faqEyebrow": "12 — FAQ",
    "landing.footerBlog": "Blog",
    "landing.footerPrivacy": "Privacy",
    "landing.footerProductFaq": "FAQ",
    "landing.footerVersion": "v2.0 Copilot",
    "landing.heroPhoneChlorine": "Cloro",
    "landing.heroPhoneStep1": "1. pH- 900 ml",
    "landing.navFaq": "FAQ",
    "landing.savingsBar1": "AQWELIA Premium",
    "landing.spaBrandCategoryEco": "Eco",
    "landing.spaBrandCategoryPremium": "Premium",
    "landing.variationsFactor6Title": "UV",

    # ===== legal.backHome + legal.lastUpdatedLabel (2) =====
    "legal.backHome": "Torna alla home",
    "legal.lastUpdatedLabel": "Ultimo aggiornamento:",

    # ===== legal.cgu.* (65) =====
    "legal.cgu.article10Body1": "AQWELIA fa tutto il possibile per garantire la disponibilità e l'affidabilità del Servizio, ma non può garantire un'assenza totale di errori o interruzioni.",
    "legal.cgu.article10Body2": "Essendo il Servizio fornito a titolo indicativo, AQWELIA non può essere ritenuta responsabile dei danni diretti o indiretti derivanti dall'applicazione delle raccomandazioni (in particolare: danni materiali, perdita di balneazione, deterioramento delle attrezzature, reazioni chimiche). In caso di dubbio, l'Utente deve consultare un professionista.",
    "legal.cgu.article10Title": "Articolo 10 — Responsabilità",
    "legal.cgu.article11Body1": "Tutti gli elementi del Servizio (marchio, logo, testi, algoritmi, design, guide) sono di proprietà esclusiva di AQWELIA o dei suoi partner. Qualsiasi riproduzione, rappresentazione o diffusione, totale o parziale, senza previa autorizzazione scritta è vietata.",
    "legal.cgu.article11Body2": "I Dati inseriti dall'Utente rimangono di sua proprietà. L'Utente concede a AQWELIA una licenza non esclusiva di utilizzo di tali Dati nella misura necessaria alla fornitura e al miglioramento del Servizio.",
    "legal.cgu.article11Title": "Articolo 11 — Proprietà intellettuale",
    "legal.cgu.article12Body1": "AQWELIA può modificare in qualsiasi momento i presenti CGU. I CGU applicabili sono quelli in vigore al momento dell'utilizzo del Servizio. Le modifiche sostanziali saranno notificate via e-mail o tramite l'applicazione almeno 30 giorni prima della loro entrata in vigore.",
    "legal.cgu.article12Title": "Articolo 12 — Modifiche ai CGU",
    "legal.cgu.article13Body1": "I presenti CGU sono regolati dal diritto francese. In caso di controversia, le parti si impegnano a cercare una soluzione amichevole prima di qualsiasi azione legale. In mancanza di accordo, i tribunali francesi avranno giurisdizione esclusiva.",
    "legal.cgu.article13Title": "Articolo 13 — Diritto applicabile",
    "legal.cgu.article1Body1": "I presenti Termini e Condizioni di Utilizzo (« <bold>CGU</bold> ») definiscono le modalità e le condizioni di accesso e di utilizzo dell'applicazione AQWELIA (« <bold>il Servizio</bold> »), edita dalla società AQWELIA, nonché i diritti e gli obblighi delle parti in tale ambito.",
    "legal.cgu.article1Body2": "L'utilizzo del Servizio implica l'accettazione piena e completa dei presenti CGU. Se non si è d'accordo con una qualsiasi di queste condizioni, non si deve utilizzare il Servizio.",
    "legal.cgu.article1Title": "Articolo 1 — Oggetto",
    "legal.cgu.article2Item1": "« <bold>Utente</bold> »: qualsiasi persona fisica che utilizza il Servizio.",
    "legal.cgu.article2Item2": "« <bold>Account</bold> »: spazio personale creato dall'Utente per accedere al Servizio.",
    "legal.cgu.article2Item3": "« <bold>Dati</bold> »: informazioni inserite dall'Utente (misure, foto, profilo piscina, ecc.).",
    "legal.cgu.article2Item4": "« <bold>Piano</bold> »: formula di abbonamento (Free, Premium o Expert) a cui l'Utente si iscrive.",
    "legal.cgu.article2Item5": "« <bold>Contenuto</bold> »: raccomandazioni, piani d'azione, analisi, guide e testi generati dal Servizio.",
    "legal.cgu.article2Title": "Articolo 2 — Definizioni",
    "legal.cgu.article3Body1": "AQWELIA è un copilota intelligente per la manutenzione della piscina. Il Servizio consente all'Utente di:",
    "legal.cgu.article3Body2": "Il Servizio è fornito a titolo indicativo e non sostituisce l'intervento di un professionista qualificato (piscinaro, rivenditore, bagnino).",
    "legal.cgu.article3Item1": "monitorare e analizzare la qualità dell'acqua della propria piscina (pH, cloro, TAC, TH, ecc.);",
    "legal.cgu.article3Item2": "ottenere piani d'azione personalizzati (dosaggi, filtrazione, balneabilità);",
    "legal.cgu.article3Item3": "diagnosticare visivamente l'acqua e le attrezzature tramite foto;",
    "legal.cgu.article3Item4": "consultare un assistente IA per qualsiasi domanda di manutenzione;",
    "legal.cgu.article3Item5": "ricevere promemoria intelligenti (meteo, attrezzature, scorte prodotti);",
    "legal.cgu.article3Item6": "consultare guide e risorse didattiche.",
    "legal.cgu.article3Title": "Articolo 3 — Descrizione del servizio",
    "legal.cgu.article4Body1": "La registrazione al Servizio richiede la creazione di un Account tramite un indirizzo e-mail valido e una password. L'Utente si impegna a fornire informazioni accurate e a mantenerle aggiornate.",
    "legal.cgu.article4Body2": "L'Utente è l'unico responsabile della riservatezza delle proprie credenziali e di qualsiasi utilizzo del proprio Account. Qualsiasi attività effettuata dal proprio Account si presume svolta dall'Utente.",
    "legal.cgu.article4Body3": "AQWELIA si riserva il diritto di rifiutare o chiudere un Account in caso di mancato rispetto dei presenti CGU o di comportamento fraudolento.",
    "legal.cgu.article4Title": "Articolo 4 — Registrazione e account",
    "legal.cgu.article5Body1": "L'Utente si impegna a:",
    "legal.cgu.article5Body2": "L'Utente riconosce che le raccomandazioni fornite dal Servizio sono indicative e che rimane l'unico responsabile degli atti compiuti sulla propria piscina.",
    "legal.cgu.article5Item1": "utilizzare il Servizio in conformità alla sua destinazione d'uso e al diritto applicabile;",
    "legal.cgu.article5Item2": "non tentare di deviare, disabilitare o compromettere la sicurezza del Servizio;",
    "legal.cgu.article5Item3": "non caricare Contenuti illeciti, diffamatori o che ledano i diritti di terzi;",
    "legal.cgu.article5Item4": "rispettare le istruzioni dei prodotti chimici utilizzati per la manutenzione della propria piscina.",
    "legal.cgu.article5Title": "Articolo 5 — Utilizzo del servizio",
    "legal.cgu.article6Body1": "Il Servizio offre tre Piani:",
    "legal.cgu.article6Body2": "Le funzionalità e le tariffe di ciascun Piano sono dettagliate sulla pagina <link>Tariffe</link>. AQWELIA si riserva il diritto di modificare queste offerte in qualsiasi momento, previa informazione degli Utenti abbonati almeno 30 giorni prima dell'entrata in vigore.",
    "legal.cgu.article6Item1": "<bold>Free</bold>: gratuito, include 1 piscina, misurazioni manuali di base, assistente limitato.",
    "legal.cgu.article6Item2": "<bold>Premium</bold>: fino a 3 piscine, diagnostica foto illimitata, assistente IA completo, promemoria meteo, guide avanzate.",
    "legal.cgu.article6Item3": "<bold>Expert</bold>: illimitato (piscinari professionisti), multi-cliente, esportazioni, supporto prioritario.",
    "legal.cgu.article6Title": "Articolo 6 — Abbonamenti",
    "legal.cgu.article7Body1": "Il pagamento degli abbonamenti Premium ed Expert avviene secondo la piattaforma utilizzata:",
    "legal.cgu.article7Body2": "Il rinnovo è automatico al termine del periodo sottoscritto, salvo disattivazione da parte dell'Utente nelle impostazioni del proprio account Apple/Google o tramite il portale clienti Stripe.",
    "legal.cgu.article7Item1": "<bold>Web</bold>: tramite Stripe (carta bancaria, pagamento sicuro).",
    "legal.cgu.article7Item2": "<bold>iOS</bold>: tramite Apple In-App Purchase (gestito da Apple).",
    "legal.cgu.article7Item3": "<bold>Android</bold>: tramite Google Play Billing (gestito da Google).",
    "legal.cgu.article7Title": "Articolo 7 — Pagamento",
    "legal.cgu.article8Body1": "L'Utente può recedere dal proprio abbonamento in qualsiasi momento dall'applicazione (pagina <link>Impostazioni</link>) o dalle impostazioni dell'App Store / Google Play. Il recesso ha effetto alla fine del periodo di fatturazione in corso.",
    "legal.cgu.article8Body2": "AQWELIA si riserva il diritto di recedere o sospendere l'accesso al Servizio in caso di inosservanza dei CGU, previa notifica salvo urgenza.",
    "legal.cgu.article8Title": "Articolo 8 — Recesso",
    "legal.cgu.article9Body1": "Il trattamento dei dati personali dell'Utente è regolato dalla nostra <link>Politica sulla riservatezza</link>, in conformità al Regolamento Generale sulla Protezione dei Dati (GDPR, UE 2016/679).",
    "legal.cgu.article9Body2": "L'Utente ha diritto di accesso, rettifica, cancellazione, portabilità e opposizione. Questi diritti possono essere esercitati dalla pagina <link>Impostazioni</link> o via e-mail all'indirizzo <alink>privacy@aqwelia.app</alink>.",
    "legal.cgu.article9Title": "Articolo 9 — Dati personali (GDPR)",
    "legal.cgu.contactBody1": "Per qualsiasi domanda relativa ai presenti CGU: <alink>legal@aqwelia.app</alink>",
    "legal.cgu.contactBody2": "Per qualsiasi domanda relativa ai tuoi dati: <alink>privacy@aqwelia.app</alink>",
    "legal.cgu.contactBody3": "Per qualsiasi richiesta di supporto: <link>pagina Supporto</link>.",
    "legal.cgu.contactTitle": "Contatto",
    "legal.cgu.eyebrow": "Note legali",
    "legal.cgu.metaDescription": "Termini e condizioni di utilizzo del servizio AQWELIA.",
    "legal.cgu.metaTitle": "Termini di utilizzo — AQWELIA",
    "legal.cgu.title": "Termini e Condizioni di Utilizzo",

    # ===== legal.privacy.* (74) =====
    "legal.privacy.eyebrow": "GDPR",
    "legal.privacy.metaDescription": "Politica di protezione dei dati personali AQWELIA (GDPR).",
    "legal.privacy.metaTitle": "Politica sulla riservatezza — AQWELIA",
    "legal.privacy.section10Body1": "AQWELIA implementa le misure tecniche e organizzative adeguate per proteggere i tuoi dati:",
    "legal.privacy.section10Body2": "In caso di violazione dei dati suscettibile di comportare un rischio per i tuoi diritti e le tue libertà, AQWELIA ti notificherà senza ingiustificato ritardo in conformità all'articolo 34 del GDPR.",
    "legal.privacy.section10Item1": "cifratura delle password (scrypt, algoritmo resistente agli attacchi brute-force);",
    "legal.privacy.section10Item2": "cifratura dei dati in transito (TLS 1.2+) e a riposo (cifratura del database);",
    "legal.privacy.section10Item3": "autenticazione tramite JWT firmato, durata limitata (30 giorni);",
    "legal.privacy.section10Item4": "accesso limitato ai dati personali (principio del minimo privilegio);",
    "legal.privacy.section10Item5": "backup cifrati e test di penetrazione regolari.",
    "legal.privacy.section10Title": "10. Sicurezza",
    "legal.privacy.section11Body1": "Per qualsiasi domanda relativa alla protezione dei tuoi dati, contatta il nostro DPO:",
    "legal.privacy.section11Body2": "Vedi anche i nostri <link>CGU</link> e la nostra <link2>pagina Supporto</link2>.",
    "legal.privacy.section11Title": "11. Contatto DPO",
    "legal.privacy.section1Body1": "Il titolare del trattamento dei dati personali raccolti tramite l'applicazione AQWELIA è la società <bold>AQWELIA</bold>, editrice del Servizio.",
    "legal.privacy.section1Body2": "Contatto DPO: <alink>privacy@aqwelia.app</alink>",
    "legal.privacy.section1Title": "1. Titolare del trattamento",
    "legal.privacy.section2Body1": "Il Servizio raccoglie le seguenti categorie di dati:",
    "legal.privacy.section2Item1": "<bold>Identificativi dell'account</bold>: indirizzo e-mail, nome (facoltativo), password (con hash).",
    "legal.privacy.section2Item2": "<bold>Profilo piscina</bold>: volume, forma, rivestimento, trattamento, filtro, esposizione, regione.",
    "legal.privacy.section2Item3": "<bold>Dati dell'acqua</bold>: misurazioni (pH, cloro, TAC, TH, CYA, sale, temperatura, ecc.) inserite o importate.",
    "legal.privacy.section2Item4": "<bold>Foto</bold>: immagini dell'acqua, delle pareti, del filtro, degli elettrolizzatori e dei prodotti, utilizzate per la diagnostica visiva IA.",
    "legal.privacy.section2Item5": "<bold>Attrezzature e inventario</bold>: marchio, modello, date di manutenzione, prodotti chimici in stock.",
    "legal.privacy.section2Item6": "<bold>Cronologia</bold>: conversazioni con l'assistente IA, piani d'azione generati, diagnostiche foto.",
    "legal.privacy.section2Item7": "<bold>Dati di fatturazione</bold>: piano sottoscritto, periodo, stato (le informazioni di pagamento sono trattate da Stripe, Apple o Google — AQWELIA non memorizza i numeri di carta).",
    "legal.privacy.section2Item8": "<bold>Dati di utilizzo</bold>: eventi analytics (consultazione delle guide, apertura del paywall, frequenza di utilizzo).",
    "legal.privacy.section2Title": "2. Dati raccolti",
    "legal.privacy.section3Body1": "I dati sono trattati per le seguenti finalità:",
    "legal.privacy.section3Item1": "funzionamento del Servizio (generazione di piani d'azione, calcoli dei dosaggi, monitoraggio dell'acqua);",
    "legal.privacy.section3Item2": "miglioramento dei modelli di IA (diagnostica foto, raccomandazioni) — sulla base di una preliminare anonimizzazione quando possibile;",
    "legal.privacy.section3Item3": "fatturazione e gestione degli abbonamenti;",
    "legal.privacy.section3Item4": "supporto agli utenti;",
    "legal.privacy.section3Item5": "analisi dell'utilizzo e miglioramento dell'esperienza;",
    "legal.privacy.section3Item6": "rispetto degli obblighi legali e contabili.",
    "legal.privacy.section3Title": "3. Finalità",
    "legal.privacy.section4Body1": "In conformità all'articolo 6 del GDPR, i trattamenti si basano sulle seguenti basi giuridiche:",
    "legal.privacy.section4Body2": "L'Utente può revocare il proprio consenso in qualsiasi momento dalla pagina <link>Impostazioni</link>, senza pregiudicare la liceità del trattamento precedente.",
    "legal.privacy.section4Item1": "<bold>Esecuzione del contratto</bold> (art. 6.1.b): fornitura del Servizio sottoscritto.",
    "legal.privacy.section4Item2": "<bold>Consenso</bold> (art. 6.1.a): foto inviate per la diagnostica, notifiche, eventuali comunicazioni di marketing.",
    "legal.privacy.section4Item3": "<bold>Interesse legittimo</bold> (art. 6.1.f): miglioramento del Servizio, sicurezza, prevenzione delle frodi.",
    "legal.privacy.section4Item4": "<bold>Obbligo legale</bold> (art. 6.1.c): conservazione delle fatture e delle tracce contabili.",
    "legal.privacy.section4Title": "4. Base giuridica",
    "legal.privacy.section5Item1": "<bold>Account attivo</bold>: durata di utilizzo del Servizio.",
    "legal.privacy.section5Item2": "<bold>Dati della piscina, misurazioni, foto</bold>: conservati finché l'Account è attivo, più 90 giorni dopo l'eliminazione (per eventuale ripristino), poi cancellati definitivamente.",
    "legal.privacy.section5Item3": "<bold>Fatture</bold>: 10 anni (obbligo contabile legale in Francia).",
    "legal.privacy.section5Item4": "<bold>Log di sicurezza</bold>: 12 mesi.",
    "legal.privacy.section5Item5": "<bold>Account inattivo</bold>: dopo 24 mesi senza accesso, notifica via e-mail poi eliminazione dell'Account e dei suoi dati.",
    "legal.privacy.section5Title": "5. Periodo di conservazione",
    "legal.privacy.section6Body1": "I dati sono accessibili ai seguenti destinatari:",
    "legal.privacy.section6Body2": "AQWELIA non vende mai i tuoi dati a terzi per finalità di marketing.",
    "legal.privacy.section6Item1": "<bold>AQWELIA</bold>: personale autorizzato (ingegneri, supporto) con accordo di riservatezza.",
    "legal.privacy.section6Item2": "<bold>Provider cloud</bold>: archiviazione e calcolo (situato nell'UE).",
    "legal.privacy.section6Item3": "<bold>Stripe</bold>: trattamento dei pagamenti web (soggetto al proprio GDPR).",
    "legal.privacy.section6Item4": "<bold>RevenueCat</bold>: gestione unificata degli abbonamenti iOS/Android.",
    "legal.privacy.section6Item5": "<bold>Apple / Google</bold>: pagamenti In-App (soggetti alle proprie condizioni).",
    "legal.privacy.section6Item6": "<bold>Provider IA</bold>: per la diagnostica foto e l'assistente — solo i dati strettamente necessari, senza memorizzazione oltre la sessione.",
    "legal.privacy.section6Title": "6. Destinatari",
    "legal.privacy.section7Body1": "L'hosting principale è situato nell'Unione Europea. Qualsiasi eventuale trasferimento al di fuori dell'UE (ad esempio verso un provider IA con sede negli Stati Uniti) è disciplinato dalle clausole contrattuali tipo della Commissione Europea (decisione 2021/914) e accompagnato da adeguate garanzie (cifratura, minimizzazione, pseudonimizzazione).",
    "legal.privacy.section7Title": "7. Trasferimenti al di fuori dell'UE",
    "legal.privacy.section8Body1": "In conformità agli articoli da 15 a 22 del GDPR, hai i seguenti diritti:",
    "legal.privacy.section8Body2": "Questi diritti possono essere esercitati direttamente dalla pagina <link>Impostazioni</link> (esportazione JSON, eliminazione dell'account), o via e-mail all'indirizzo <alink>privacy@aqwelia.app</alink>.",
    "legal.privacy.section8Body3": "Puoi anche presentare un reclamo al Garante per la protezione dei dati personali (www.garanteprivacy.it) o all'autorità di controllo del tuo Paese.",
    "legal.privacy.section8Item1": "<bold>Diritto di accesso</bold>: ottenere una copia dei tuoi dati.",
    "legal.privacy.section8Item2": "<bold>Diritto di rettifica</bold>: correggere dati inesatti.",
    "legal.privacy.section8Item3": "<bold>Diritto alla cancellazione</bold> (« diritto all'oblio »): eliminare il tuo Account e i tuoi dati.",
    "legal.privacy.section8Item4": "<bold>Diritto alla portabilità</bold>: ricevere i tuoi dati in un formato strutturato e riutilizzabile.",
    "legal.privacy.section8Item5": "<bold>Diritto di opposizione</bold>: rifiutare un trattamento fondato sull'interesse legittimo.",
    "legal.privacy.section8Item6": "<bold>Diritto di limitazione</bold>: congelare temporaneamente un trattamento.",
    "legal.privacy.section8Item7": "<bold>Diritto di revocare il tuo consenso</bold> in qualsiasi momento.",
    "legal.privacy.section8Title": "8. I tuoi diritti",
    "legal.privacy.section9Body1": "AQWELIA utilizza un minimo di tracker strettamente necessari al funzionamento del Servizio (sessione di autenticazione, preferenze di lingua e tema). Nessun cookie pubblicitario o di tracciamento di terze parti viene depositato senza consenso.",
    "legal.privacy.section9Body2": "Le preferenze possono essere gestite dalla pagina <link>Impostazioni</link>.",
    "legal.privacy.section9Title": "9. Cookie e tracker",
    "legal.privacy.title": "Politica sulla riservatezza",

    # ===== legal.support.* (34) =====
    "legal.support.cardAssistantDesc": "Per una domanda rapida sulla tua piscina, chiedi all'assistente direttamente nell'app.",
    "legal.support.cardAssistantLink": "Apri l'app",
    "legal.support.cardAssistantTitle": "Assistente IA integrato",
    "legal.support.cardBugDesc": "Hai notato un comportamento imprevisto? Descrivicelo con uno screenshot se possibile.",
    "legal.support.cardBugLink": "Segnala via email",
    "legal.support.cardBugTitle": "Segnala un bug",
    "legal.support.cardFaqDesc": "Risposte alle domande più frequenti: abbonamenti, dati, piscina, compatibilità.",
    "legal.support.cardFaqLink": "Vedi la FAQ",
    "legal.support.cardFaqTitle": "FAQ",
    "legal.support.cardFeatureDesc": "Un'idea per migliorare AQWELIA? Leggiamo tutti i suggerimenti.",
    "legal.support.cardFeatureLink": "Condividi la mia idea",
    "legal.support.cardFeatureSubject": "Idea funzionalità AQWELIA",
    "legal.support.cardFeatureTitle": "Richiedi una funzionalità",
    "legal.support.cardKbDesc": "Guide dettagliate, tutorial video e articoli di aiuto. Prossimamente.",
    "legal.support.cardKbLink": "Prossimamente",
    "legal.support.cardKbTitle": "Base di conoscenza",
    "legal.support.cardLegalDesc": "Per argomenti GDPR, riservatezza o CGU, scrivi a privacy@aqwelia.app.",
    "legal.support.cardLegalLink": "Contatta il DPO",
    "legal.support.cardLegalTitle": "Questioni legali",
    "legal.support.emailDesc": "Il modo migliore per contattarci. Risposta entro 48 ore lavorative.",
    "legal.support.emailTitle": "Email",
    "legal.support.eyebrow": "Aiuto e supporto",
    "legal.support.metaDescription": "Contattare il supporto AQWELIA, FAQ, segnalare un bug, richiedere una funzionalità.",
    "legal.support.metaTitle": "Supporto — AQWELIA",
    "legal.support.resourcesCguLink": "Termini di utilizzo",
    "legal.support.resourcesPrivacyLink": "Politica sulla riservatezza",
    "legal.support.resourcesSettingsLink": "Impostazioni account",
    "legal.support.resourcesTitle": "Risorse correlate",
    "legal.support.responseTimeExpert": "<bold>Piano Expert</bold>: risposta entro 24h, supporto prioritario.",
    "legal.support.responseTimeFree": "<bold>Piano Free</bold>: risposta entro 72 ore lavorative.",
    "legal.support.responseTimePremium": "<bold>Piano Premium</bold>: risposta entro 48 ore lavorative.",
    "legal.support.responseTimeTitle": "Tempo di risposta",
    "legal.support.subtitle": "Il nostro team è disponibile per aiutarti a ottenere il massimo da AQWELIA.",
    "legal.support.title": "Contatta il supporto",

    # ===== metadata.* (7) =====
    "metadata.layoutDescription": "AQWELIA — l'app rivoluzionaria di gestione piscina alimentata dall'IA: assistente esperto, analisi visiva dell'acqua, piano d'azione deterministico e altro ancora.",
    "metadata.layoutKeywordAI": "IA",
    "metadata.layoutKeywordMaintenance": "manutenzione",
    "metadata.layoutKeywordPool": "piscina",
    "metadata.layoutKeywordSmartAssistant": "assistente intelligente",
    "metadata.layoutKeywordWaterQuality": "qualità acqua",
    "metadata.layoutTitle": "AQWELIA — Copilota Intelligente per Piscina",

    # ===== mobile.screens.* (18) =====
    "mobile.screens.analysesAriaSubtabs": "Sotto-schede Analisi",
    "mobile.screens.analysesSubtabLogbook": "Registro",
    "mobile.screens.analysesSubtabMesures": "Misurazioni",
    "mobile.screens.analysesSubtabPhoto": "Foto",
    "mobile.screens.maintenanceAriaSubtabs": "Sotto-schede Manutenzione",
    "mobile.screens.maintenanceSubtabActions": "Azioni",
    "mobile.screens.profileAriaPoolProfile": "Profilo piscina",
    "mobile.screens.profileAriaSettings": "Impostazioni",
    "mobile.screens.profileAriaSubscription": "Abbonamento",
    "mobile.screens.profileConfigureToStart": "Configura la tua piscina per iniziare",
    "mobile.screens.profileElectrolysisSalt": "Elettrolisi sale",
    "mobile.screens.profileFaqContact": "FAQ + contatto",
    "mobile.screens.profileHelpSupport": "Aiuto e supporto",
    "mobile.screens.profileNotifReminders": "Notifiche e promemoria",
    "mobile.screens.profilePoolNotConfigured": "Piscina non configurata",
    "mobile.screens.profilePrivacyData": "Riservatezza e dati",
    "mobile.screens.profileSubscriptionTitle": "Abbonamento",
    "mobile.screens.profileVersionLine": "AQWELIA Pro · v1.0.0-mobile",

    # ===== modules.* (12) =====
    "modules.dashboard.labelTac": "TAC",
    "modules.dashboard.labelTemp": "Temp.",
    "modules.guides.min": "min",
    "modules.guides.premiumBadge": "PREMIUM",
    "modules.healthLog.alkalinity": "TAC",
    "modules.maintenance.equipmentTypes.robot": "Robot",
    "modules.maintenance.equipmentTypes.skimmer": "Skimmer",
    "modules.maintenance.productCategories.alkalinity_plus": "TAC+",
    "modules.maintenance.productCategories.ph_minus": "pH-",
    "modules.maintenance.productCategories.ph_plus": "pH+",
    "modules.waterTest.filtration": "Filtr.",
    "modules.waterTest.statusOk": "Ok",

    # ===== nav.* (6) =====
    "nav.home": "Home",
    "nav.landing": "Landing",
    "nav.premium": "AQWELIA Premium",
    "nav.pro": "Pro",
    "nav.shortPremium": "Premium",
    "nav.shortPremiumBadge": "PREMIUM",

    # ===== navGroups.home (1) =====
    "navGroups.home": "Home",

    # ===== onboarding.* (4) =====
    "onboarding.spa": "Spa",
    "onboarding.surfaceLiner": "Liner",
    "onboarding.treatmentUV": "UV",
    "onboarding.volume": "Volume",

    # ===== plans.* (37) =====
    "plans.expert.features.accountingExport": "Esportazione contabile",
    "plans.expert.features.advancedTechNotes": "Note tecniche avanzate",
    "plans.expert.features.allPremium": "Tutto di Premium",
    "plans.expert.features.apiIntegrations": "API + integrazioni",
    "plans.expert.features.multiClients": "Multi-cliente illimitato",
    "plans.expert.features.photosBeforeAfter": "Foto prima/dopo",
    "plans.expert.features.quotesVisits": "Preventivi e pianificazione visite",
    "plans.expert.name": "Expert",
    "plans.free.features.1pool": "1 piscina",
    "plans.free.features.2scans": "2 scansioni foto / mese",
    "plans.free.features.5guides": "5 guide di base",
    "plans.free.features.clearWaterIndex": "Indice acqua limpida + sicurezza bagno",
    "plans.free.features.history14": "Cronologia 14 giorni",
    "plans.free.features.simpleWeather": "Meteo semplice",
    "plans.free.features.unlimitedManualTests": "Test dell'acqua illimitati (manuale)",
    "plans.gates.guides_premium": "Le guide premium sono riservate ai piani a pagamento.",
    "plans.gates.history_extended": "La cronologia estesa è riservata ai piani a pagamento.",
    "plans.gates.multi_pool": "Il multi-piscina è riservato a Premium ed Expert.",
    "plans.gates.pdf_report": "Il rapporto PDF è riservato a Premium ed Expert.",
    "plans.gates.photo_scan_limit": "Limite di {n} scansioni/mese raggiunto.",
    "plans.gates.pro_mode": "La modalità pro è riservata a Premium ed Expert.",
    "plans.gates.smart_reminders": "I promemoria intelligenti sono riservati ai piani a pagamento.",
    "plans.gates.spa_support": "Il supporto spa è riservato al piano Premium.",
    "plans.gates.weather_advanced": "La meteo avanzata è riservata ai piani a pagamento.",
    "plans.offline": "Offline",
    "plans.premium.features.3pools": "3 piscine",
    "plans.premium.features.advancedWeather": "Meteo avanzata + avvisi",
    "plans.premium.features.allGuidesVideos": "Tutte le guide + video",
    "plans.premium.features.pdfReport": "Rapporto PDF condivisibile",
    "plans.premium.features.prioritySupport": "Supporto prioritario",
    "plans.premium.features.proMode": "Modalità pro (LSI avanzato)",
    "plans.premium.features.smartReminders": "Promemoria intelligenti",
    "plans.premium.features.spaSupport": "Spa e acqua calda (bromo, ossigeno attivo)",
    "plans.premium.features.unlimitedHistory": "Cronologia illimitata",
    "plans.premium.features.unlimitedScans": "Scansioni foto illimitate",
    "plans.premium.name": "Premium",
    "plans.premiumLabel": "AQWELIA Premium",

    # ===== reminders.* (38) =====
    "reminders.cell_clean.action": "Smonta la cellula, immergi in una soluzione acida diluita 10-15 min, risciacqua.",
    "reminders.cell_clean.detail": "La cellula si incrosta con il tempo. Pulizia acida ogni 3-6 mesi.",
    "reminders.cell_clean.title": "Pulizia cellula elettrolizzatore",
    "reminders.equipment_overdue.action": "Pianifica una manutenzione per questa attrezzatura.",
    "reminders.equipment_overdue.detail": "Manutenzione in ritardo di {days} giorni.",
    "reminders.equipment_overdue.title": "Manutenzione {type}",
    "reminders.filter_clean.actionCartridge": "Smonta e risciacqua la cartuccia.",
    "reminders.filter_clean.actionSand": "Esegui un backwash (contro-lavaggio).",
    "reminders.filter_clean.detailCartridge": "Risciacquo della cartuccia consigliato.",
    "reminders.filter_clean.detailGeneric": "Controllo del filtro consigliato.",
    "reminders.filter_clean.detailSand": "Backwash del filtro a sabbia consigliato.",
    "reminders.filter_clean.title": "Pulizia del filtro",
    "reminders.low_product.action": "Pensa a riacquistarlo prima di esaurirlo.",
    "reminders.low_product.detail": "È rimasto poco di questo prodotto.",
    "reminders.low_product.title": "Scorta bassa: {name}",
    "reminders.retest_product.action": "Eseguire un altro test pH + cloro nelle ore successive.",
    "reminders.retest_product.detail": "Hai aggiunto un prodotto di recente. Verifica l'effetto.",
    "reminders.retest_product.title": "Re-test dopo il trattamento",
    "reminders.skimmer_clean.action": "Svuota il cestello dello skimmer e quello della pompa.",
    "reminders.skimmer_clean.detail": "Detriti, foglie, insetti da rimuovere regolarmente.",
    "reminders.skimmer_clean.title": "Controllare skimmer e cestello",
    "reminders.startup.action": "Segui la guida al riavvio: pulizia, trattamento, filtrazione.",
    "reminders.startup.detail": "La primavera arriva: prepara la piscina per la stagione.",
    "reminders.startup.title": "Riavvio di stagione",
    "reminders.test_first.action": "Inserisci il tuo primo test (pH minimo).",
    "reminders.test_first.detail": "Nessun test registrato. Attiva il monitoraggio.",
    "reminders.test_first.title": "Primo test dell'acqua",
    "reminders.test_overdue.action": "Esegui un test completo: pH + cloro + TAC.",
    "reminders.test_overdue.detail": "Ultimo test {days} giorni fa. La qualità dell'acqua cambia rapidamente.",
    "reminders.test_overdue.title": "Test dell'acqua da rifare",
    "reminders.test_soon.action": "Controlla pH e cloro libero.",
    "reminders.test_soon.detail": "Ultimo test {days} giorni fa.",
    "reminders.test_soon.title": "Test di routine",
    "reminders.winterize.action": "Segui la guida all'invernalizzazione: acqua fredda, prodotti invernali, copertura.",
    "reminders.winterize.detail": "L'autunno è arrivato: anticipa l'invernalizzazione.",
    "reminders.winterize.title": "Preparare l'invernalizzazione",
    "reminders.wx_test.action": "Testa pH e cloro.",
    "reminders.wx_test.title": "Test consigliato (meteo)",

    # ===== settings.* (7) =====
    "settings.deleteFailedDesc": "Eliminazione fallita",
    "settings.exportFailedDesc": "Esportazione fallita",
    "settings.marketplaceLabel": "Mercato: {marketplace}",
    "settings.planExpert": "Expert",
    "settings.planFree": "Free",
    "settings.planPremium": "Premium",
    "settings.unitsVolume": "Volume",

    # ===== spaData.* (18) =====
    "spaData.drainage_reason_intensive": "Uso intensivo rilevato — svuotamento consigliato ogni {months} mesi per evitare la saturazione di prodotti.",
    "spaData.drainage_reason_standard": "Svuotamento consigliato ogni {months} mesi (più economico del sovratrattamento).",
    "spaData.freq.config": "Configurazione",
    "spaData.freq.daily": "Quotidiano",
    "spaData.freq.every_3_4_months": "Ogni 3-4 mesi",
    "spaData.freq.per_drain": "A ogni svuotamento",
    "spaData.freq.per_usage": "Ad uso",
    "spaData.freq.weekly": "Settimanale",
    "spaData.rec_chlorine_evaporates": "⚠️ Il cloro evapora rapidamente in acqua calda. Passa al bromo per maggiore efficacia.",
    "spaData.rec_cover_after_use": "Copri la spa dopo ogni utilizzo per evitare l'evaporazione e la fotosintesi.",
    "spaData.rec_drain_economic": "Svuota ogni 3-4 mesi — è più economico del sovratrattare.",
    "spaData.rec_temp_critical_health": "🔴 Temperatura critica (>38°C) — rischio per la salute. Abbassa la temperatura.",
    "spaData.rec_temp_high_chlorine_warning": "⚠️ Temperatura elevata — il cloro NON è consigliato. Usa il bromo.",
    "spaData.rec_temp_high_session_limit": "Monitora la temperatura: oltre i 38°C, limita le sessioni a 15-20 min.",
    "spaData.seats_label": "Numero di posti a sedere",
    "spaData.usage_intensive": "Intensivo (5+/settimana)",
    "spaData.usage_occasional": "Occasionale (1-2x/settimana)",
    "spaData.usage_regular": "Regolare (3-4x/settimana)",

    # ===== weather.* (41) =====
    "weather.alerts.frost_risk.action": "Proteggi il locale tecnico. Lascia la filtrazione in funzione di notte per evitare il gelo. Invernalizza se non fatto.",
    "weather.alerts.frost_risk.message": "Temperatura negativa prevista. Rischio per le attrezzature e le tubazioni.",
    "weather.alerts.frost_risk.title": "Rischio di gelo",
    "weather.alerts.frost_risk.when": "Stanotte",
    "weather.alerts.heat_extreme.action": "Aumenta la filtrazione di 2h/giorno. Controlla il cloro ogni mattina. Considera un anti-alghe preventivo.",
    "weather.alerts.heat_extreme.message": "{temp} °C previsti. Acqua molto calda = cloro consumato più velocemente + proliferazione di alghe.",
    "weather.alerts.heat_extreme.title": "Ondata di calore prevista",
    "weather.alerts.heat_extreme.when": "Da adesso e durante l'ondata",
    "weather.alerts.heat_high.action": "Aumenta la filtrazione di 1h/giorno e testa il cloro domani.",
    "weather.alerts.heat_high.message": "{temp} °C previsti. Probabile sovraconsumo di cloro.",
    "weather.alerts.heat_high.title": "Forte caldo previsto",
    "weather.alerts.heat_high.when": "Domani mattina",
    "weather.alerts.heavy_rain.action": "Dopo la pioggia: controlla pH e cloro, pulisci lo skimmer e il cestello della pompa.",
    "weather.alerts.heavy_rain.message": "La pioggia diluisce i prodotti, fa abbassare il pH e porta detriti.",
    "weather.alerts.heavy_rain.title": "Piogge intense previste",
    "weather.alerts.heavy_rain.when": "Dopo la pioggia",
    "weather.alerts.storm_soon.action": "Controlla il cloro libero stasera prima del temporale. Aumenta la filtrazione domani.",
    "weather.alerts.storm_soon.message": "{percent} % di rischio di temporale. Il temporale diluisce il cloro e fa salire il pH.",
    "weather.alerts.storm_soon.title": "Temporale previsto domani",
    "weather.alerts.storm_soon.when": "Stasera prima delle 20:00",
    "weather.alerts.uv_high.action": "Controlla il tuo stabilizzante (CYA) e il cloro libero.",
    "weather.alerts.uv_high.message": "Il sole degrada il cloro non stabilizzato più velocemente.",
    "weather.alerts.uv_high.title": "UV molto alti",
    "weather.alerts.uv_high.when": "Questa settimana",
    "weather.alerts.wind_strong.action": "Controlla lo skimmer e il cestello della pompa. Pulisci la linea di galleggiamento.",
    "weather.alerts.wind_strong.message": "{wind} km/h. Detriti, foglie, polvere nella piscina.",
    "weather.alerts.wind_strong.title": "Vento forte previsto",
    "weather.alerts.wind_strong.when": "Dopo il vento",
    "weather.filtration.reason": "Regola: metà della temperatura dell'acqua ({temp} °C) in ore di filtrazione.",
    "weather.filtration.scheduleDiurnal": "Filtrazione diurna consigliata.",
    "weather.filtration.scheduleNocturnal": "Preferisci la filtrazione notturna (meno evaporazione, migliore efficacia del cloro).",
    "weather.precipShort": "Precip.",
    "weather.severity.info": "Info",
    "weather.summary.calm": "Meteo mite a {location}. Nessun avviso particolare. Filtra {hours}h/giorno.",
    "weather.summary.withAlerts": "{count} avviso/i meteo: {titles}. Segui le azioni consigliate.",
    "weather.testReason.after_rain": "Test pH + cloro consigliato dopo la pioggia.",
    "weather.testReason.before_storm": "Test consigliato prima del temporale previsto domani.",
    "weather.testReason.during_heatwave": "Test giornaliero consigliato durante l'ondata di calore.",
    "weather.testReason.routine": "Ultimo test {days} giorni fa. Test di routine consigliato.",
    "weather.testReason.urgent": "Ultimo test {days} giorni fa: test urgente consigliato.",
    "weather.uvShort": "UV",
}


def main():
    worksheet = json.loads(WORKSHEET.read_text(encoding='utf-8'))
    ws_keys = list(worksheet.keys())

    # Build ordered output matching worksheet key order
    output = {}
    missing = []
    for k in ws_keys:
        if k in TRANSLATIONS:
            output[k] = TRANSLATIONS[k]
        else:
            missing.append(k)

    if missing:
        print(f'ERROR: {len(missing)} keys missing translations:')
        for k in missing[:20]:
            print(f'  {k}')
        raise SystemExit(1)

    extra = [k for k in TRANSLATIONS if k not in worksheet]
    if extra:
        print(f'WARNING: {len(extra)} extra translations not in worksheet:')
        for k in extra[:20]:
            print(f'  {k}')

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        json.dumps(output, ensure_ascii=False, indent=2) + '\n',
        encoding='utf-8'
    )
    print(f'Wrote {len(output)} keys to {OUTPUT}')


if __name__ == '__main__':
    main()
