#!/usr/bin/env python3
"""Translate all EN-identical values in de.json to German."""
import json
import sys

# Translation dictionary: EN value -> DE value
# Brand names kept as-is: AQWELIA, Ripple, Lagoon, Atlas, Jacuzzi, Pentair, etc.
# Technical terms kept: pH, TAC, CYA, LSI, TA, CH, UV
# Currency: € kept
# Placeholders: {city}, {percent}, {n}, {count}, etc. preserved

TRANSLATIONS = {
    # === Short values (1-10 chars) ===
    "…": "…",
    "AI": "KI",
    "OK": "OK",
    "Ok": "OK",
    "TA": "TA",
    "UV": "UV",
    "pH": "pH",
    "Add": "Hinzufügen",
    "All": "Alle",
    "CYA": "CYA",
    "Eco": "Eco",
    "FAQ": "FAQ",
    "Log": "Verlauf",
    "Low": "Niedrig",
    "Now": "Jetzt",
    "Pro": "Pro",
    "Spa": "Spa",
    "TA+": "TA+",
    "min": "Min.",
    "pH+": "pH+",
    "pH-": "pH-",
    "Back": "Zurück",
    "Blog": "Blog",
    "Cell": "Zelle",
    "Cold": "Kalt",
    "Done": "Erledigt",
    "Free": "Kostenlos",
    "High": "Hoch",
    "Info": "Info",
    "More": "Mehr",
    "Name": "Name",
    "Oval": "Oval",
    "Plan": "Plan",
    "Pool": "Pool",
    "Pump": "Pumpe",
    "Salt": "Salz",
    "Sand": "Sand",
    "Save": "Speichern",
    "Step": "Schritt",
    "Text": "Text",
    "Tip:": "Tipp:",
    "Type": "Typ",
    "Unit": "Einheit",
    "User": "Benutzer",
    "When": "Wann",
    "Wind": "Wind",
    "user": "Benutzer",
    " and ": " und ",
    "Alert": "Alarm",
    "Brand": "Marke",
    "Clear": "Leeren",
    "Close": "Schließen",
    "Cover": "Abdeckung",
    "Email": "E-Mail",
    "Error": "Fehler",
    "Fresh": "Frisch",
    "Glass": "Glas",
    "Ideal": "Ideal",
    "Issue": "Problem",
    "Later": "Später",
    "Liner": "Folie",
    "Model": "Modell",
    "Next:": "Weiter:",
    "Notes": "Notizen",
    "Other": "Sonstige",
    "Photo": "Foto",
    "Retry": "Wiederholen",
    "Robot": "Roboter",
    "Temp.": "Temp.",
    "Terms": "AGB",
    "Tests": "Tests",
    "Tiled": "Fliesen",
    "Today": "Heute",
    "Usage": "Nutzung",
    "Watch": "Beobachten",
    "Water": "Wasser",
    "h/day": "h/Tag",
    "never": "nie",
    "seats": "Sitze",
    "{n} d": "{n} T",
    "(aqua)": "(aqua)",
    "(well)": "(Quelle)",
    "Action": "Aktion",
    "Cancel": "Abbrechen",
    "Delete": "Löschen",
    "Device": "Gerät",
    "Do now": "Jetzt tun",
    "Expert": "Experte",
    "Export": "Exportieren",
    "Failed": "Fehlgeschlagen",
    "Filter": "Filter",
    "Filtr.": "Filtr.",
    "Guides": "Anleitungen",
    "Ideal:": "Ideal:",
    "Manual": "Manuell",
    "My spa": "Mein Spa",
    "Source": "Quelle",
    "Status": "Status",
    "System": "System",
    "Urgent": "Dringend",
    "autumn": "Herbst",
    "metric": "metrisch",
    "spring": "Frühling",
    "summer": "Sommer",
    "winter": "Winter",
    "5+/week": "5+/Woche",
    "AQWELIA": "AQWELIA",
    "Bromine": "Brom",
    "Country": "Land",
    "E.g.: 5": "z. B.: 5",
    "Extreme": "Extrem",
    "Feature": "Funktion",
    "Filter:": "Filter:",
    "Free Cl": "Freies Cl",
    "History": "Verlauf",
    "Landing": "Startseite",
    "Logbook": "Protokoll",
    "My pool": "Mein Pool",
    "Offline": "Offline",
    "PREMIUM": "PREMIUM",
    "Precip.": "Niederschl.",
    "Premium": "Premium",
    "Preview": "Vorschau",
    "Problem": "Problem",
    "Re-test": "Nachmessung",
    "Refresh": "Aktualisieren",
    "Regular": "Regelmäßig",
    "Restart": "Neustart",
    "Season:": "Saison:",
    "See log": "Verlauf ansehen",
    "Skimmer": "Skimmer",
    "Source:": "Quelle:",
    "Summary": "Zusammenfassung",
    "Support": "Support",
    "Title *": "Titel *",
    "Trigger": "Auslöser",
    "Warning": "Warnung",
    "Weather": "Wetter",
    "gallons": "Gallonen",
    "in {n}d": "in {n} T",
    "in {n}h": "in {n}h",
    "tablets": "Tabletten",
    "12 — FAQ": "12 — FAQ",
    "All good": "Alles in Ordnung",
    "Balanced": "Ausgeglichen",
    "Beginner": "Anfänger",
    "Category": "Kategorie",
    "Chlorine": "Chlor",
    "Critical": "Kritisch",
    "Imperial": "Imperial",
    "Imported": "Importiert",
    "John Doe": "Max Mustermann",
    "Loading…": "Wird geladen…",
    "Moderate": "Moderat",
    "Never do": "Niemals tun",
    "New test": "Neue Messung",
    "Opening…": "Wird geöffnet…",
    "Password": "Passwort",
    "Pleasant": "Angenehm",
    "Priority": "Priorität",
    "Pro tip:": "Profi-Tipp:",
    "Products": "Produkte",
    "Quantity": "Menge",
    "Schedule": "Zeitplan",
    "Settings": "Einstellungen",
    "Sign out": "Abmelden",
    "Spa name": "Spa-Name",
    "Too cold": "Zu kalt",
    "Warning:": "Warnung:",
    "imperial": "imperial",
    "optional": "optional",
    "pH probe": "pH-Sonde",
    "pH trend": "pH-Verlauf",
    "{n}d ago": "vor {n} T",
    "••••••••": "••••••••",
    "1-2x/week": "1–2×/Woche",
    "3-4x/week": "3–4×/Woche",
    "Analytics": "Analyse",
    "Cartridge": "Kartusche",
    "Deleting…": "Wird gelöscht…",
    "Do not do": "Nicht tun",
    "Equipment": "Geräte",
    "Heat pump": "Wärmepumpe",
    "How long?": "Wie lange?",
    "Intensive": "Intensiv",
    "Inventory": "Bestand",
    "Locate me": "Mich lokalisieren",
    "Locating…": "Lokalisierung…",
    "Price (€)": "Preis (€)",
    "Reminders": "Erinnerungen",
    "See plans": "Pläne ansehen",
    "Specific.": "Spezifisch.",
    "Swim {n}h": "Baden {n}h",
    "This week": "Diese Woche",
    "Treatment": "Behandlung",
    "Unlimited": "Unbegrenzt",
    "User menu": "Benutzermenü",
    "Vigilance": "Wachsamkeit",
    "Your plan": "Ihr Plan",
    "Algae risk": "Algenrisiko",
    "Anti-algae": "Algentötung",
    "Call a pro": "Profi rufen",
    "Diagnostic": "Diagnose",
    "Emergency?": "Notfall?",
    "Exporting…": "Wird exportiert…",
    "Filtration": "Filtration",
    "Flocculant": "Flockungsmittel",
    "Health log": "Pflegeprotokoll",
    "In 1 click": "In 1 Klick",
    "Last test:": "Letzte Messung:",
    "Maintained": "Gewartet",
    "Occasional": "Gelegentlich",
    "PDF export": "PDF-Export",
    "PDF report": "PDF-Bericht",
    "Regenerate": "Neu generieren",
    "Restoring…": "Wird wiederhergestellt…",
    "Salt (g/L)": "Salz (g/L)",
    "Stabilizer": "Stabilisator",
    "To analyze": "Zu analysieren",
    "Water test": "Wasseranalyse",
    "Welcome to": "Willkommen bei",
    "Well done!": "Gut gemacht!",
    "in {days}d": "in {days} T",
    "Action plan": "Aktionsplan",
    "Coming soon": "Bald verfügbar",
    "E.g.: 19.90": "z. B.: 19,90",
    "Environment": "Umgebung",
    "Filter type": "Filtertyp",
    "Filtr. {n}h": "Filtr. {n}h",
    "Green water": "Grünes Wasser",
    "Maintained:": "Gewartet:",
    "Maintenance": "Wartung",
    "Measurement": "Messung",
    "Multi-pools": "Mehrere Pools",
    "Photo strip": "Teststreifen",
    "Priority #1": "Priorität #1",
    "Save failed": "Speichern fehlgeschlagen",
    "Spa volume?": "Spa-Volumen?",
    "Swim safety": "Badesicherheit",
    "Unstable pH": "Instabiler pH",
    "Winterizing": "Überwinterung",
    "cached data": "Zwischengespeicherte Daten",
    "in {hours}h": "in {hours}h",
    "pH required": "pH erforderlich",
    "♨️ Spa mode": "♨️ Spa-Modus",
    "AI Assistant": "KI-Assistent",
    "Back to Free": "Zurück zu Kostenlos",
    "Cloudy water": "Trübes Wasser",
    "Current plan": "Aktueller Plan",
    "E.g.: 30 (%)": "z. B.: 30 (%)",
    "E.g.: VS-100": "z. B.: VS-100",
    "Electrolyzer": "Elektrolyseur",
    "Enter a test": "Messung eingeben",
    "Ideal ranges": "Idealbereiche",
    "Installed on": "Installiert am",
    "Intermediate": "Fortgeschritten",
    "Invalid file": "Ungültige Datei",
    "Live weather": "Live-Wetter",
    "Manual entry": "Manuelle Eingabe",
    "Measurements": "Messwerte",
    "Mild weather": "Mildes Wetter",
    "More modules": "Weitere Module",
    "Next re-test": "Nächste Nachmessung",
    "No reminders": "Keine Erinnerungen",
    "Pool copilot": "Pool-Copilot",
    "Product name": "Produktname",
    "Re-test {n}h": "Nachmessung {n}h",
    "Redirecting…": "Weiterleitung…",
    "Spa drainage": "Spa-Ablass",
    "Spa max temp": "Spa Max-Temp.",
    "Swim comfort": "Badekomfort",
    "Water alerts": "Wasser-Alarme",
    "Weather risk": "Wetter-Risiko",
    "pH evolution": "pH-Entwicklung",
    "v2.0 Copilot": "v2.0 Copilot",
    "AQWELIA Admin": "AQWELIA Admin",
    "Action queued": "Aktion eingereiht",
    "Active oxygen": "Aktivsauerstoff",
    "After a storm": "Nach einem Sturm",
    "Choose {name}": "{name} wählen",
    "Concentration": "Konzentration",
    "Context used:": "Verwendeter Kontext:",
    "Delete failed": "Löschen fehlgeschlagen",
    "E.g.: Buy pH-": "z. B.: pH- kaufen",
    "E.g.: Pentair": "z. B.: Pentair",
    "Export failed": "Export fehlgeschlagen",
    "In {location}": "In {location}",
    "Maximum 6 MB.": "Maximal 6 MB.",
    "Name required": "Name erforderlich",
    "Next reminder": "Nächste Erinnerung",
    "Pool max temp": "Pool Max-Temp.",
    "Premium guide": "Premium-Anleitung",
    "Product added": "Produkt hinzugefügt",
    "Product stock": "Produktbestand",
    "Rain tomorrow": "Morgen Regen",
    "See full plan": "Vollständigen Plan ansehen",
    "See reminders": "Erinnerungen ansehen",
    "Slow chlorine": "Langsames Chlor",
    "Smart weather": "Intelligentes Wetter",
    "Stinging eyes": "Brennende Augen",
    "Type required": "Typ erforderlich",
    "Unknown error": "Unbekannter Fehler",
    "{count} today": "{count} heute",
    "3-day forecast": "3-Tage-Vorhersage",
    "Algae on walls": "Algen an den Wänden",
    "Cancel anytime": "Jederzeit kündbar",
    "Estimated cost": "Geschätzte Kosten",
    "Export as JSON": "Als JSON exportieren",
    "Filter cleaner": "Filterreiniger",
    "Invalid volume": "Ungültiges Volumen",
    "Made in France": "Hergestellt in Frankreich",
    "Not configured": "Nicht konfiguriert",
    "Opening guide…": "Anleitung wird geöffnet…",
    "Premium guides": "Premium-Anleitungen",
    "Privacy Policy": "Datenschutzerklärung",
    "Related guides": "Verwandte Anleitungen",
    "Reminder added": "Erinnerung hinzugefügt",
    "Restore failed": "Wiederherstellung fehlgeschlagen",
    "Robot cleaning": "Roboter-Reinigung",
    "Shock chlorine": "Stoßchlor",
    "Stock updated.": "Bestand aktualisiert.",
    "Title required": "Titel erforderlich",
    "Unable to save": "Speichern nicht möglich",
    "{count} urgent": "{count} dringend",
    "{n} day(s) ago": "vor {n} Tag(en)",
    "♨️ Spa details": "♨️ Spa-Details",
    "AQWELIA Premium": "AQWELIA Premium",
    "Account deleted": "Konto gelöscht",
    "Action recorded": "Aktion erfasst",
    "Assistance mode": "Assistenzmodus",
    "Before vacation": "Vor dem Urlaub",
    "Choose duration": "Laufzeit wählen",
    "Climate & usage": "Klima & Nutzung",
    "Could not clear": "Leeren nicht möglich",
    "Deletion failed": "Löschen fehlgeschlagen",
    "Deletion queued": "Löschen eingereiht",
    "Equipment added": "Gerät hinzugefügt",
    "Estimated water": "Geschätztes Wasser",
    "Filter cleaning": "Filterreinigung",
    "Go to assistant": "Zum Assistenten",
    "History cleared": "Verlauf geleert",
    "Image too large": "Bild zu groß",
    "Latest analysis": "Letzte Analyse",
    "Link (optional)": "Link (optional)",
    "Location denied": "Standort verweigert",
    "Main navigation": "Hauptnavigation",
    "Min. filtration": "Min. Filtration",
    "Name (optional)": "Name (optional)",
    "Not enough data": "Nicht genügend Daten",
    "Note (optional)": "Notiz (optional)",
    "Overall quality": "Gesamtqualität",
    "Polyester shell": "Polyester-Schale",
    "Product deleted": "Produkt gelöscht",
    "See action plan": "Aktionsplan ansehen",
    "Smart reminders": "Intelligente Erinnerungen",
    "Step {step} / 4": "Schritt {step} / 4",
    "TA (alkalinity)": "TA (Alkalinität)",
    "Units: {system}": "Einheiten: {system}",
    "Vigilance level": "Wachsamkeitsstufe",
    "CYA (stabilizer)": "CYA (Stabilisator)",
    "Chlorine at zero": "Chlor bei null",
    "Choose an image.": "Wählen Sie ein Bild.",
    "Could not delete": "Löschen nicht möglich",
    "Could not update": "Aktualisierung nicht möglich",
    "E.g.: liquid pH-": "z. B.: flüssiges pH-",
    "I have a problem": "Ich habe ein Problem",
    "Last maintenance": "Letzte Wartung",
    "Last water test:": "Letzte Wasseranalyse:",
    "Next maintenance": "Nächste Wartung",
    "Painted concrete": "Beton, gestrichen",
    "Plan regenerated": "Plan neu generiert",
    "Pool winterizing": "Pool-Überwinterung",
    "Profile created!": "Profil erstellt!",
    "Reminder deleted": "Erinnerung gelöscht",
    "Reminder snoozed": "Erinnerung aufgeschoben",
    "Restart (spring)": "Neustart (Frühling)",
    "Skimmer / basket": "Skimmer / Korb",
    "Swimming allowed": "Baden erlaubt",
    "Temperature (°C)": "Temperatur (°C)",
    "Treatment method": "Behandlungsmethode",
    "Your pool expert": "Ihr Pool-Experte",
    "AQWELIA Assistant": "AQWELIA-Assistent",
    "AQWELIA resources": "AQWELIA-Ressourcen",
    "Account & privacy": "Konto & Datenschutz",
    "An error occurred": "Ein Fehler ist aufgetreten",
    "Can I swim today?": "Kann ich heute baden?",
    "Clear water index": "Kristallwasser-Index",
    "Detail (optional)": "Detail (optional)",
    "Electrolyzer cell": "Elektrolysezelle",
    "Equipment deleted": "Gerät gelöscht",
    "Export downloaded": "Export heruntergeladen",
    "Filtration & pump": "Filtration & Pumpe",
    "Free, to discover": "Kostenlos, zum Entdecken",
    "Location detected": "Standort erkannt",
    "Made in France 🇫🇷": "Hergestellt in Frankreich 🇫🇷",
    "Measurement saved": "Messung gespeichert",
    "New conversation.": "Neue Unterhaltung.",
    "No purchase found": "Kein Kauf gefunden",
    "No urgent action.": "Keine dringende Aktion.",
    "Now in {location}": "Jetzt in {location}",
    "Permission denied": "Berechtigung verweigert",
    "Photo diagnostics": "Foto-Diagnosen",
    "Product inventory": "Produktbestand",
    "Recommended photo": "Foto empfohlen",
    "Salt electrolysis": "Salzelektrolyse",
    "Salt electrolyzer": "Salzelektrolyseur",
    "Too much chlorine": "Zu viel Chlor",
    "Upgrade to {plan}": "Upgrade auf {plan}",
    "Visual diagnostic": "Visuelle Diagnose",
    "e.g.: Garden pool": "z. B.: Gartenpool",
    "e.g.: Terrace spa": "z. B.: Terrassen-Spa",
    "Action recommended": "Aktion empfohlen",
    "Back from vacation": "Zurück aus dem Urlaub",
    "Bromine activated.": "Brom aktiviert.",
    "Cannot open portal": "Portal kann nicht geöffnet werden",
    "Could not restore.": "Wiederherstellung nicht möglich.",
    "Current conditions": "Aktuelle Bedingungen",
    "Diagnostic deleted": "Diagnose gelöscht",
    "Diatomaceous earth": "Kieselgur",
    "Electrolyzer error": "Elektrolyseur-Fehler",
    "Interface language": "Oberflächensprache",
    "Measured on {date}": "Gemessen am {date}",
    "Purchase cancelled": "Kauf abgebrochen",
    "Purchases restored": "Käufe wiederhergestellt",
    "Re-test after 24h.": "Nachmessung nach 24 Std.",
    "Reminder completed": "Erinnerung erledigt",
    "Resources & guides": "Ressourcen & Anleitungen",
    "Setup in 2 minutes": "Einrichtung in 2 Minuten",
    "Swimming forbidden": "Baden verboten",
    "Total cost: {cost}": "Gesamtkosten: {cost}",
    "Water measurements": "Wasser-Messwerte",
    "m³ (liters ÷ 1000)": "m³ (Liter ÷ 1000)",
    "Active plan: {plan}": "Aktiver Plan: {plan}",
    "Communication error": "Kommunikationsfehler",
    "Detailed comparison": "Detaillierter Vergleich",
    "Disinfection method": "Desinfektionsmethode",
    "Due date (optional)": "Fälligkeitsdatum (optional)",
    "Enter a measurement": "Messung eingeben",
    "Equipment ({count})": "Geräte ({count})",
    "Error during signup": "Fehler bei der Registrierung",
    "Free plan activated": "Kostenlos-Plan aktiviert",
    "Measurement deleted": "Messung gelöscht",
    "No urgent reminders": "Keine dringenden Erinnerungen",
    "Photo scans / month": "Foto-Scans / Monat",
    "Plan {plan} active.": "Plan {plan} aktiv.",
    "Pool weather alerts": "Pool-Wetter-Alarme",
    "Re-test in {hours}h": "Nachmessung in {hours}h",
    "Recent measurements": "Letzte Messungen",
    "Recommended dosages": "Empfohlene Dosierungen",
    "Recommended for you": "Für Sie empfohlen",
    "Type and dimensions": "Typ und Abmessungen",
    "Weather unavailable": "Wetter nicht verfügbar",
    "Your pool reminders": "Ihre Pool-Erinnerungen",
    "Add my first product": "Mein erstes Produkt hinzufügen",
    "Back to landing page": "Zurück zur Startseite",
    "Backwash the filter.": "Filter zurückspülen.",
    "Check pH and adjust.": "pH prüfen und anpassen.",
    "Could not regenerate": "Neugenerierung nicht möglich",
    "Currency: {currency}": "Währung: {currency}",
    "Current plan: {name}": "Aktueller Plan: {name}",
    "Encrypted connection": "Verschlüsselte Verbindung",
    "Equipment & products": "Geräte & Produkte",
    "Filter high pressure": "Hoher Filterdruck",
    "Filter wash ({type})": "Filterrückspülung ({type})",
    "High filter pressure": "Hoher Filterdruck",
    "JSON file retrieved.": "JSON-Datei abgerufen.",
    "Marked as maintained": "Als gewartet markiert",
    "No pending reminders": "Keine offenen Erinnerungen",
    "Premium Spa Support.": "Premium-Spa-Support.",
    "Pump prefilter check": "Pumpenvorfilter prüfen",
    "Restore my purchases": "Meine Käufe wiederherstellen",
    "Save & generate plan": "Speichern & Plan erstellen",
    "Swimming discouraged": "Baden nicht empfohlen",
    "You'll see it later.": "Sie sehen es später.",
    "pH probe calibration": "pH-Sonden-Kalibrierung",
    "Add a manual reminder": "Manuelle Erinnerung hinzufügen",
    "Adjust pH to 7.2-7.4.": "pH auf 7,2–7,4 einstellen.",
    "Connect to subscribe.": "Verbinden Sie sich zum Abonnieren.",
    "E.g.: Lyon, Biarritz…": "z. B.: Lyon, Biarritz…",
    "Enter my measurements": "Meine Messwerte eingeben",
    "Every {months} months": "Alle {months} Monate",
    "Generated action plan": "Generierter Aktionsplan",
    "Maintenance due soon.": "Wartung bald fällig.",
    "Maintenance reminders": "Wartungs-Erinnerungen",
    "Measurement reminders": "Mess-Erinnerungen",
    "Measurements to enter": "Einzugebende Messwerte",
    "No photo diagnostics.": "Keine Foto-Diagnosen.",
    "Pool profile injected": "Pool-Profil übernommen",
    "Product name required": "Produktname erforderlich",
    "Re-test after 24-48h.": "Nachmessung nach 24–48 Std.",
    "Shock chlorine treat.": "Stoßchlor-Behandlung.",
    "Signed in as {email}.": "Angemeldet als {email}.",
    "Step-by-step protocol": "Schritt-für-Schritt-Protokoll",
    "Strong chlorine smell": "Starker Chlorgestank",
    "To do — in this order": "Erledigen — in dieser Reihenfolge",
    "Weather & pool advice": "Wetter- & Pool-Beratung",
    "Welcome to AQWELIA. 🌊": "Willkommen bei AQWELIA. 🌊",
    "Add my first equipment": "Mein erstes Gerät hinzufügen",
    "Give your pool a name.": "Geben Sie Ihrem Pool einen Namen.",
    "Go to photo diagnostic": "Zur Foto-Diagnose",
    "Hide advanced settings": "Erweiterte Einstellungen ausblenden",
    "Manage my subscription": "Mein Abonnement verwalten",
    "No measurements saved.": "Keine Messungen gespeichert.",
    "Optimal daily duration": "Optimale Tagesdauer",
    "Plan {plan} activated.": "Plan {plan} aktiviert.",
    "Profile not configured": "Profil nicht konfiguriert",
    "Recommended filtration": "Empfohlene Filtration",
    "Search a guide, a tag…": "Anleitung oder Tag suchen…",
    "Unlock smart reminders": "Intelligente Erinnerungen freischalten",
    "Water test recommended": "Wasseranalyse empfohlen",
    "Yes, delete my account": "Ja, mein Konto löschen",
    "You can edit it later.": "Sie können es später bearbeiten.",
    "e.g.: Marseille, Lyon…": "z. B.: Marseille, Lyon…",
    "Default profile created": "Standardprofil erstellt",
    "Instructions (optional)": "Anweisungen (optional)",
    "Locate me automatically": "Mich automatisch lokalisieren",
    "No purchases to restore": "Keine Käufe wiederherzustellen",
    "Pro mode (advanced LSI)": "Pro-Modus (erweitertes LSI)",
    "Subscription activated!": "Abonnement aktiviert!",
    "Unstable pH — adjust TA": "Instabiler pH — TA anpassen",
    "Your city (for weather)": "Ihre Stadt (fürs Wetter)",
    "{hours}h filtration/day": "{hours}h Filtration/Tag",
    "Active oxygen activated.": "Aktivsauerstoff aktiviert.",
    "Cover with winter cover.": "Mit Winterabdeckung abdecken.",
    "Enter a positive volume.": "Geben Sie ein positives Volumen ein.",
    "No action plan available": "Kein Aktionsplan verfügbar",
    "Not enough measurements.": "Nicht genügend Messungen.",
    "Swimming to be confirmed": "Baden noch zu bestätigen",
    "You're on the Free plan.": "Sie sind im Kostenlos-Plan.",
    "live weather via wttr.in": "Live-Wetter über wttr.in",
    "Add anti-algae if needed.": "Bei Bedarf Algentötung hinzufügen.",
    "Advanced weather + alerts": "Erweitertes Wetter + Alarme",
    "Allow camera in settings.": "Kamera in den Einstellungen erlauben.",
    "Check pH before shocking.": "pH vor Stoßchlorung prüfen.",
    "Enter a water measurement": "Wasser-Messwert eingeben",
    "Enter your city manually.": "Geben Sie Ihre Stadt manuell ein.",
    "Geolocation not supported": "Geolokalisierung nicht unterstützt",
    "Last maintenance updated.": "Letzte Wartung aktualisiert.",
    "No water measurements yet": "Noch keine Wasser-Messwerte",
    "Saving & generating plan…": "Wird gespeichert & Plan erstellt…",
    "Shock chlorine treatment.": "Stoßchlor-Behandlung.",
    "Shock treat + anti-algae.": "Stoßbehandlung + Algentötung.",
    "The expert is thinking...": "Der Experte denkt nach...",
    "Chlorine (not recommended)": "Chlor (nicht empfohlen)",
    "Continuous filtration 48h.": "Durchgehende Filtration 48 Std.",
    "Could not apply this city.": "Diese Stadt konnte nicht übernommen werden.",
    "Could not open management.": "Verwaltung konnte nicht geöffnet werden.",
    "Electrolysis cell cleaning": "Reinigung der Elektrolysezelle",
    "Frequently asked questions": "Häufig gestellte Fragen",
    "Hi! I'm your pool expert 👋": "Hallo! Ich bin Ihr Pool-Experte 👋",
    "Latest water test injected": "Letzte Wasseranalyse übernommen",
    "Marketplace: {marketplace}": "Marktplatz: {marketplace}",
    "No weather alerts for now.": "Aktuell keine Wetter-Alarme.",
    "Strong smell = chloramines": "Starker Geruch = Chloramine",
    "Weather unavailable, retry": "Wetter nicht verfügbar, erneut versuchen",
    "What is the refund policy?": "Wie lautet die Rückerstattungsrichtlinie?",
    "After a storm — restoration": "Nach einem Sturm — Wiederherstellung",
    "Can I change plans anytime?": "Kann ich jederzeit den Plan wechseln?",
    "Complementary disinfection.": "Ergänzende Desinfektion.",
    "How do I winterize my pool?": "Wie überwintere ich meinen Pool?",
    "Incorrect email or password": "Falsche E-Mail oder falsches Passwort",
    "JPG / PNG / WEBP — max 6 MB": "JPG / PNG / WEBP — max. 6 MB",
    "Product inventory ({count})": "Produktbestand ({count})",
    "You cancelled the purchase.": "Sie haben den Kauf abgebrochen.",
    "{count} reminder(s) pending": "{count} offene Erinnerung(en)",
    "Action plan generated below.": "Aktionsplan unten generiert.",
    "Back from vacation — restart": "Zurück aus dem Urlaub — Neustart",
    "Chlorine-free, eco-friendly.": "Chlorfrei, umweltfreundlich.",
    "Diagnostic saved in logbook.": "Diagnose im Protokoll gespeichert.",
    "Enter at least the pH value.": "Geben Sie mindestens den pH-Wert ein.",
    "If chloramines: shock treat.": "Bei Chloraminen: Stoßbehandlung.",
    "Is an annual plan available?": "Gibt es einen Jahresplan?",
    "No active subscription found": "Kein aktives Abonnement gefunden",
    "Photograph the filter gauge.": "Fotografieren Sie das Filter-Manometer.",
    "Remove winter floats/gizmos.": "Winter-Bojen/Eis-Stopfen entfernen.",
    "Salt electrolysis activated.": "Salzelektrolyse aktiviert.",
    "{count} measurement(s) total": "{count} Messung(en) gesamt",
    "Adjust pH first (target 7.2).": "Zuerst pH einstellen (Ziel 7,2).",
    "Continuous filtration 12-24h.": "Durchgehende Filtration 12–24 Std.",
    "Continuous filtration 24-48h.": "Durchgehende Filtration 24–48 Std.",
    "Ideal for hot water and spas.": "Ideal für heißes Wasser und Spas.",
    "No active subscription found.": "Kein aktives Abonnement gefunden.",
    "No guide matches your search.": "Keine Anleitung entspricht Ihrer Suche.",
    "Unable to load the dashboard.": "Dashboard konnte nicht geladen werden.",
    "Will sync when you're online.": "Wird synchronisiert, wenn Sie online sind.",
    "{count} recent measurement(s)": "{count} aktuelle Messung(en)",
    "AI diagnostic available below.": "KI-Diagnose unten verfügbar.",
    "E.g.: replace cell in 6 months": "z. B.: Zelle in 6 Monaten ersetzen",
    "Measure pH, chlorine, TA, CYA.": "pH, Chlor, TA, CYA messen.",
    "Photograph the affected walls.": "Fotografieren Sie die betroffenen Wände.",
    "Skim, scoop, vacuum the floor.": "Abschöpfen, herausfischen, Boden saugen.",
    "e.g.: Pentair Superflo 0.75 HP": "z. B.: Pentair Superflo 0,75 HP",
    "pH {value} slightly off ideal.": "pH {value} leicht abweichend vom Ideal.",
    "Account created, please sign in": "Konto erstellt, bitte anmelden",
    "Check supply voltage (breaker).": "Versorgungsspannung prüfen (Sicherung).",
    "Chlorine at zero — disinfection": "Chlor bei null — Desinfektion",
    "Enter your city manually below.": "Geben Sie unten Ihre Stadt manuell ein.",
    "No swimming for 8h after shock.": "8 Std. nach Stoßchlorung nicht baden.",
    "Pump (brand / model — optional)": "Pumpe (Marke / Modell — optional)",
    "Skim and remove surface debris.": "Oberflächlichen Schmutz abschöpfen.",
    "The plan has been recalculated.": "Der Plan wurde neu berechnet.",
    "Applicable standards ({country})": "Anwendbare Normen ({country})",
    "By continuing, you agree to our ": "Mit der Fortsetzung stimmen Sie unseren ",
    "E.g.: 1 tablet / basket per week": "z. B.: 1 Tablette / Korb pro Woche",
    "Free plan: basic reminders only.": "Kostenlos-Plan: nur einfache Erinnerungen.",
    "Green water, storm, strong odor…": "Grünes Wasser, Sturm, starker Geruch…",
    "Irritations — pH or chloramines?": "Reizungen — pH oder Chloramine?",
    "Low stock — consider reordering.": "Niedriger Bestand — Nachbestellen erwägen.",
    "Permanently delete your account?": "Konto dauerhaft löschen?",
    "Re-test after 12-24h filtration.": "Nachmessung nach 12–24 Std. Filtration.",
    "Run filtration continuously 24h.": "Filtration durchgehend 24 Std. laufen lassen.",
    "Unable to create default profile": "Standardprofil konnte nicht erstellt werden",
    "Vacuum deposits after treatment.": "Ablagerungen nach der Behandlung absaugen.",
    "pH {value} outside safety range.": "pH {value} außerhalb des Sicherheitsbereichs.",
    "Brush walls and floor vigorously.": "Wände und Boden kräftig bürsten.",
    "Check that valves are fully open.": "Prüfen, dass alle Ventile vollständig offen sind.",
    "Cloudy water — clarity diagnostic": "Trübes Wasser — Klarheits-Diagnose",
    "E.g.: The bottle is almost empty…": "z. B.: Die Flasche ist fast leer…",
    "Green water — anti-algae protocol": "Grünes Wasser — Anti-Algen-Protokoll",
    "If pH out of range: adjust first.": "Wenn pH außerhalb des Bereichs: zuerst anpassen.",
    "Immediate actions — in this order": "Sofortmaßnahmen — in dieser Reihenfolge",
    "Shock treat if chlorine < 1 mg/L.": "Stoßbehandlung bei Chlor < 1 mg/L.",
    "Check pump and filter (full wash).": "Pumpe und Filter prüfen (volle Spülung).",
    "DO NOT add chlorine or stabilizer.": "KEIN Chlor oder Stabilisator hinzufügen.",
    "Do a final floor/surface cleaning.": "Abschließende Boden-/Oberflächenreinigung durchführen.",
    "Everything you get with each plan.": "Alles, was Sie mit jedem Plan erhalten.",
    "Over-chlorination — lower chlorine": "Überchlorung — Chlor senken",
    "Will sync when you're back online.": "Wird synchronisiert, wenn Sie wieder online sind.",
    "Check water flow (primary circuit).": "Wasserdurchfluss prüfen (Hauptkreislauf).",
    "Import a photo and click \"Analyze\".": "Foto importieren und auf „Analysieren\" klicken.",
    "Most common, simple and economical.": "Am häufigsten, einfach und wirtschaftlich.",
    "Rinse 30 seconds to reset the sand.": "30 Sekunden spülen, um den Sand zurückzusetzen.",
    "Run filtration continuously 24-48h.": "Filtration durchgehend 24–48 Std. laufen lassen.",
    "Your city will be used for weather.": "Ihre Stadt wird für das Wetter verwendet.",
    "Check water level, top up if needed.": "Wasserstand prüfen, bei Bedarf nachfüllen.",
    "Empty bags/filters after each cycle.": "Säcke/Filter nach jedem Zyklus leeren.",
    "Measure pH, chlorine, TA, CYA, salt.": "pH, Chlor, TA, CYA, Salz messen.",
    "My water is green, what should I do?": "Mein Wasser ist grün, was soll ich tun?",
    "No swimming until chlorine < 4 mg/L.": "Nicht baden, bis Chlor < 4 mg/L.",
    "Not enough measurements for a chart.": "Nicht genügend Messungen für ein Diagramm.",
    "Phosphates {value} mg/L: algae risk.": "Phosphate {value} mg/L: Algenrisiko.",
    "Photograph the water and pool floor.": "Fotografieren Sie Wasser und Poolboden.",
    "Wait until water < 12-15°C to start.": "Warten, bis Wasser < 12–15 °C, bevor begonnen wird.",
    "Your manual reminder has been saved.": "Ihre manuelle Erinnerung wurde gespeichert.",
    "Adjust pH, then TA, then shock treat.": "pH einstellen, dann TA, dann Stoßbehandlung.",
    "Global score 0–100, higher is better.": "Gesamtwert 0–100, je höher desto besser.",
    "Type your question... (Enter to send)": "Ihre Frage eingeben... (Enter zum Senden)",
    "Check free chlorine (too low = algae).": "Freies Chlor prüfen (zu niedrig = Algen).",
    "Consult the manual for the exact code.": "Im Handbuch den genauen Code nachschlagen.",
    "Empty the prefilter basket every week.": "Den Vorfilterkorb jede Woche leeren.",
    "Measure pH (high pH clouds the water).": "pH messen (hohes pH trübt das Wasser).",
    "Re-measure pH and adjust (target 7.2).": "pH neu messen und anpassen (Ziel 7,2).",
    "Shock treat to break down chloramines.": "Stoßbehandlung, um Chloramine abzubauen.",
    "Soft water, less chlorine maintenance.": "Weiches Wasser, weniger Chlor-Wartung.",
    "Add slow chlorine to maintain residual.": "Langsames Chlor hinzufügen, um Restchlor zu erhalten.",
    "Check CYA (too high = chlorine locked).": "CYA prüfen (zu hoch = Chlor blockiert).",
    "Check pH (high pH accelerates scaling).": "pH prüfen (hohes pH beschleunigt Verkalkung).",
    "Drain pipes, install gizmos and floats.": "Rohre entleeren, Eis-Stopfen und Bojen einsetzen.",
    "Should I do a chlorine shock treatment?": "Sollte ich eine Stoßchlorung durchführen?",
    "Brush walls and floor to dislodge algae.": "Wände und Boden bürsten, um Algen zu lösen.",
    "How much pH- should I add for my volume?": "Wie viel pH- sollte ich für mein Volumen hinzufügen?",
    "Information about the installed version.": "Informationen zur installierten Version.",
    "Measure pH (rain often acidifies water).": "pH messen (Regen säuert oft das Wasser an).",
    "My electrolyzer shows an error, help me.": "Mein Elektrolyseur zeigt einen Fehler, helfen Sie mir.",
    "Note the date of last wash for tracking.": "Datum der letzten Spülung zur Nachverfolgung notieren.",
    "Pool profile — click to manage equipment": "Pool-Profil — klicken, um Geräte zu verwalten",
    "Check filtration (pressure, filter wash).": "Filtration prüfen (Druck, Filter spülen).",
    "No swimming until free chlorine > 1 mg/L.": "Nicht baden, bis freies Chlor > 1 mg/L.",
    "Shock chlorine treat (after pH adjusted).": "Stoßchlor-Behandlung (nach pH-Einstellung).",
    "Your subscription is active until {date}.": "Ihr Abonnement ist aktiv bis {date}.",
    "Check CYA: if < 30, sun destroys chlorine.": "CYA prüfen: bei < 30 zerstört die Sonne das Chlor.",
    "Check and empty the pump prefilter basket.": "Pumpenvorfilterkorb prüfen und leeren.",
    "Could not fetch weather for your location.": "Wetter für Ihren Standort konnte nicht abgerufen werden.",
    "If TA < 80: add TA+ to reach 100-120 mg/L.": "Wenn TA < 80: TA+ hinzufügen, um 100–120 mg/L zu erreichen.",
    "If clogged filter: backwash or flocculant.": "Bei verstopftem Filter: Rückspülen oder Flockungsmittel.",
    "No profile: configure the pool for a plan.": "Kein Profil: Pool konfigurieren, um einen Plan zu erhalten.",
    "Remove the winter cover, clean and dry it.": "Winterabdeckung entfernen, reinigen und trocknen.",
    "Global system + unit-by-unit customization.": "Globales System + individuelle Anpassung pro Einheit.",
    "Measure free chlorine (too high irritates).": "Freies Chlor messen (zu hoch reizt).",
    "Shock chlorine treatment after pH balanced.": "Stoßchlor-Behandlung nach pH-Ausgleich.",
    "Sorry, an error occurred. Please try again.": "Entschuldigung, ein Fehler ist aufgetreten. Bitte erneut versuchen.",
    "Weather updated based on your GPS position.": "Wetter basierend auf Ihrer GPS-Position aktualisiert.",
    "Check pH: if > 7.6, chlorine is ineffective.": "pH prüfen: bei > 7,6 ist Chlor unwirksam.",
    "Country default values ({country}) restored.": "Länder-Standardwerte ({country}) wiederhergestellt.",
    "DO NOT add slow chlorine: it makes it worse.": "KEIN langsames Chlor hinzufügen: es verschlimmert es.",
    "Evaporates quickly in hot water, irritating.": "Verdunstet schnell in heißem Wasser, reizend.",
    "Lower water level below skimmers (10-15 cm).": "Wasserstand unter die Skimmer senken (10–15 cm).",
    "What happens at the end of the subscription?": "Was passiert am Ende des Abonnements?",
    "{count} measurement(s) — ideal range 7.0–7.4": "{count} Messung(en) — Idealbereich 7,0–7,4",
    "A question, a bug, an idea? Our team replies.": "Eine Frage, ein Bug, eine Idee? Unser Team antwortet.",
    "Backwash: 2-3 minutes until water runs clear.": "Rückspülen: 2–3 Minuten, bis das Wasser klar ist.",
    "Measure pH first (pH < 7 or > 7.6 irritates).": "Zuerst pH messen (pH < 7 oder > 7,6 reizt).",
    "No measurements. Enter your first test above.": "Keine Messungen. Geben Sie oben Ihren ersten Test ein.",
    "AQWELIA — Always crystal-clear water. © {year}": "AQWELIA — Immer kristallklares Wasser. © {year}",
    "Allow geolocation or enter your city manually.": "Geolokalisierung erlauben oder Stadt manuell eingeben.",
    "Check free chlorine: often too low (< 1 mg/L).": "Freies Chlor prüfen: oft zu niedrig (< 1 mg/L).",
    "Eco-friendly, chlorine-free. Ideal below 35°C.": "Umweltfreundlich, chlorfrei. Ideal unter 35 °C.",
    "I have alerts on my water, help me prioritize.": "Ich habe Alarme zu meinem Wasser, helfen Sie mir zu priorisieren.",
    "Measure free chlorine (often diluted by rain).": "Freies Chlor messen (oft durch Regen verdünnt).",
    "To verify the effect of the ongoing treatment.": "Um die Wirkung der laufenden Behandlung zu überprüfen.",
    "Weather, guides, reminders and premium offers.": "Wetter, Anleitungen, Erinnerungen und Premium-Angebote.",
    "Backwash every 2-4 weeks depending on pressure.": "Alle 2–4 Wochen Rückspülen, je nach Druck.",
    "E.g.: test after a storm, slightly cloudy water…": "z. B.: Messung nach Sturm, leicht trübes Wasser…",
    "Free chlorine too low: disinfection not ensured.": "Freies Chlor zu niedrig: Desinfektion nicht gewährleistet.",
    "Manage your subscription, data, and preferences.": "Verwalten Sie Ihr Abonnement, Ihre Daten und Einstellungen.",
    "The plan will be regenerated when you're online.": "Der Plan wird neu generiert, wenn Sie online sind.",
    "Wait 24h after TA adjustment before touching pH.": "24 Std. nach TA-Anpassung warten, bevor pH angefasst wird.",
    "Add winterizing product (anti-algae, anti-scale).": "Überwinterungsprodukt hinzufügen (Algentötung, Anti-Kalk).",
    "Calibrate with buffer solutions every 1-2 months.": "Alle 1–2 Monate mit Pufferlösungen kalibrieren.",
    "Check CH (hardness): low CH can make water milky.": "CH (Härte) prüfen: niedriges CH kann das Wasser milchig machen.",
    "For a custom task not covered by smart reminders.": "Für eine benutzerdefinierte Aufgabe, die nicht von intelligenten Erinnerungen abgedeckt ist.",
    "Measure alkalinity (TA): it's what stabilizes pH.": "Alkalinität (TA) messen: sie stabilisiert den pH.",
    "Measure combined chlorine (chloramines irritate).": "Gebundenes Chlor messen (Chloramine reizen).",
    "Photograph the electrolyzer display and the cell.": "Fotografieren Sie das Elektrolyseur-Display und die Zelle.",
    "Photograph the surface to check debris and color.": "Fotografieren Sie die Oberfläche, um Schmutz und Farbe zu prüfen.",
    "Descale the cell in diluted acid every 3-6 months.": "Zelle alle 3–6 Monate in verdünnter Säure entkalken.",
    "How we collect, use, and protect your data (GDPR).": "Wie wir Ihre Daten erheben, nutzen und schützen (DSGVO).",
    "The diagnostic has been removed from your history.": "Die Diagnose wurde aus Ihrem Verlauf entfernt.",
    "Unable to retrieve your position. Enter your city.": "Position konnte nicht abgerufen werden. Bitte Stadt eingeben.",
    "Measure salt: if < 4 g/L, the cell doesn't produce.": "Salz messen: bei < 4 g/L produziert die Zelle nicht.",
    "Recommended for spa. Stable in hot water, odorless.": "Für Spas empfohlen. Stabil in heißem Wasser, geruchlos.",
    "The Terms governing the use of the AQWELIA service.": "Die AGB, die die Nutzung des AQWELIA-Dienstes regeln.",
    "You're up to date. Smart reminders will appear here.": "Sie sind auf dem neuesten Stand. Intelligente Erinnerungen erscheinen hier.",
    "If very high (> 10): partial dilution (renew 20-30%).": "Bei sehr hohem Wert (> 10): teilweise Verdünnung (20–30% erneuern).",
    "Inspect the cell: if scaled, descale in diluted acid.": "Zelle inspizieren: bei Verkalkung in verdünnter Säure entkalken.",
    "Reconnect the pump and set valves to summer position.": "Pumpe wieder anschließen und Ventile auf Sommerstellung setzen.",
    "Target ranges automatically applied to your analyses.": "Zielbereiche, die automatisch auf Ihre Analysen angewendet werden.",
    "Check aeration / waterfall: strong stirring raises pH.": "Belüftung / Wasserfall prüfen: starke Bewegung erhöht den pH.",
    "Choose which reminders and alerts you want to receive.": "Wählen Sie, welche Erinnerungen und Alarme Sie erhalten möchten.",
    "Could not get your position. Retry or enter your city.": "Position konnte nicht abgerufen werden. Erneut versuchen oder Stadt eingeben.",
    "If free chlorine > 4: wait for it to drop, don't swim.": "Wenn freies Chlor > 4: warten, bis es sinkt, nicht baden.",
    "My filter gauge shows high pressure. What should I do?": "Mein Filter-Manometer zeigt hohen Druck. Was soll ich tun?",
    "Automatically generated from your registered equipment.": "Automatisch aus Ihren erfassten Geräten generiert.",
    "Combined chlorine {value} mg/L: irritating chloramines.": "Gebundenes Chlor {value} mg/L: reizende Chloramine.",
    "Concrete recommendations generated from real forecasts.": "Konkrete Empfehlungen aus echten Vorhersagen generiert.",
    "Changing country resets the applied units and standards.": "Länderwechsel setzt die angewendeten Einheiten und Normen zurück.",
    "If pressure stays high: filter media may need replacing.": "Wenn der Druck hoch bleibt: Filtermedium muss möglicherweise ersetzt werden.",
    "Turn off pump (passive) or keep running (active, > 0°C).": "Pumpe ausschalten (passiv) oder weiterlaufen lassen (aktiv, > 0 °C).",
    "Check pH (target 7.0–7.4): if out of range, adjust first.": "pH prüfen (Ziel 7,0–7,4): wenn außerhalb des Bereichs, zuerst anpassen.",
    "This guide is reserved for Premium or higher subscribers.": "Diese Anleitung ist Abonnenten mit Premium oder höher vorbehalten.",
    "AQWELIA will monitor the salt level for your electrolyzer.": "AQWELIA überwacht den Salzgehalt für Ihren Elektrolyseur.",
    "Add equipment to activate automatic maintenance reminders.": "Geräte hinzufügen, um automatische Wartungs-Erinnerungen zu aktivieren.",
    "Chlorine neutralizer (thiosulfate) exists: dose carefully.": "Chlor-Neutralisator (Thiosulfat) existiert: vorsichtig dosieren.",
    "Measure free AND total chlorine (combined = total - free).": "Freies UND gesamtes Chlor messen (gebunden = gesamt - frei).",
    "Covering the pool doesn't speed up the drop: leave it open.": "Abdecken des Pools beschleunigt den Abbau nicht: offen lassen.",
    "If not urgent: wait (sun degrades free chlorine in 24-48h).": "Nicht dringend: warten (Sonne baut freies Chlor in 24–48 Std. ab).",
    "Photograph the surface water and the filter pressure gauge.": "Fotografieren Sie das Oberflächenwasser und das Filter-Manometer.",
    "Reference for your measurements (AQWELIA proprietary mode).": "Referenz für Ihre Messungen (AQWELIA-eigener Modus).",
    "Check free and combined chlorine (chloramines = cloudiness).": "Freies und gebundenes Chlor prüfen (Chloramine = Trübung).",
    "High volume for a spa (usually 0.8 to 3 m³). Check the unit.": "Hohes Volumen für ein Spa (normalerweise 0,8 bis 3 m³). Einheit prüfen.",
    "Check CYA (stabilizer): if > 60, chlorine is locked → dilute.": "CYA prüfen (Stabilisator): bei > 60 ist Chlor blockiert → verdünnen.",
    "If combined chlorine > 0.4 mg/L: chloramines are the culprit.": "Wenn gebundenes Chlor > 0,4 mg/L: Chloramine sind die Ursache.",
    "Unlimited advice, smart reminders, PDF reports and much more.": "Unbegrenzte Beratung, intelligente Erinnerungen, PDF-Berichte und vieles mehr.",
    "Your data stays on your device. You can edit everything later.": "Ihre Daten bleiben auf Ihrem Gerät. Sie können alles später bearbeiten.",
    "Current plan: {plan}. Manage your subscription from the portal.": "Aktueller Plan: {plan}. Verwalten Sie Ihr Abonnement im Portal.",
    "Irreversible action. All your data will be permanently deleted.": "Unumkehrbare Aktion. Alle Ihre Daten werden dauerhaft gelöscht.",
    "My free chlorine is at 0 mg/L. How do I bring it back up safely?": "Mein freies Chlor liegt bei 0 mg/L. Wie bringe ich es sicher wieder hoch?",
    "My free chlorine is too high (> 5 mg/L). How do I bring it down?": "Mein freies Chlor ist zu hoch (> 5 mg/L). Wie senke ich es?",
    "pH required. Other parameters are optional but improve accuracy.": "pH erforderlich. Andere Parameter sind optional, erhöhen aber die Genauigkeit.",
    "⚠️ Above 38°C, limit sessions to 15-20 min (cardiovascular risk).": "⚠️ Über 38 °C Sitzungen auf 15–20 Min. begrenzen (kardiovaskuläres Risiko).",
    "Photograph the water surface and a wall to confirm algae presence.": "Fotografieren Sie die Wasseroberfläche und eine Wand, um Algen zu bestätigen.",
    "Quantities calculated from your water volume and treatment method.": "Mengen, berechnet aus Ihrem Wasservolumen und Ihrer Behandlungsmethode.",
    "Ask me anything about pH, chlorine, algae, filtration, winterizing…": "Fragen Sie mich alles über pH, Chlor, Algen, Filtration, Überwinterung…",
    "My pH won't hold, it keeps going up or down. How do I stabilize it?": "Mein pH hält nicht, er steigt oder sinkt ständig. Wie stabilisiere ich ihn?",
    "Smart reminders generated from your history, weather and equipment.": "Intelligente Erinnerungen, generiert aus Verlauf, Wetter und Geräten.",
    "Expert guides, tutorials and how-tos for clear water all year round.": "Experten-Anleitungen, Tutorials und Anleitungen für das ganze Jahr klares Wasser.",
    "Indicative answers. Always verify with a water test before treatment.": "Richtwert-Antworten. Vor der Behandlung immer mit einer Wasseranalyse überprüfen.",
    "My water is cloudy but not green. Help me find the cause and clear it.": "Mein Wasser ist trüb, aber nicht grün. Helfen Sie mir, die Ursache zu finden und es zu klären.",
    "Swimmers have stinging eyes and skin irritation. Is it pH or chlorine?": "Badende haben brennende Augen und Hautreizungen. Ist es pH oder Chlor?",
    "My salt electrolyzer shows an error code. What are the possible causes?": "Mein Salzelektrolyseur zeigt einen Fehlercode. Was sind die möglichen Ursachen?",
    "In compliance with GDPR, you can export or delete your data at any time.": "Gemäß DSGVO können Sie Ihre Daten jederzeit exportieren oder löschen.",
    "Weather reminders, post-treatment re-test, low stock… Upgrade to Premium.": "Wetter-Erinnerungen, Nachmessung nach Behandlung, niedriger Bestand… Upgrade auf Premium.",
    "I have algae forming on the pool walls. How do I eliminate it permanently?": "Ich habe Algenbildung an den Poolwänden. Wie werde ich sie dauerhaft los?",
    "Optional: if left empty, AQWELIA will use IP geolocation or ask you later.": "Optional: Wenn leer, verwendet AQWELIA IP-Geolokalisierung oder fragt später nach.",
    "Assess safety before swimming. In case of irritation, get out of the water.": "Sicherheit vor dem Baden prüfen. Bei Reizungen aus dem Wasser steigen.",
    "My pool just went through a storm (rain, heat, debris). Help me restore it.": "Mein Pool hat gerade einen Sturm erlebt (Regen, Hitze, Schmutz). Helfen Sie mir, ihn wiederherzustellen.",
    "Download all your data (pool, measurements, photos, history) in JSON format.": "Alle Ihre Daten herunterladen (Pool, Messungen, Fotos, Verlauf) im JSON-Format.",
    "Eco-friendly and odorless. Watch the temperature: less effective above 35°C.": "Umweltfreundlich und geruchlos. Achten Sie auf die Temperatur: über 35 °C weniger wirksam.",
    "It's spring, I'm restarting my pool after winter. Give me the full protocol.": "Es ist Frühling, ich starte meinen Pool nach dem Winter neu. Geben Sie mir das vollständige Protokoll.",
    "My water turned green, help me identify the cause and treat it step by step.": "Mein Wasser ist grün geworden, helfen Sie mir, die Ursache zu finden und Schritt für Schritt zu behandeln.",
    "Order matters: TA before pH, pH before chlorine, chlorine before filtration.": "Reihenfolge ist wichtig: TA vor pH, pH vor Chlor, Chlor vor Filtration.",
    "Reactivate your Premium or Expert subscriptions purchased on another device.": "Reaktivieren Sie Ihre Premium- oder Expert-Abonnements, die auf einem anderen Gerät gekauft wurden.",
    "We couldn't fetch the weather. Check your connection or try another location.": "Wir konnten das Wetter nicht abrufen. Prüfen Sie Ihre Verbindung oder versuchen Sie einen anderen Ort.",
    "Real conditions, personalized alerts and recommended filtration for your pool.": "Echte Bedingungen, personalisierte Alarme und empfohlene Filtration für Ihren Pool.",
    "You're all caught up! Smart reminders will appear here based on your activity.": "Sie sind auf dem neuesten Stand! Intelligente Erinnerungen erscheinen hier basierend auf Ihrer Aktivität.",
    "Automatically generated from your latest measurement. Follow the steps in order.": "Automatisch aus Ihrer letzten Messung generiert. Befolgen Sie die Schritte in der angegebenen Reihenfolge.",
    "My pool smells strongly of chlorine, yet free chlorine is normal. What's going on?": "Mein Pool riecht stark nach Chlor, aber freies Chlor ist normal. Was ist los?",
    "You're offline. Your question has been saved and will be processed on reconnection.": "Sie sind offline. Ihre Frage wurde gespeichert und wird bei der nächsten Verbindung bearbeitet.",
    "You're on the Free plan. Subscribe to Premium or Expert to manage your subscription.": "Sie sind im Kostenlos-Plan. Abonnieren Sie Premium oder Expert, um Ihr Abonnement zu verwalten.",
    "Before buying, check your inventory: AQWELIA flags low stock so you avoid duplicates.": "Vor dem Kauf Bestand prüfen: AQWELIA meldet niedrige Bestände, um Doppelkäufe zu vermeiden.",
    "I want to winterize my pool properly for winter. Give me the active/passive protocol.": "Ich möchte meinen Pool richtig für den Winter überwintern. Geben Sie mir das aktive/passive Protokoll.",
    "Tip: measure pH first, then chlorine, TA and CYA. The action plan adapts automatically.": "Tipp: zuerst pH messen, dann Chlor, TA und CYA. Der Aktionsplan passt sich automatisch an.",
    "Enter your test values (pH required). The action plan is generated automatically on save.": "Geben Sie Ihre Messwerte ein (pH erforderlich). Der Aktionsplan wird beim Speichern automatisch generiert.",
    "Stripe is not configured locally. In production, this button will open the Stripe portal.": "Stripe ist lokal nicht konfiguriert. In Produktion öffnet diese Schaltfläche das Stripe-Portal.",
    "AQWELIA will adapt its recommendations for hot water and monitor the bromine level (3-5 mg/L).": "AQWELIA passt seine Empfehlungen für heißes Wasser an und überwacht den Bromgehalt (3–5 mg/L).",
    "Risk depends on heat, UV and rain. The higher the risk, the earlier you should test and treat.": "Das Risiko hängt von Hitze, UV und Regen ab. Je höher das Risiko, desto früher sollten Sie messen und behandeln.",
    "I'm back from vacation, my pool ran for several weeks without maintenance. How do I restart it?": "Ich bin aus dem Urlaub zurück, mein Pool lief mehrere Wochen ohne Wartung. Wie starte ich ihn neu?",
    "Complete history: water measurements, quality indices, photo diagnostics. PDF report coming soon.": "Vollständiger Verlauf: Wasser-Messwerte, Qualitäts-Indizes, Foto-Diagnosen. PDF-Bericht folgt bald.",
    "Enter your first test (pH minimum) to activate the clear water index, action plan and swim safety.": "Erste Messung eingeben (mindestens pH), um den Kristallwasser-Index, Aktionsplan und Badesicherheit zu aktivieren.",
    "Track your equipment (maintenance, upcoming deadlines) and your product stock so you never run out.": "Verfolgen Sie Ihre Geräte (Wartung, anstehende Termine) und Ihren Produktbestand, damit Sie nie leer ausgehen.",
    "In case of electrical danger, leak, severe irritation or inability to treat, contact a professional.": "Bei elektrischer Gefahr, Leck, starker Reizung oder Unfähigkeit zu behandeln, wenden Sie sich an einen Fachmann.",
    "Select your situation: AQWELIA provides a guided protocol and can prepare a question for the AI assistant.": "Wählen Sie Ihre Situation: AQWELIA bietet ein geführtes Protokoll und kann eine Frage für den KI-Assistenten vorbereiten.",
    "The spa configuration is saved but advanced spa recommendations (bromine, draining, pump programs) require the": "Die Spa-Konfiguration wird gespeichert, aber erweiterte Spa-Empfehlungen (Brom, Ablassen, Pumpenprogramme) erfordern den",
    "Enter a water measurement to automatically generate an ordered action plan: immediate actions, dosages, swim safety.": "Wasser-Messwert eingeben, um automatisch einen geordneten Aktionsplan zu generieren: Sofortmaßnahmen, Dosierungen, Badesicherheit.",
    "Ask your questions: dosages, maintenance, safety, equipment. The assistant knows your pool and your latest measurements.": "Stellen Sie Ihre Fragen: Dosierungen, Wartung, Sicherheit, Geräte. Der Assistent kennt Ihren Pool und Ihre letzten Messungen.",
    "Describe your pool or spa to activate the copilot: personalized advice, exact dosages, ordered action plans and safety alerts.": "Beschreiben Sie Ihren Pool oder Spa, um den Copiloten zu aktivieren: personalisierte Ratschläge, exakte Dosierungen, geordnete Aktionspläne und Sicherheits-Alarme.",
    "The full PDF report (measurements, action plans, diagnostics) is coming soon. In the meantime, all your data is kept in the log.": "Der vollständige PDF-Bericht (Messungen, Aktionspläne, Diagnosen) folgt bald. In der Zwischenzeit werden alle Ihre Daten im Protokoll aufbewahrt.",
    "Yes. You can upgrade or downgrade whenever you want. The change applies immediately and the prorata is calculated automatically.": "Ja. Sie können jederzeit upgraden oder downgraden. Die Änderung wird sofort wirksam und die anteilige Berechnung erfolgt automatisch.",
    "At the end of the paid period, you automatically revert to the Free plan. Your data is retained; only premium features are suspended.": "Am Ende des kostenpflichtigen Zeitraums fallen Sie automatisch auf den Kostenlos-Plan zurück. Ihre Daten bleiben erhalten; nur Premium-Funktionen werden ausgesetzt.",
    "You can request a full refund within 14 days of your first payment, no questions asked. Beyond that, contact support for special cases.": "Sie können innerhalb von 14 Tagen nach Ihrer ersten Zahlung eine volle Rückerstattung verlangen, ohne Angabe von Gründen. Danach wenden Sie sich für Sonderfälle an den Support.",
    "For now we offer 7 days, 1 month, 3 months (-10%) and 6 months (-20%). An annual plan is in preparation — contact us to get early access.": "Wir bieten derzeit 7 Tage, 1 Monat, 3 Monate (-10%) und 6 Monate (-20%). Ein Jahresplan ist in Vorbereitung — kontaktieren Sie uns für frühen Zugang.",
    "This information allows AQWELIA to calculate the recommended filtration duration and schedule maintenance reminders (filter washing, etc.).": "Diese Informationen ermöglichen es AQWELIA, die empfohlene Filtrationsdauer zu berechnen und Wartungs-Erinnerungen zu planen (Filter spülen usw.).",
    "Premium Spa Support. The spa configuration is saved but advanced spa recommendations (bromine, draining, pump programs) require the Premium plan.": "Premium-Spa-Support. Die Spa-Konfiguration wird gespeichert, aber erweiterte Spa-Empfehlungen (Brom, Ablassen, Pumpenprogramme) erfordern den Premium-Plan.",
    "⚠️ Chlorine not recommended in spa. At high temperature, chlorine evaporates quickly, forms irritating chloramines and smells strong. AQWELIA strongly recommends bromine for spas.": "⚠️ Chlor im Spa nicht empfohlen. Bei hoher Temperatur verdunstet Chlor schnell, bildet reizende Chloramine und riecht stark. AQWELIA empfiehlt ausdrücklich Brom für Spas.",
    "This action is irreversible. All your data (pools, measurements, photos, history, subscription) will be deleted immediately and cannot be recovered. If you have an active subscription, please cancel it first from the App Store or Google Play.": "Diese Aktion ist unumkehrbar. Alle Ihre Daten (Pools, Messungen, Fotos, Verlauf, Abonnement) werden sofort gelöscht und können nicht wiederhergestellt werden. Wenn Sie ein aktives Abonnement haben, kündigen Sie es bitte zuerst im App Store oder Google Play.",
}


def translate_json(obj):
    """Recursively translate all string values in the JSON object."""
    if isinstance(obj, dict):
        return {k: translate_json(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [translate_json(v) for v in obj]
    elif isinstance(obj, str):
        return TRANSLATIONS.get(obj, obj)
    else:
        return obj


def main():
    de_path = 'src/i18n/locales/de.json'
    en_path = 'src/i18n/locales/en.json'

    with open(de_path, 'r', encoding='utf-8') as f:
        de = json.load(f)
    with open(en_path, 'r', encoding='utf-8') as f:
        en = json.load(f)

    def flatten(obj, prefix=''):
        out = {}
        if isinstance(obj, dict):
            for k, v in obj.items():
                key = f"{prefix}.{k}" if prefix else k
                out.update(flatten(v, key))
        elif isinstance(obj, list):
            for i, v in enumerate(obj):
                key = f"{prefix}[{i}]"
                out.update(flatten(v, key))
        else:
            out[prefix] = obj
        return out

    de_flat_before = flatten(de)
    en_flat = flatten(en)

    identical_before = 0
    for k in de_flat_before:
        if k in en_flat and de_flat_before[k] == en_flat[k]:
            val = de_flat_before[k]
            if val is None or val is True or val is False:
                continue
            if isinstance(val, (int, float)):
                continue
            identical_before += 1

    # Apply translations
    de_translated = translate_json(de)

    de_flat_after = flatten(de_translated)

    identical_after = 0
    translated_count = 0
    untranslated_keys = []
    for k in de_flat_after:
        if k in en_flat and de_flat_after[k] == en_flat[k]:
            val = de_flat_after[k]
            if val is None or val is True or val is False:
                continue
            if isinstance(val, (int, float)):
                continue
            identical_after += 1
            untranslated_keys.append((k, val))

    for k in de_flat_before:
        if k in en_flat and de_flat_before[k] == en_flat[k]:
            val = de_flat_before[k]
            if val is None or val is True or val is False:
                continue
            if isinstance(val, (int, float)):
                continue
            if de_flat_after[k] != de_flat_before[k]:
                translated_count += 1

    # Write back
    with open(de_path, 'w', encoding='utf-8') as f:
        json.dump(de_translated, f, ensure_ascii=False, indent=2)
        f.write('\n')

    total = len(de_flat_after)
    print(f"Total values: {total}")
    print(f"Identical before: {identical_before} ({identical_before/total*100:.2f}%)")
    print(f"Translated: {translated_count}")
    print(f"Identical after: {identical_after} ({identical_after/total*100:.2f}%)")
    print(f"\nRemaining identical values:")
    for k, v in untranslated_keys:
        print(f"  {k}: {v}")


if __name__ == '__main__':
    main()
