#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build Dutch translation for AQWELIA i18n nl-part2."""
import json
import os

OUT = {}

# --- guidesData.reminder_* (5 keys) ---
OUT["guidesData.reminder_test_water_detail"] = "Het is tijd om uw water te testen."
OUT["guidesData.reminder_test_water_title"] = "Watertest"
OUT["guidesData.reminder_winterize_action"] = "Actie voor winterklaar maken"
OUT["guidesData.reminder_winterize_detail"] = "Detail voor winterklaar maken"
OUT["guidesData.reminder_winterize_title"] = "Winterklaar maken"

# --- guidesData.salt-system-basics.* (13 keys) ---
OUT["guidesData.salt-system-basics.steps.1.detail"] = "Zout (NaCl) wordt in-situ geëlektrolyseerd tot actief chloor. Geen chlooropslag, zachter water."
OUT["guidesData.salt-system-basics.steps.1.title"] = "Het principe"
OUT["guidesData.salt-system-basics.steps.2.detail"] = "Afhankelijk van het model: over het algemeen 3-7 g/L. Raadpleeg de handleiding. Te laag = geen productie; te hoog = oververbruik."
OUT["guidesData.salt-system-basics.steps.2.title"] = "Vereist zoutgehalte"
OUT["guidesData.salt-system-basics.steps.3.detail"] = "Zonder stabilisator wordt het geproduceerde chloor door de zon vernietigd in 2 u."
OUT["guidesData.salt-system-basics.steps.3.title"] = "Stabilisator (CYA) onmisbaar"
OUT["guidesData.salt-system-basics.steps.4.detail"] = "De electrolyzer verhoogt de pH. Vaak bijregelen nodig."
OUT["guidesData.salt-system-basics.steps.4.title"] = "De pH in de gaten houden"
OUT["guidesData.salt-system-basics.steps.5.detail"] = "In koud water (< 15 °C) daalt de productie. Geen zorgen in de winter."
OUT["guidesData.salt-system-basics.steps.5.title"] = "Productie afhankelijk van temperatuur"
OUT["guidesData.salt-system-basics.steps.6.detail"] = "Zure reiniging elke 3-6 maanden, afhankelijk van de waterhardheid."
OUT["guidesData.salt-system-basics.steps.6.title"] = "Onderhoud cel"
OUT["guidesData.salt-system-basics.summary"] = "Principe, zoutgehalte, productie, routinematig onderhoud."
OUT["guidesData.salt-system-basics.title"] = "Begrijp uw zout-electrolyzer"

# --- guidesData.startup.* (15 keys) ---
OUT["guidesData.startup.steps.1.detail"] = "Verwijder opeengehoopte bladeren en vuil."
OUT["guidesData.startup.steps.1.title"] = "Verwijder de afdekking en reinig"
OUT["guidesData.startup.steps.2.detail"] = "Vul het waterpeel bij."
OUT["guidesData.startup.steps.2.title"] = "Bijvullen als het waterpeil laag is"
OUT["guidesData.startup.steps.3.detail"] = "Controleer het filter (backwash indien nodig)."
OUT["guidesData.startup.steps.3.title"] = "Start de filtratie"
OUT["guidesData.startup.steps.4.detail"] = "pH, chloor, TAC, stabilisator."
OUT["guidesData.startup.steps.4.title"] = "Test het water"
OUT["guidesData.startup.steps.5.detail"] = "TAC → pH → chloor. Geen haast."
OUT["guidesData.startup.steps.5.title"] = "Geleidelijk in balans brengen"
OUT["guidesData.startup.steps.6.detail"] = "Om op een gezonde basis te herstarten."
OUT["guidesData.startup.steps.6.title"] = "Een shockbehandeling uitvoeren"
OUT["guidesData.startup.steps.7.detail"] = "Pomp, electrolyzer, afdichtingen, manometer."
OUT["guidesData.startup.steps.7.title"] = "Controleer de apparatuur"
OUT["guidesData.startup.summary"] = "Uw zwembad na de winter zachtjes wekken."
OUT["guidesData.startup.title"] = "Seizoensstart in de lente"

# --- guidesData.swim-safety.* (11 keys) ---
OUT["guidesData.swim-safety.steps.1.detail"] = "Buiten dit bereik: mogelijke irritatie."
OUT["guidesData.swim-safety.steps.1.title"] = "pH tussen 7.0 en 7.6"
OUT["guidesData.swim-safety.steps.2.detail"] = "Minder = onvoldoende desinfectie. Meer = irritatie."
OUT["guidesData.swim-safety.steps.2.title"] = "Vrij chloor tussen 1 en 3 mg/L"
OUT["guidesData.swim-safety.steps.3.detail"] = "Daarboven: sterke geur, prikkende ogen."
OUT["guidesData.swim-safety.steps.3.title"] = "Gebonden chloor < 0.4 mg/L"
OUT["guidesData.swim-safety.steps.4.detail"] = "2 u na pH, 8 u na chloor-shock."
OUT["guidesData.swim-safety.steps.4.title"] = "Respecteer de wachttijden na behandeling"
OUT["guidesData.swim-safety.steps.5.detail"] = "Beter wachten op een test dan twijfelachtig water ingaan."
OUT["guidesData.swim-safety.steps.5.title"] = "Bij twijfel: niet zwemmen"
OUT["guidesData.swim-safety.summary"] = "Veiligheidscriteria voor risicovrij zwemmen."
OUT["guidesData.swim-safety.title"] = "Zwemveiligheid: wanneer mag u zwemmen?"

# --- guidesData.tac-control.* (11 keys) ---
OUT["guidesData.tac-control.steps.1.detail"] = "TAC (totale alkaliniteit) stabiliseert de pH. Zonder TAC schiet de pH omhoog bij elke producttoevoeging."
OUT["guidesData.tac-control.steps.1.title"] = "Rol van TAC"
OUT["guidesData.tac-control.steps.2.detail"] = "Doel 100 mg/L."
OUT["guidesData.tac-control.steps.2.title"] = "Ideaal bereik 80-120 mg/L"
OUT["guidesData.tac-control.steps.3.detail"] = "Breng TAC altijd eerst in balans, anders houdt de pH niet stand."
OUT["guidesData.tac-control.steps.3.title"] = "AANPASSEN VOOR de pH"
OUT["guidesData.tac-control.steps.4.detail"] = "Verdunnen, verdelen, 3 u filtratie."
OUT["guidesData.tac-control.steps.4.title"] = "Om te verhogen: natriumbicarbonaat"
OUT["guidesData.tac-control.steps.5.detail"] = "Complexer, langzaam uitvoeren met een pH-."
OUT["guidesData.tac-control.steps.5.title"] = "Om te verlagen: zuur"
OUT["guidesData.tac-control.summary"] = "TAC is de buffer van de pH. Zonder goede TAC wordt de pH onstabiel."
OUT["guidesData.tac-control.title"] = "Begrijp alkaliniteit (TAC)"

# --- guidesData.tag_* (18 keys) ---
OUT["guidesData.tag_algues"] = "algen"
OUT["guidesData.tag_backwash"] = "backwash"
OUT["guidesData.tag_cartouche"] = "cartridge"
OUT["guidesData.tag_chloramines"] = "chloramines"
OUT["guidesData.tag_chlore"] = "chloor"
OUT["guidesData.tag_choc"] = "shock"
OUT["guidesData.tag_debutant"] = "beginner"
OUT["guidesData.tag_electrolyseur"] = "electrolyzer"
OUT["guidesData.tag_filtration"] = "filtratie"
OUT["guidesData.tag_filtre"] = "filter"
OUT["guidesData.tag_floculant"] = "flocculant"
OUT["guidesData.tag_odeur"] = "geur"
OUT["guidesData.tag_securite"] = "veiligheid"
OUT["guidesData.tag_sel"] = "zout"
OUT["guidesData.tag_trouble"] = "troebel"
OUT["guidesData.tag_vert"] = "groen"
OUT["guidesData.tag_yeux"] = "ogen"

# --- guidesData.vacation-mode.* (15 keys) ---
OUT["guidesData.vacation-mode.steps.1.detail"] = "Alles in balans brengen voor vertrek: pH, chloor, TAC."
OUT["guidesData.vacation-mode.steps.1.title"] = "Een volledige test uitvoeren"
OUT["guidesData.vacation-mode.steps.2.detail"] = "Grondig desinfecteren."
OUT["guidesData.vacation-mode.steps.2.title"] = "Shock-chloor de dag ervoor"
OUT["guidesData.vacation-mode.steps.3.detail"] = "Bij een afwezigheid < 1 week."
OUT["guidesData.vacation-mode.steps.3.title"] = "Vul de dispenser met langzaam chloor"
OUT["guidesData.vacation-mode.steps.4.detail"] = "Minstens 4-6 u/dag, bij voorkeur 's nachts."
OUT["guidesData.vacation-mode.steps.4.title"] = "Stel de filtratietimer in"
OUT["guidesData.vacation-mode.steps.5.detail"] = "Dekzeil of afdekking: beperkt vuil en verdamping."
OUT["guidesData.vacation-mode.steps.5.title"] = "Dek het zwembad af"
OUT["guidesData.vacation-mode.steps.6.detail"] = "Laat iemand controleren of installeer een robot."
OUT["guidesData.vacation-mode.steps.6.title"] = "Bij lange afwezigheid: buur of robot"
OUT["guidesData.vacation-mode.steps.7.detail"] = "In de zomer is verminderde filtratie voldoende. In de winter volledige wintervoorbereiding."
OUT["guidesData.vacation-mode.steps.7.title"] = "Afhankelijk van het seizoen: actieve of passieve wintervoorbereiding"
OUT["guidesData.vacation-mode.summary"] = "Bereid uw zwembad voor op een afwezigheid van enkele dagen/weken."
OUT["guidesData.vacation-mode.title"] = "Voordat u op vakantie gaat"

# --- guidesData.winterization.* (15 keys) ---
OUT["guidesData.winterization.steps.1.detail"] = "Actief: verminderde filtratie. Passief: volledige stop. Hangt af van het klimaat."
OUT["guidesData.winterization.steps.1.title"] = "Kies actieve of passieve wintervoorbereiding"
OUT["guidesData.winterization.steps.2.detail"] = "Water, wanden, bodem, filter, waterlijn."
OUT["guidesData.winterization.steps.2.title"] = "Grondig reinigen"
OUT["guidesData.winterization.steps.3.detail"] = "Winterproduct, anti-algen en anti-kalk."
OUT["guidesData.winterization.steps.3.title"] = "Voer een wintervoorbehandeling uit"
OUT["guidesData.winterization.steps.4.detail"] = "10-15 cm onder de mondstukken voor passief."
OUT["guidesData.winterization.steps.4.title"] = "Verlaag het waterpeil"
OUT["guidesData.winterization.steps.5.detail"] = "Tegen vorst beschermen."
OUT["guidesData.winterization.steps.5.title"] = "Voelbare leidingen ledigen"
OUT["guidesData.winterization.steps.6.detail"] = "Winterdekzeil of afdekking."
OUT["guidesData.winterization.steps.6.title"] = "Dek het zwembad af"
OUT["guidesData.winterization.steps.7.detail"] = "Vooral tijdens vorstperioden."
OUT["guidesData.winterization.steps.7.title"] = "Actieve wintervoorbereiding: filtratie 2-3 u/dag"
OUT["guidesData.winterization.summary"] = "Het zwembad winterklaar maken zonder de apparatuur te beschadigen."
OUT["guidesData.winterization.title"] = "Uw zwembad winterklaar maken"

# --- landing.* (19 keys) ---
OUT["landing.disclaimerLabel"] = "Disclaimer."
OUT["landing.faqEyebrow"] = "12 — FAQ"
OUT["landing.footerBlog"] = "Blog"
OUT["landing.footerContact"] = "Contact"
OUT["landing.footerPrivacy"] = "Privacy"
OUT["landing.footerProduct"] = "Product"
OUT["landing.footerProductFaq"] = "FAQ"
OUT["landing.footerSupport"] = "Support"
OUT["landing.footerVersion"] = "v2.0 Copiloot"
OUT["landing.heroBadge"] = "AQUA · WELL · AI"
OUT["landing.heroPhoneBadge"] = "AI ONLINE"
OUT["landing.heroPhoneChlorine"] = "Chloor"
OUT["landing.heroPhoneStep1"] = "1. pH- 900 ml"
OUT["landing.navFaq"] = "FAQ"
OUT["landing.savingsBar1"] = "AQWELIA Premium"
OUT["landing.spaBrandCategoryEco"] = "Eco"
OUT["landing.spaBrandCategoryPremium"] = "Premium"
OUT["landing.storyAquaWord"] = "(aqua)"
OUT["landing.variationsFactor6Title"] = "UV"

# --- legal.backHome ---
OUT["legal.backHome"] = "Terug naar home"

# --- legal.cgu.* (54 keys) ---
OUT["legal.cgu.article10Body1"] = "AQWELIA doet er alles aan om de beschikbaarheid en betrouwbaarheid van de Dienst te verzekeren, maar kan geen totale afwezigheid van fouten of onderbrekingen garanderen."
OUT["legal.cgu.article10Body2"] = "Aangezien de Dienst informatief wordt aangeboden, kan AQWELIA niet aansprakelijk worden gesteld voor directe of indirecte schade voortvloeiend uit de toepassing van de aanbevelingen (met name: materiële schade, verlies van zwemplezier, aantasting van apparatuur, chemische reacties). Bij twijfel dient de Gebruiker een professional te raadplegen."
OUT["legal.cgu.article10Title"] = "Artikel 10 — Aansprakelijkheid"
OUT["legal.cgu.article11Body1"] = "Alle elementen van de Dienst (merk, logo, teksten, algoritmes, ontwerp, gidsen) zijn exclusief eigendom van AQWELIA of haar partners. Elke reproductie, weergave of verspreiding, geheel of gedeeltelijk, zonder voorafgaande schriftelijke toestemming is verboden."
OUT["legal.cgu.article11Body2"] = "De door de Gebruiker ingevoerde Gegevens blijven zijn eigendom. De Gebruiker verleent AQWELIA een niet-exclusieve licentie voor het gebruik van deze Gegevens voor zover nodig voor de levering en verbetering van de Dienst."
OUT["legal.cgu.article11Title"] = "Artikel 11 — Intellectueel eigendom"
OUT["legal.cgu.article12Body1"] = "AQWELIA kan deze GBU op elk gewenst moment wijzigen. De van toepassing zijnde GBU zijn diegene die gelden op het moment van gebruik van de Dienst. Ingrijpende wijzigingen worden per e-mail of via de applicatie meegedeeld, ten minste 30 dagen voordat ze inwerking treden."
OUT["legal.cgu.article12Title"] = "Artikel 12 — Wijzigingen van de GBU"
OUT["legal.cgu.article13Body1"] = "Deze GBU worden beheerst door het Franse recht. Bij een geschil verplichten de partijen zich een minnelijke oplossing te zoeken voordat enige juridische actie wordt ondernomen. Bij gebrek aan overeenkomst zijn uitsluitend de Franse rechtbanken bevoegd."
OUT["legal.cgu.article13Title"] = "Artikel 13 — Toepasselijk recht"
OUT["legal.cgu.article1Body1"] = "Deze Algemene Gebruiksvoorwaarden (« <bold>GBU</bold> ») bepalen de voorwaarden en modaliteiten voor toegang tot en gebruik van de AQWELIA-applicatie (« <bold>de Dienst</bold> »), uitgegeven door de vennootschap AQWELIA, alsook de rechten en verplichtingen van de partijen in dit kader."
OUT["legal.cgu.article1Body2"] = "Het gebruik van de Dienst impliceert de volledige aanvaarding van deze GBU. Indien u niet akkoord gaat met een van deze voorwaarden, mag u de Dienst niet gebruiken."
OUT["legal.cgu.article1Title"] = "Artikel 1 — Doel"
OUT["legal.cgu.article2Item1"] = "« <bold>Gebruiker</bold> »: elke natuurlijke persoon die de Dienst gebruikt."
OUT["legal.cgu.article2Item2"] = "« <bold>Account</bold> »: persoonlijke ruimte die door de Gebruiker is aangemaakt om toegang te krijgen tot de Dienst."
OUT["legal.cgu.article2Item3"] = "« <bold>Gegevens</bold> »: informatie die door de Gebruiker is ingevoerd (metingen, foto's, zwembadprofiel, enz.)."
OUT["legal.cgu.article2Item4"] = "« <bold>Abonnement</bold> »: abonnementsformule (Free, Premium of Expert) waarop de Gebruiker zich abonneert."
OUT["legal.cgu.article2Item5"] = "« <bold>Inhoud</bold> »: aanbevelingen, actieplannen, analyses, gidsen en teksten die door de Dienst worden gegenereerd."
OUT["legal.cgu.article2Title"] = "Artikel 2 — Definities"
OUT["legal.cgu.article3Body1"] = "AQWELIA is een intelligente copiloot voor zwembadonderhoud. De Dienst stelt de Gebruiker in staat om:"
OUT["legal.cgu.article3Body2"] = "De Dienst wordt informatief aangeboden en vervangt niet de tussenkomst van een gekwalificeerde professional (zwembadspecialist, verdeler, redder)."
OUT["legal.cgu.article3Item1"] = "de kwaliteit van zijn zwembadwater opvolgen en analyseren (pH, chloor, TAC, TH, enz.);"
OUT["legal.cgu.article3Item2"] = "persoonlijke actieplannen verkrijgen (doseringen, filtratie, zwembaarheid);"
OUT["legal.cgu.article3Item3"] = "water en apparatuur visueel diagnosticeren via foto;"
OUT["legal.cgu.article3Item4"] = "een AI-assistent raadplegen voor elke onderhoudsvraag;"
OUT["legal.cgu.article3Item5"] = "slimme herinneringen ontvangen (weer, apparatuur, productvoorraden);"
OUT["legal.cgu.article3Item6"] = "educatieve gidsen en bronnen raadplegen."
OUT["legal.cgu.article3Title"] = "Artikel 3 — Beschrijving van de dienst"
OUT["legal.cgu.article4Body1"] = "Registratie voor de Dienst vereist het aanmaken van een Account via een geldig e-mailadres en een wachtwoord. De Gebruiker verbindt zich ertoe nauwkeurige informatie te verstrekken en deze up-to-date te houden."
OUT["legal.cgu.article4Body2"] = "De Gebruiker is als enige verantwoordelijk voor de vertrouwelijkheid van zijn inloggegevens en voor elk gebruik van zijn Account. Elke activiteit die vanuit zijn Account wordt uitgevoerd, wordt geacht door de Gebruiker te zijn uitgevoerd."
OUT["legal.cgu.article4Body3"] = "AQWELIA behoudt zich het recht voor een Account te weigeren of te sluiten bij niet-naleving van deze GBU of bij frauduleus gedrag."
OUT["legal.cgu.article4Title"] = "Artikel 4 — Registratie en account"
OUT["legal.cgu.article5Body1"] = "De Gebruiker verbindt zich ertoe:"
OUT["legal.cgu.article5Body2"] = "De Gebruiker erkent dat de door de Dienst verstrekte aanbevelingen indicatief zijn en dat hij als enige verantwoordelijk blijft voor de acties die hij op zijn zwembad onderneemt."
OUT["legal.cgu.article5Item1"] = "de Dienst te gebruiken in overeenstemming met het doel ervan en het geldende recht;"
OUT["legal.cgu.article5Item2"] = "niet te proberen de Dienst om te leiden, uit te schakelen of de beveiliging ervan in gevaar te brengen;"
OUT["legal.cgu.article5Item3"] = "ge Inhoud te uploaden die onrechtmatig, lasterlijk is of inbreuk maakt op de rechten van derden;"
OUT["legal.cgu.article5Item4"] = "de voorschriften van de chemische producten die worden gebruikt voor het onderhoud van zijn zwembad na te leven."
OUT["legal.cgu.article5Title"] = "Artikel 5 — Gebruik van de dienst"
OUT["legal.cgu.article6Body1"] = "De Dienst biedt drie Abonnementen:"
OUT["legal.cgu.article6Body2"] = "De functionaliteiten en tarieven van elk Abonnement worden beschreven op de pagina <link>Tarieven</link>. AQWELIA behoudt zich het recht voor deze aanbiedingen op elk gewenst moment te wijzigen, mits zij geabonneerde Gebruikers ten minste 30 dagen voor inwerkingtreding informeert."
OUT["legal.cgu.article6Item1"] = "<bold>Free</bold>: gratis, omvat 1 zwembad, basis handmatige metingen, beperkte assistent."
OUT["legal.cgu.article6Item2"] = "<bold>Premium</bold>: tot 3 zwembaden, onbeperkte fotodiagnostiek, volledige AI-assistent, weersherinneringen, geavanceerde gidsen."
OUT["legal.cgu.article6Item3"] = "<bold>Expert</bold>: onbeperkt (professionele zwembadspecialisten), multi-klant, exports, prioritaire support."
OUT["legal.cgu.article6Title"] = "Artikel 6 — Abonnementen"
OUT["legal.cgu.article7Body1"] = "De betaling van Premium- en Expert-abonnementen gebeurt volgens het gebruikte platform:"
OUT["legal.cgu.article7Body2"] = "De verlenging is automatisch aan het einde van de geabonneerde periode, tenzij de Gebruiker dit uitschakelt in de instellingen van zijn Apple/Google-account of via de Stripe-klantenportaal."
OUT["legal.cgu.article7Item1"] = "<bold>Web</bold>: via Stripe (bankkaart, beveiligde betaling)."
OUT["legal.cgu.article7Item2"] = "<bold>iOS</bold>: via Apple In-App Purchase (beheerd door Apple)."
OUT["legal.cgu.article7Item3"] = "<bold>Android</bold>: via Google Play Billing (beheerd door Google)."
OUT["legal.cgu.article7Title"] = "Artikel 7 — Betaling"
OUT["legal.cgu.article8Body1"] = "De Gebruiker kan zijn abonnement op elk moment opzeggen vanuit de applicatie (pagina <link>Instellingen</link>) of vanuit de instellingen van de App Store / Google Play. De opzegging wordt effectief aan het einde van de lopende facturatieperiode."
OUT["legal.cgu.article8Body2"] = "AQWELIA behoudt zich het recht voor de toegang tot de Dienst te beëindigen of op te schorten bij een overtreding van de GBU, na voorafgaande kennisgeving, behalve in geval van nood."
OUT["legal.cgu.article8Title"] = "Artikel 8 — Beëindiging"
OUT["legal.cgu.article9Body1"] = "De verwerking van de persoonsgegevens van de Gebruiker wordt beheerst door ons <link>Privacybeleid</link>, in overeenstemming met de Algemene Verordening Gegevensbescherming (AVG, EU 2016/679)."
OUT["legal.cgu.article9Body2"] = "De Gebruiker heeft recht op toegang, rectificatie, verwijdering, draagbaarheid en bezwaar. Deze rechten kunnen worden uitgeoefend vanaf de pagina <link>Instellingen</link> of per e-mail via <alink>privacy@aqwelia.app</alink>."
OUT["legal.cgu.article9Title"] = "Artikel 9 — Persoonsgegevens (AVG)"
OUT["legal.cgu.contactBody1"] = "Voor elke vraag met betrekking tot deze GBU: <alink>legal@aqwelia.app</alink>"
OUT["legal.cgu.contactBody2"] = "Voor elke vraag met betrekking tot uw gegevens: <alink>privacy@aqwelia.app</alink>"
OUT["legal.cgu.contactBody3"] = "Voor elke supportaanvraag: <link>supportpagina</link>."
OUT["legal.cgu.contactTitle"] = "Contact"
OUT["legal.cgu.eyebrow"] = "Juridische mededeling"
OUT["legal.cgu.metaDescription"] = "Algemene gebruiksvoorwaarden van de AQWELIA-dienst."
OUT["legal.cgu.metaTitle"] = "GBU — AQWELIA"
OUT["legal.cgu.title"] = "Algemene Gebruiksvoorwaarden"

# --- legal.lastUpdatedLabel ---
OUT["legal.lastUpdatedLabel"] = "Laatst bijgewerkt:"

# --- legal.privacy.* (50 keys) ---
OUT["legal.privacy.eyebrow"] = "AVG"
OUT["legal.privacy.metaDescription"] = "Privacybeleid voor persoonsgegevens van AQWELIA (AVG)."
OUT["legal.privacy.metaTitle"] = "Privacybeleid — AQWELIA"
OUT["legal.privacy.section10Body1"] = "AQWELIA implementeert passende technische en organisatorische maatregelen om uw gegevens te beschermen:"
OUT["legal.privacy.section10Body2"] = "In geval van een datalek dat een risico vormt voor uw rechten en vrijheden, zal AQWELIA u zonder onredelijke vertraging informeren overeenkomstig artikel 34 van de AVG."
OUT["legal.privacy.section10Item1"] = "versleuteling van wachtwoorden (scrypt, bestand tegen brute-force);"
OUT["legal.privacy.section10Item2"] = "versleuteling van gegevens tijdens transport (TLS 1.2+) en in rust (databaseversleuteling);"
OUT["legal.privacy.section10Item3"] = "authenticatie via ondertekende JWT, beperkte geldigheidsduur (30 dagen);"
OUT["legal.privacy.section10Item4"] = "beperkte toegang tot persoonsgegevens (principe van minimale bevoegdheid);"
OUT["legal.privacy.section10Item5"] = "versleutelde back-ups en regelmatige penetratietests."
OUT["legal.privacy.section10Title"] = "10. Beveiliging"
OUT["legal.privacy.section11Body1"] = "Voor elke vraag over de bescherming van uw gegevens kunt u contact opnemen met onze FG (Functionaris voor Gegevensbescherming):"
OUT["legal.privacy.section11Body2"] = "Zie ook onze <link>GBU</link> en onze <link2>supportpagina</link2>."
OUT["legal.privacy.section11Title"] = "11. Contact FG"
OUT["legal.privacy.section1Body1"] = "De verwerkingsverantwoordelijke voor de via de AQWELIA-applicatie verzamelde persoonsgegevens is de vennootschap <bold>AQWELIA</bold>, uitgever van de Dienst."
OUT["legal.privacy.section1Body2"] = "Contact FG: <alink>privacy@aqwelia.app</alink>"
OUT["legal.privacy.section1Title"] = "1. Verwerkingsverantwoordelijke"
OUT["legal.privacy.section2Body1"] = "De Dienst verzamelt de volgende categorieën gegevens:"
OUT["legal.privacy.section2Item1"] = "<bold>Accountidentificatoren</bold>: e-mailadres, naam (optioneel), wachtwoord (gehasht)."
OUT["legal.privacy.section2Item2"] = "<bold>Zwembadprofiel</bold>: volume, vorm, bekleding, behandeling, filter, blootstelling, regio."
OUT["legal.privacy.section2Item3"] = "<bold>Watergegevens</bold>: metingen (pH, chloor, TAC, TH, CYA, zout, temperatuur, enz.) die zijn ingevoerd of geïmporteerd."
OUT["legal.privacy.section2Item4"] = "<bold>Foto's</bold>: afbeeldingen van water, wanden, filter, electrolyzers en producten, gebruikt voor visuele AI-diagnostiek."
OUT["legal.privacy.section2Item5"] = "<bold>Apparatuur en voorraad</bold>: merk, model, onderhoudsdatums, chemische producten op voorraad."
OUT["legal.privacy.section2Item6"] = "<bold>Geschiedenis</bold>: gesprekken met de AI-assistent, gegenereerde actieplannen, fotodiagnostiek."
OUT["legal.privacy.section2Item7"] = "<bold>Factureringsgegevens</bold>: geabonneerd abonnement, periode, status (betalingsinformatie wordt verwerkt door Stripe, Apple of Google — AQWELIA slaat geen kaartnummers op)."
OUT["legal.privacy.section2Item8"] = "<bold>Gebruiksgegevens</bold>: analytics-gebeurtenissen (raadpleging van gidsen, opening van betaalschermen, gebruiksfrequentie)."
OUT["legal.privacy.section2Title"] = "2. Verzamelde gegevens"
OUT["legal.privacy.section3Body1"] = "De gegevens worden verwerkt voor de volgende doeleinden:"
OUT["legal.privacy.section3Item1"] = "werking van de Dienst (generatie van actieplannen, doseringsberekeningen, opvolging van het water);"
OUT["legal.privacy.section3Item2"] = "verbetering van de AI-modellen (fotodiagnostiek, aanbevelingen) — op basis van voorafgaande anonimisering waar mogelijk;"
OUT["legal.privacy.section3Item3"] = "facturering en abonnementsbeheer;"
OUT["legal.privacy.section3Item4"] = "gebruikersondersteuning;"
OUT["legal.privacy.section3Item5"] = "gebruiksanalyse en verbetering van de ervaring;"
OUT["legal.privacy.section3Item6"] = "naleving van wettelijke en boekhoudkundige verplichtingen."
OUT["legal.privacy.section3Title"] = "3. Doeleinden"
OUT["legal.privacy.section4Body1"] = "Overeenkomstig artikel 6 van de AVG berust de verwerking op de volgende wettelijke grondslagen:"
OUT["legal.privacy.section4Body2"] = "De Gebruiker kan zijn toestemming op elk moment intrekken vanaf de pagina <link>Instellingen</link>, zonder afbreuk te doen aan de rechtmatigheid van de eerdere verwerking."
OUT["legal.privacy.section4Item1"] = "<bold>Uitvoering van de overeenkomst</bold> (art. 6.1.b): levering van de geabonneerde Dienst."
OUT["legal.privacy.section4Item2"] = "<bold>Toestemming</bold> (art. 6.1.a): voor diagnostiek verstuurde foto's, meldingen, eventuele marketingcommunicatie."
OUT["legal.privacy.section4Item3"] = "<bold>Gerechtvaardigd belang</bold> (art. 6.1.f): verbetering van de Dienst, beveiliging, fraudepreventie."
OUT["legal.privacy.section4Item4"] = "<bold>Wettelijke verplichting</bold> (art. 6.1.c): bewaring van facturen en boekhoudkundige sporen."
OUT["legal.privacy.section4Title"] = "4. Wettelijke grondslag"
OUT["legal.privacy.section5Item1"] = "<bold>Actief account</bold>: gebruiksduur van de Dienst."
OUT["legal.privacy.section5Item2"] = "<bold>Zwembadgegevens, metingen, foto's</bold>: bewaard zolang het Account actief is, plus 90 dagen na verwijdering (voor eventueel herstel), daarna definitief gewist."
OUT["legal.privacy.section5Item3"] = "<bold>Facturen</bold>: 10 jaar (wettelijke boekhoudverplichting in Frankrijk)."
OUT["legal.privacy.section5Item4"] = "<bold>Beveiligingslogs</bold>: 12 maanden."
OUT["legal.privacy.section5Item5"] = "<bold>Inactief account</bold>: na 24 maanden zonder aanmelding, melding per e-mail en vervolgens verwijdering van het Account en de bijbehorende gegevens."
OUT["legal.privacy.section5Title"] = "5. Bewaartermijn"
OUT["legal.privacy.section6Body1"] = "De gegevens zijn toegankelijk voor de volgende ontvangers:"
OUT["legal.privacy.section6Body2"] = "AQWELIA verkoopt uw gegevens nooit aan derden voor marketingdoeleinden."
OUT["legal.privacy.section6Item1"] = "<bold>AQWELIA</bold>: bevoegd personeel (ingenieurs, support) onder een geheimhoudingsovereenkomst."
OUT["legal.privacy.section6Item2"] = "<bold>Cloudhost</bold>: opslag en computing (EU-gelegen)."
OUT["legal.privacy.section6Item3"] = "<bold>Stripe</bold>: verwerking van webbetalingen (onderworpen aan een eigen AVG)."
OUT["legal.privacy.section6Item4"] = "<bold>RevenueCat</bold>: uniform beheer van iOS/Android-abonnementen."
OUT["legal.privacy.section6Item5"] = "<bold>Apple / Google</bold>: in-app-betalingen (onderworpen aan hun eigen voorwaarden)."
OUT["legal.privacy.section6Item6"] = "<bold>AI-leveranciers</bold>: voor fotodiagnostiek en de assistent — uitsluitend strikt noodzakelijke gegevens, zonder opslag buiten de sessie."
OUT["legal.privacy.section6Title"] = "6. Ontvangers"
OUT["legal.privacy.section7Body1"] = "De hoofdhosting bevindt zich in de Europese Unie. Eventuele transfers buiten de EU (bijvoorbeeld naar een in de Verenigde Staten gevestigde AI-leverancier) worden omkaderd door de standaardcontractbepalingen van de Europese Commissie (besluit 2021/914) en vergezeld van passende waarborgen (versleuteling, minimalisering, pseudonimisering)."
OUT["legal.privacy.section7Title"] = "7. Transfers buiten de EU"
OUT["legal.privacy.section8Body1"] = "Overeenkomstig de artikelen 15 tot 22 van de AVG beschikt u over de volgende rechten:"
OUT["legal.privacy.section8Body2"] = "Deze rechten kunnen rechtstreeks worden uitgeoefend vanaf de pagina <link>Instellingen</link> (JSON-export, accountverwijdering), of per e-mail via <alink>privacy@aqwelia.app</alink>."
OUT["legal.privacy.section8Body3"] = "U kunt ook een klacht indienen bij de AP (www.autoriteitpersoonsgegevens.nl) of bij de toezichthoudende autoriteit van uw land."
OUT["legal.privacy.section8Item1"] = "<bold>Recht op toegang</bold>: een kopie van uw gegevens verkrijgen."
OUT["legal.privacy.section8Item2"] = "<bold>Recht op rectificatie</bold>: onjuiste gegevens corrigeren."
OUT["legal.privacy.section8Item3"] = "<bold>Recht op verwijdering</bold> (\"recht om vergeten te worden\"): uw Account en uw gegevens verwijderen."
OUT["legal.privacy.section8Item4"] = "<bold>Recht op draagbaarheid</bold>: uw gegevens ontvangen in een gestructureerde en herbruikbare indeling."
OUT["legal.privacy.section8Item5"] = "<bold>Recht van bezwaar</bold>: verwerking weigeren die is gebaseerd op gerechtvaardigd belang."
OUT["legal.privacy.section8Item6"] = "<bold>Recht op beperking</bold>: een verwerking tijdelijk bevriezen."
OUT["legal.privacy.section8Item7"] = "<bold>Recht om uw toestemming</bold> op elk moment in te trekken."
OUT["legal.privacy.section8Title"] = "8. Uw rechten"
OUT["legal.privacy.section9Body1"] = "AQWELIA gebruikt een minimum aan trackers die strikt noodzakelijk zijn voor de werking van de Dienst (authenticatiesessie, taal- en themavoorkeuren). Er worden geen advertentie- of trackingcookies van derden geplaatst zonder toestemming."
OUT["legal.privacy.section9Body2"] = "De voorkeuren kunnen worden beheerd vanaf de pagina <link>Instellingen</link>."
OUT["legal.privacy.section9Title"] = "9. Cookies en trackers"
OUT["legal.privacy.title"] = "Privacybeleid"

# --- legal.support.* (22 keys) ---
OUT["legal.support.cardAssistantDesc"] = "Voor een snelle vraag over uw zwembad kunt u de assistent rechtstreeks in de app raadplegen."
OUT["legal.support.cardAssistantLink"] = "App openen"
OUT["legal.support.cardAssistantTitle"] = "Ingebouwde AI-assistent"
OUT["legal.support.cardBugDesc"] = "Heeft u onverwacht gedrag opgemerkt? Beschrijf het ons met, indien mogelijk, een schermafbeelding."
OUT["legal.support.cardBugLink"] = "Per e-mail melden"
OUT["legal.support.cardBugTitle"] = "Een bug melden"
OUT["legal.support.cardFaqDesc"] = "Antwoorden op de meest gestelde vragen: abonnementen, gegevens, zwembad, compatibiliteit."
OUT["legal.support.cardFaqLink"] = "FAQ bekijken"
OUT["legal.support.cardFaqTitle"] = "FAQ"
OUT["legal.support.cardFeatureDesc"] = "Een idee om AQWELIA te verbeteren? We lezen alle suggesties."
OUT["legal.support.cardFeatureLink"] = "Mijn idee delen"
OUT["legal.support.cardFeatureSubject"] = "Functie-idee AQWELIA"
OUT["legal.support.cardFeatureTitle"] = "Een functie aanvragen"
OUT["legal.support.cardKbDesc"] = "Gedetailleerde gidsen, video-tutorials en hulp artikelen. Binnenkort beschikbaar."
OUT["legal.support.cardKbLink"] = "Binnenkort beschikbaar"
OUT["legal.support.cardKbTitle"] = "Kennisbank"
OUT["legal.support.cardLegalDesc"] = "Voor AVG-, privacy- of GBU-onderwerpen, schrijf naar privacy@aqwelia.app."
OUT["legal.support.cardLegalLink"] = "Contact met de FG"
OUT["legal.support.cardLegalTitle"] = "Juridische vragen"
OUT["legal.support.emailDesc"] = "De beste manier om ons te bereiken. Antwoord binnen 48 werkuur."
OUT["legal.support.emailTitle"] = "E-mail"
OUT["legal.support.eyebrow"] = "Hulp & support"
OUT["legal.support.metaDescription"] = "Contact met AQWELIA-support, FAQ, een bug melden, een functie aanvragen."
OUT["legal.support.metaTitle"] = "Support — AQWELIA"
OUT["legal.support.resourcesCguLink"] = "Algemene voorwaarden"
OUT["legal.support.resourcesPrivacyLink"] = "Privacybeleid"
OUT["legal.support.resourcesSettingsLink"] = "Accountinstellingen"
OUT["legal.support.resourcesTitle"] = "Gerelateerde bronnen"
OUT["legal.support.responseTimeExpert"] = "<bold>Expert-abonnement</bold>: antwoord binnen 24 u, prioritaire support."
OUT["legal.support.responseTimeFree"] = "<bold>Free-abonnement</bold>: antwoord binnen 72 werkuur."
OUT["legal.support.responseTimePremium"] = "<bold>Premium-abonnement</bold>: antwoord binnen 48 werkuur."
OUT["legal.support.responseTimeTitle"] = "Responstijd"
OUT["legal.support.subtitle"] = "Ons team staat klaar om u te helpen het meeste uit AQWELIA te halen."
OUT["legal.support.title"] = "Contact met support"

# --- metadata.* (7 keys) ---
OUT["metadata.layoutDescription"] = "AQWELIA — de revolutionaire AI-aangedreven zwembadbeheer-app: expert-assistent, visuele wateranalyse, deterministisch actieplan en meer."
OUT["metadata.layoutKeywordAI"] = "AI"
OUT["metadata.layoutKeywordMaintenance"] = "onderhoud"
OUT["metadata.layoutKeywordPool"] = "zwembad"
OUT["metadata.layoutKeywordSmartAssistant"] = "slimme assistent"
OUT["metadata.layoutKeywordWaterQuality"] = "waterkwaliteit"
OUT["metadata.layoutTitle"] = "AQWELIA — Intelligente Copiloot voor Zwembad"

# --- mobile.screens.* (18 keys) ---
OUT["mobile.screens.analysesAriaSubtabs"] = "Subtabbladen Analyses"
OUT["mobile.screens.analysesSubtabLogbook"] = "Logboek"
OUT["mobile.screens.analysesSubtabMesures"] = "Metingen"
OUT["mobile.screens.analysesSubtabPhoto"] = "Foto"
OUT["mobile.screens.maintenanceAriaSubtabs"] = "Subtabbladen Onderhoud"
OUT["mobile.screens.maintenanceSubtabActions"] = "Acties"
OUT["mobile.screens.profileAriaPoolProfile"] = "Zwembadprofiel"
OUT["mobile.screens.profileAriaSettings"] = "Instellingen"
OUT["mobile.screens.profileAriaSubscription"] = "Abonnement"
OUT["mobile.screens.profileConfigureToStart"] = "Configureer uw zwembad om te beginnen"
OUT["mobile.screens.profileElectrolysisSalt"] = "Zout-electrolyse"
OUT["mobile.screens.profileFaqContact"] = "FAQ + contact"
OUT["mobile.screens.profileHelpSupport"] = "Hulp & support"
OUT["mobile.screens.profileNotifReminders"] = "Meldingen & herinneringen"
OUT["mobile.screens.profilePoolNotConfigured"] = "Zwembad niet geconfigureerd"
OUT["mobile.screens.profilePrivacyData"] = "Privacy & gegevens"
OUT["mobile.screens.profileSubscriptionTitle"] = "Abonnement"
OUT["mobile.screens.profileVersionLine"] = "AQWELIA Pro · v1.0.0-mobile"

# --- modules.* (23 keys) ---
OUT["modules.assistant.aqweliaAssistant"] = "AQWELIA-assistent"
OUT["modules.dashboard.later"] = "Later"
OUT["modules.dashboard.weatherIn"] = "In {location}"
OUT["modules.guides.level.beginner"] = "Beginner"
OUT["modules.guides.level.expert"] = "Expert"
OUT["modules.guides.min"] = "min"
OUT["modules.guides.premiumBadge"] = "PREMIUM"
OUT["modules.guides.tipLabel"] = "Tip:"
OUT["modules.maintenance.equipmentTypes.filter"] = "Filter"
OUT["modules.maintenance.equipmentTypes.robot"] = "Robot"
OUT["modules.maintenance.equipmentTypes.skimmer"] = "Skimmer"
OUT["modules.maintenance.labels.model"] = "Model"
OUT["modules.maintenance.labels.status"] = "Status"
OUT["modules.maintenance.labels.type"] = "Type"
OUT["modules.maintenance.productCategories.flocculant"] = "Flocculant"
OUT["modules.maintenance.productCategories.ph_minus"] = "pH-"
OUT["modules.maintenance.productCategories.ph_plus"] = "pH+"
OUT["modules.reminders.filterLabel"] = "Filter:"
OUT["modules.reminders.priority.low"] = "Later"
OUT["modules.reminders.season.winter"] = "winter"
OUT["modules.reminders.typeLabel"] = "Type"
OUT["modules.waterTest.filtration"] = "Filtr."
OUT["modules.waterTest.status"] = "Status"

# --- nav.* (8 keys) ---
OUT["nav.online"] = "AI online"
OUT["nav.premium"] = "AQWELIA Premium"
OUT["nav.pro"] = "Pro"
OUT["nav.shortIA"] = "AI"
OUT["nav.shortPlan"] = "Abonnement"
OUT["nav.shortPremium"] = "Premium"
OUT["nav.shortPremiumBadge"] = "PREMIUM"
OUT["nav.shortWater"] = "Water"

# --- onboarding.* (10 keys) ---
OUT["onboarding.filter"] = "Filter"
OUT["onboarding.spa"] = "Spa"
OUT["onboarding.spaUsageHighDesc"] = "5+/week"
OUT["onboarding.spaUsageLowDesc"] = "1-2x/week"
OUT["onboarding.spaUsageMediumDesc"] = "3-4x/week"
OUT["onboarding.surfaceLiner"] = "Liner"
OUT["onboarding.treatmentUV"] = "UV"
OUT["onboarding.unitGal"] = "gallons"
OUT["onboarding.unitM3"] = "m³ (liters ÷ 1000)"
OUT["onboarding.volume"] = "Volume"

# --- plans.* (38 keys) ---
OUT["plans.daysShort"] = "{n} d"
OUT["plans.expert.features.accountingExport"] = "Boekhoudexport"
OUT["plans.expert.features.advancedTechNotes"] = "Geavanceerde technische notities"
OUT["plans.expert.features.allPremium"] = "Alles uit Premium"
OUT["plans.expert.features.apiIntegrations"] = "API + integraties"
OUT["plans.expert.features.multiClients"] = "Onbeperkt multi-klant"
OUT["plans.expert.features.photosBeforeAfter"] = "Foto's voor/na"
OUT["plans.expert.features.quotesVisits"] = "Offertes en bezoekplanning"
OUT["plans.expert.name"] = "Expert"
OUT["plans.free.features.1pool"] = "1 zwembad"
OUT["plans.free.features.2scans"] = "2 fotoscans / maand"
OUT["plans.free.features.5guides"] = "5 basisgidsen"
OUT["plans.free.features.clearWaterIndex"] = "Helderwaterindex + zwemveiligheid"
OUT["plans.free.features.history14"] = "Geschiedenis 14 dagen"
OUT["plans.free.features.simpleWeather"] = "Eenvoudig weer"
OUT["plans.free.features.unlimitedManualTests"] = "Onbeperkte watertests (handmatig)"
OUT["plans.gates.guides_premium"] = "Premium-gidsen zijn voorbehouden aan betaalde abonnementen."
OUT["plans.gates.history_extended"] = "Uitgebreide geschiedenis is voorbehouden aan betaalde abonnementen."
OUT["plans.gates.multi_pool"] = "Multi-zwembad is voorbehouden aan Premium en Expert."
OUT["plans.gates.pdf_report"] = "PDF-rapport is voorbehouden aan Premium en Expert."
OUT["plans.gates.photo_scan_limit"] = "Limiet van {n} scans/maand bereikt."
OUT["plans.gates.pro_mode"] = "Pro-modus is voorbehouden aan Premium en Expert."
OUT["plans.gates.smart_reminders"] = "Slimme herinneringen zijn voorbehouden aan betaalde abonnementen."
OUT["plans.gates.spa_support"] = "Spa-support is voorbehouden aan het Premium-abonnement."
OUT["plans.gates.weather_advanced"] = "Geavanceerd weer is voorbehouden aan betaalde abonnementen."
OUT["plans.offline"] = "Offline"
OUT["plans.premium.features.3pools"] = "3 zwembaden"
OUT["plans.premium.features.advancedWeather"] = "Geavanceerd weer + meldingen"
OUT["plans.premium.features.allGuidesVideos"] = "Alle gidsen + video's"
OUT["plans.premium.features.pdfReport"] = "Deelbaar PDF-rapport"
OUT["plans.premium.features.prioritySupport"] = "Prioritaire support"
OUT["plans.premium.features.proMode"] = "Pro-modus (geavanceerde LSI)"
OUT["plans.premium.features.smartReminders"] = "Slimme herinneringen"
OUT["plans.premium.features.spaSupport"] = "Spa en heet water (broom, actief zuurstof)"
OUT["plans.premium.features.unlimitedHistory"] = "Onbeperkte geschiedenis"
OUT["plans.premium.features.unlimitedScans"] = "Onbeperkte fotoscans"
OUT["plans.premium.name"] = "Premium"
OUT["plans.premiumLabel"] = "AQWELIA Premium"

# --- reminders.* (38 keys) ---
OUT["reminders.cell_clean.action"] = "Demonteer de cel, week 10-15 min in een verdunde zuuroplossing, spoel na."
OUT["reminders.cell_clean.detail"] = "De cel zet zich in de loop der tijd vast met kalk. Zure reiniging elke 3-6 maanden."
OUT["reminders.cell_clean.title"] = "Reiniging electrolyzer-cel"
OUT["reminders.equipment_overdue.action"] = "Plan onderhoud voor deze apparatuur."
OUT["reminders.equipment_overdue.detail"] = "Onderhoud {days} dagen te laat."
OUT["reminders.equipment_overdue.title"] = "Onderhoud {type}"
OUT["reminders.filter_clean.actionCartridge"] = "Verwijder en spoel de cartridge."
OUT["reminders.filter_clean.actionSand"] = "Voer een backwash (tegenspoeling) uit."
OUT["reminders.filter_clean.detailCartridge"] = "Cartridgespoeling aanbevolen."
OUT["reminders.filter_clean.detailGeneric"] = "Filtercontrole aanbevolen."
OUT["reminders.filter_clean.detailSand"] = "Backwash van het zandfilter aanbevolen."
OUT["reminders.filter_clean.title"] = "Reiniging van het filter"
OUT["reminders.low_product.action"] = "Denk eraan om opnieuw te kopen voordat u zonder zit."
OUT["reminders.low_product.detail"] = "Er is nog weinig van dit product over."
OUT["reminders.low_product.title"] = "Lage voorraad: {name}"
OUT["reminders.retest_product.action"] = "Voer binnen enkele uren opnieuw een pH- + chloortest uit."
OUT["reminders.retest_product.detail"] = "U heeft onlangs een product toegevoegd. Controleer het effect."
OUT["reminders.retest_product.title"] = "Opnieuw testen na behandeling"
OUT["reminders.skimmer_clean.action"] = "Maak het skimmermandje en het pompmandje leeg."
OUT["reminders.skimmer_clean.detail"] = "Vuil, bladeren, insecten regelmatig verwijderen."
OUT["reminders.skimmer_clean.title"] = "Skimmer en mandje controleren"
OUT["reminders.startup.action"] = "Volg de gids voor seizoensstart: reinigen, behandeling, filtratie."
OUT["reminders.startup.detail"] = "De lente komt eraan: bereid het zwembad voor op het seizoen."
OUT["reminders.startup.title"] = "Seizoensstart"
OUT["reminders.test_first.action"] = "Voer uw eerste test in (minstens pH)."
OUT["reminders.test_first.detail"] = "Geen test geregistreerd. Activeer de opvolging."
OUT["reminders.test_first.title"] = "Eerste watertest"
OUT["reminders.test_overdue.action"] = "Voer een volledige test uit: pH + chloor + TAC."
OUT["reminders.test_overdue.detail"] = "Laatste test {days} dagen geleden. De waterkwaliteit verandert snel."
OUT["reminders.test_overdue.title"] = "Watertest opnieuw uitvoeren"
OUT["reminders.test_soon.action"] = "Controleer pH en vrij chloor."
OUT["reminders.test_soon.detail"] = "Laatste test {days} dagen geleden."
OUT["reminders.test_soon.title"] = "Routinetest"
OUT["reminders.winterize.action"] = "Volg de gids voor wintervoorbereiding: koud water, winterproducten, afdekking."
OUT["reminders.winterize.detail"] = "De herfst is er: anticipeer op de wintervoorbereiding."
OUT["reminders.winterize.title"] = "Bereid de wintervoorbereiding voor"
OUT["reminders.wx_test.action"] = "Test pH en chloor."
OUT["reminders.wx_test.title"] = "Test aanbevolen (weer)"

# --- settings.* (5 keys) ---
OUT["settings.deleteFailedDesc"] = "Verwijdering mislukt"
OUT["settings.exportFailedDesc"] = "Export mislukt"
OUT["settings.planExpert"] = "Expert"
OUT["settings.planPremium"] = "Premium"
OUT["settings.unitsVolume"] = "Volume"

# --- spaData.* (18 keys) ---
OUT["spaData.drainage_reason_intensive"] = "Intensief gebruik vastgesteld — verversing aanbevolen om de {months} maanden om verzadiging door producten te voorkomen."
OUT["spaData.drainage_reason_standard"] = "Verversing aanbevolen om de {months} maanden (goedkoper dan overbehandelen)."
OUT["spaData.freq.config"] = "Configuratie"
OUT["spaData.freq.daily"] = "Dagelijks"
OUT["spaData.freq.every_3_4_months"] = "Elke 3-4 maanden"
OUT["spaData.freq.per_drain"] = "Bij elke verversing"
OUT["spaData.freq.per_usage"] = "Per gebruik"
OUT["spaData.freq.weekly"] = "Wekelijks"
OUT["spaData.rec_chlorine_evaporates"] = "⚠️ Chloor verdampt snel in heet water. Schakel over op broom voor meer efficiëntie."
OUT["spaData.rec_cover_after_use"] = "Dek de spa af na elk gebruik om verdamping en fotosynthese te voorkomen."
OUT["spaData.rec_drain_economic"] = "Ververs om de 3-4 maanden — dat is goedkoper dan overbehandelen."
OUT["spaData.rec_temp_critical_health"] = "🔴 Kritieke temperatuur (>38 °C) — gezondheidsrisico. Verlaag de temperatuur."
OUT["spaData.rec_temp_high_chlorine_warning"] = "⚠️ Hoge temperatuur — chloor wordt NIET aanbevolen. Gebruik broom."
OUT["spaData.rec_temp_high_session_limit"] = "Houd de temperatuur in de gaten: boven 38 °C, beperk sessies tot 15-20 min."
OUT["spaData.seats_label"] = "Aantal zitplaatsen"
OUT["spaData.usage_intensive"] = "Intensief (5+/week)"
OUT["spaData.usage_occasional"] = "Occasioneel (1-2x/week)"
OUT["spaData.usage_regular"] = "Regelmatig (3-4x/week)"

# --- weather.* (40 keys) ---
OUT["weather.alerts.frost_risk.action"] = "Bescherm de technische ruimte. Laat de filtratie 's nachts draaien om vorst te voorkomen. Maak winterklaar indien nog niet gedaan."
OUT["weather.alerts.frost_risk.message"] = "Negatieve temperatuur voorspeld. Risico voor apparatuur en leidingen."
OUT["weather.alerts.frost_risk.title"] = "Vorstgevaar"
OUT["weather.alerts.frost_risk.when"] = "Vannacht"
OUT["weather.alerts.heat_extreme.action"] = "Verhoog de filtratie met 2 u/dag. Controleer elke ochtend het chloor. Overweeg preventief anti-algen."
OUT["weather.alerts.heat_extreme.message"] = "{temp} °C voorspeld. Zeer warm water = chloor sneller verbruikt + algengroei."
OUT["weather.alerts.heat_extreme.title"] = "Hittegolf verwacht"
OUT["weather.alerts.heat_extreme.when"] = "Vanaf nu en tijdens de hittegolf"
OUT["weather.alerts.heat_high.action"] = "Verhoog de filtratie met 1 u/dag en test morgen het chloor."
OUT["weather.alerts.heat_high.message"] = "{temp} °C voorspeld. Waarschijnlijk oververbruik van chloor."
OUT["weather.alerts.heat_high.title"] = "Hoge hitte verwacht"
OUT["weather.alerts.heat_high.when"] = "Morgenochtend"
OUT["weather.alerts.heavy_rain.action"] = "Na de regen: controleer pH en chloor, maak de skimmer en het pompmandje schoon."
OUT["weather.alerts.heavy_rain.message"] = "Regen verdunt de producten, verlaagt de pH en brengt vuil mee."
OUT["weather.alerts.heavy_rain.title"] = "Zware regenval verwacht"
OUT["weather.alerts.heavy_rain.when"] = "Na de regen"
OUT["weather.alerts.storm_soon.action"] = "Controleer vanavond het vrij chloor vóór het onweer. Verhoog morgen de filtratie."
OUT["weather.alerts.storm_soon.message"] = "{percent} % kans op onweer. Onweer verdunt chloor en verhoogt de pH."
OUT["weather.alerts.storm_soon.title"] = "Onweer morgen verwacht"
OUT["weather.alerts.storm_soon.when"] = "Vanavond vóór 20 u"
OUT["weather.alerts.uv_high.action"] = "Controleer uw stabilisator (CYA) en het vrij chloor."
OUT["weather.alerts.uv_high.message"] = "Zonlicht breekt niet-gestabiliseerd chloor sneller af."
OUT["weather.alerts.uv_high.title"] = "Zeer hoge UV"
OUT["weather.alerts.uv_high.when"] = "Deze week"
OUT["weather.alerts.wind_strong.action"] = "Controleer de skimmer en het pompmandje. Reinig de waterlijn."
OUT["weather.alerts.wind_strong.message"] = "{wind} km/h. Vuil, bladeren, stof in het zwembad."
OUT["weather.alerts.wind_strong.title"] = "Sterke wind verwacht"
OUT["weather.alerts.wind_strong.when"] = "Na de wind"
OUT["weather.filtration.reason"] = "Regel: de helft van de watertemperatuur ({temp} °C) aan filtratie-uren."
OUT["weather.filtration.scheduleDiurnal"] = "Dagfiltratie aanbevolen."
OUT["weather.filtration.scheduleNocturnal"] = "Geef de voorkeur aan nachtfiltratie (minder verdamping, betere chloorefficiëntie)."
OUT["weather.summary.calm"] = "Mild weer in {location}. Geen specifieke waarschuwing. Filter {hours} u/dag."
OUT["weather.summary.withAlerts"] = "{count} weeralarm(en): {titles}. Volg de aanbevolen acties."
OUT["weather.testReason.after_rain"] = "pH- + chloortest aanbevolen na de regen."
OUT["weather.testReason.before_storm"] = "Test aanbevolen vóór het morgen verwachte onweer."
OUT["weather.testReason.during_heatwave"] = "Dagelijkse test aanbevolen tijdens de hittegolf."
OUT["weather.testReason.routine"] = "Laatste test {days} dagen geleden. Routinetest aanbevolen."
OUT["weather.testReason.urgent"] = "Laatste test {days} dagen geleden: dringende test aanbevolen."
OUT["weather.uvShort"] = "UV"
OUT["weather.wind"] = "Wind"


def main():
    src = json.load(open('/home/z/my-project/.tmp/worksheets/nl-part2.json'))
    src_keys = set(src.keys())
    out_keys = set(OUT.keys())
    missing = src_keys - out_keys
    extra = out_keys - src_keys
    print(f"src={len(src_keys)} out={len(out_keys)} missing={len(missing)} extra={len(extra)}")
    if missing:
        print("MISSING:", sorted(missing)[:20])
    if extra:
        print("EXTRA:", sorted(extra)[:20])
    if missing or extra:
        return 1
    # Write file preserving worksheet order
    ordered = {k: OUT[k] for k in src.keys()}
    with open('/home/z/my-project/.tmp/translated/nl-part2.json', 'w', encoding='utf-8') as f:
        json.dump(ordered, f, ensure_ascii=False, indent=2)
        f.write('\n')
    print(f"wrote {len(ordered)} keys to /home/z/my-project/.tmp/translated/nl-part2.json")
    return 0


if __name__ == '__main__':
    exit(main())
