#!/usr/bin/env python3
"""Build /home/z/my-project/.tmp/translated/de-part2.json — German translations for de-part2 worksheet (502 keys)."""
import json
import os

# German translations for AQWELIA i18n keys (part 2).
# Source: /home/z/my-project/.tmp/worksheets/de-part2.json (FR primary, EN reference)
# Output: /home/z/my-project/.tmp/translated/de-part2.json
# Conventions:
#  - Formal "Sie" form for legal text (legal.*).
#  - Nouns capitalized; natural fluent German (not word-for-word).
#  - "pool" = "Pool", "spa" = "Spa", "chlorine" = "Chlor", "pH" stays "pH",
#    "TAC" kept (per task acronym list), "CYA"/"TH" kept.
#  - Brand names AQWELIA / AquaMind / AquaMind AI never translated.
#  - Acronyms pH/TAC/CYA/TH/OK/TDS/ORP/ppm kept.
#  - Units ml/L/kg/g/°C/°F/%/kWh/mg/L kept.
#  - ICU params {word} preserved verbatim.
#  - Rich-text tags <bold>/<link>/<alink>/<link2> preserved with translated inner text.
#  - "Term": definition pattern preserved with straight double quotes.

T = {}

# ============================================================
# guidesData.* (115 keys)
# ============================================================
T['guidesData.reminder_skimmer'] = 'Skimmer und Korb prüfen'
T['guidesData.reminder_skimmer_action'] = 'Leeren Sie den Skimmerkorb und den Pumpenkorb.'
T['guidesData.reminder_skimmer_check_action'] = 'Leeren Sie den Skimmerkorb und den Pumpenkorb.'
T['guidesData.reminder_skimmer_check_detail'] = 'Schmutz, Blätter und Insekten regelmäßig entfernen.'
T['guidesData.reminder_skimmer_check_title'] = 'Skimmer und Korb prüfen'
T['guidesData.reminder_skimmer_desc'] = 'Schmutz, Blätter und Insekten regelmäßig entfernen.'
T['guidesData.reminder_test_water_action'] = 'Führen Sie einen vollständigen Test durch (pH, Chlor, TAC).'
T['guidesData.reminder_test_water_detail'] = 'Es ist Zeit, Ihr Wasser zu testen.'
T['guidesData.reminder_test_water_title'] = 'Wassertest'
T['guidesData.reminder_winterize_action'] = 'Aktion für Überwinterung'
T['guidesData.reminder_winterize_detail'] = 'Detail für Überwinterung'
T['guidesData.reminder_winterize_title'] = 'Überwinterung'

T['guidesData.salt-system-basics.steps.1.detail'] = 'Salz (NaCl) wird in situ zu aktivem Chlor elektrolysiert. Keine Chlorlagerung, weicheres Wasser.'
T['guidesData.salt-system-basics.steps.1.title'] = 'Das Prinzip'
T['guidesData.salt-system-basics.steps.2.detail'] = 'Je nach Modell: im Allgemeinen 3-7 g/L. Prüfen Sie die Anleitung. Zu niedrig = keine Produktion; zu hoch = Überverbrauch.'
T['guidesData.salt-system-basics.steps.2.title'] = 'Erforderlicher Salzgehalt'
T['guidesData.salt-system-basics.steps.3.detail'] = 'Ohne Stabilisator wird das produzierte Chlor durch die Sonne in 2 Std. zerstört.'
T['guidesData.salt-system-basics.steps.3.title'] = 'Stabilisator (CYA) unerlässlich'
T['guidesData.salt-system-basics.steps.4.detail'] = 'Der Elektrolyseur lässt den pH-Wert steigen. Häufige Regulierung erforderlich.'
T['guidesData.salt-system-basics.steps.4.title'] = 'Den pH-Wert überwachen'
T['guidesData.salt-system-basics.steps.5.detail'] = 'In kaltem Wasser (< 15 °C) sinkt die Produktion. Im Winter besteht kein Anlass zur Sorge.'
T['guidesData.salt-system-basics.steps.5.title'] = 'Produktion nach Temperatur'
T['guidesData.salt-system-basics.steps.6.detail'] = 'Säurereinigung alle 3-6 Monate je nach Wasserhärte.'
T['guidesData.salt-system-basics.steps.6.title'] = 'Zellenwartung'
T['guidesData.salt-system-basics.summary'] = 'Prinzip, Salzgehalt, Produktion, laufende Wartung.'
T['guidesData.salt-system-basics.title'] = 'Salzelektrolyse verstehen'

T['guidesData.startup.steps.1.detail'] = 'Angesammelte Blätter und Schmutz entfernen.'
T['guidesData.startup.steps.1.title'] = 'Abdeckung entfernen und reinigen'
T['guidesData.startup.steps.2.detail'] = 'Wasserstand wieder auffüllen.'
T['guidesData.startup.steps.2.title'] = 'Bei niedrigem Wasserstand nachfüllen'
T['guidesData.startup.steps.3.detail'] = 'Filter prüfen (bei Bedarf zurückspülen).'
T['guidesData.startup.steps.3.title'] = 'Filtration starten'
T['guidesData.startup.steps.4.detail'] = 'pH, Chlor, TAC, Stabilisator.'
T['guidesData.startup.steps.4.title'] = 'Wasser testen'
T['guidesData.startup.steps.5.detail'] = 'TAC → pH → Chlor. Keine Eile.'
T['guidesData.startup.steps.5.title'] = 'Schrittweise ausbalancieren'
T['guidesData.startup.steps.6.detail'] = 'Um auf einer gesunden Basis zu starten.'
T['guidesData.startup.steps.6.title'] = 'Eine Stoßbehandlung durchführen'
T['guidesData.startup.steps.7.detail'] = 'Pumpe, Elektrolyseur, Dichtungen, Manometer.'
T['guidesData.startup.steps.7.title'] = 'Ausrüstung prüfen'
T['guidesData.startup.summary'] = 'Den Pool nach dem Winter schonend aus dem Winterschlaf holen.'
T['guidesData.startup.title'] = 'Frühjahrsinbetriebnahme'

T['guidesData.swim-safety.steps.1.detail'] = 'Außerhalb dieses Bereichs: mögliche Reizungen.'
T['guidesData.swim-safety.steps.1.title'] = 'pH zwischen 7,0 und 7,6'
T['guidesData.swim-safety.steps.2.detail'] = 'Weniger = unzureichende Desinfektion. Mehr = Reizung.'
T['guidesData.swim-safety.steps.2.title'] = 'Freies Chlor zwischen 1 und 3 mg/L'
T['guidesData.swim-safety.steps.3.detail'] = 'Darüber: starker Geruch, brennende Augen.'
T['guidesData.swim-safety.steps.3.title'] = 'Gebundenes Chlor < 0,4 mg/L'
T['guidesData.swim-safety.steps.4.detail'] = '2 Std. nach pH, 8 Std. nach Stoßchlorung.'
T['guidesData.swim-safety.steps.4.title'] = 'Wartezeiten nach der Behandlung einhalten'
T['guidesData.swim-safety.steps.5.detail'] = 'Lieber auf einen Test warten als in zweifelhaftes Wasser gehen.'
T['guidesData.swim-safety.steps.5.title'] = 'Im Zweifel: nicht baden'
T['guidesData.swim-safety.summary'] = 'Sicherheitskriterien für risikofreies Baden.'
T['guidesData.swim-safety.title'] = 'Badesicherheit: Wann darf man baden?'

T['guidesData.tac-control.steps.1.detail'] = 'Der TAC (Gesamtalkalität) stabilisiert den pH-Wert. Ohne ihn springt der pH-Wert bei jeder Produktdosierung an.'
T['guidesData.tac-control.steps.1.title'] = 'Rolle des TAC'
T['guidesData.tac-control.steps.2.detail'] = 'Zielwert 100 mg/L.'
T['guidesData.tac-control.steps.2.title'] = 'Idealer Bereich 80-120 mg/L'
T['guidesData.tac-control.steps.3.detail'] = 'Den TAC immer zuerst ausbalancieren, sonst hält der pH-Wert nicht.'
T['guidesData.tac-control.steps.3.title'] = 'VOR dem pH-Wert anpassen'
T['guidesData.tac-control.steps.4.detail'] = 'Verdünnen, verteilen, 3 Std. filtrieren.'
T['guidesData.tac-control.steps.4.title'] = 'Zum Anheben: Natriumhydrogencarbonat'
T['guidesData.tac-control.steps.5.detail'] = 'Komplexer, langsam mit einem pH-Minus durchführen.'
T['guidesData.tac-control.steps.5.title'] = 'Zum Senken: Säure'
T['guidesData.tac-control.summary'] = 'Der TAC ist der Puffer des pH-Werts. Ohne einen guten TAC wird der pH-Wert instabil.'
T['guidesData.tac-control.title'] = 'Alkalität (TAC) verstehen'

T['guidesData.tag_algues'] = 'Algen'
T['guidesData.tag_backwash'] = 'Rückspülen'
T['guidesData.tag_cartouche'] = 'Patrone'
T['guidesData.tag_chloramines'] = 'Chloramine'
T['guidesData.tag_chlore'] = 'Chlor'
T['guidesData.tag_choc'] = 'Stoß'
T['guidesData.tag_debutant'] = 'Anfänger'
T['guidesData.tag_electrolyseur'] = 'Elektrolyseur'
T['guidesData.tag_filtration'] = 'Filtration'
T['guidesData.tag_filtre'] = 'Filter'
T['guidesData.tag_floculant'] = 'Flockungsmittel'
T['guidesData.tag_odeur'] = 'Geruch'
T['guidesData.tag_securite'] = 'Sicherheit'
T['guidesData.tag_sel'] = 'Salz'
T['guidesData.tag_trouble'] = 'trüb'
T['guidesData.tag_vert'] = 'grün'
T['guidesData.tag_yeux'] = 'Augen'

T['guidesData.vacation-mode.steps.1.detail'] = 'Vor der Abreise alles ausbalancieren: pH, Chlor, TAC.'
T['guidesData.vacation-mode.steps.1.title'] = 'Einen vollständigen Test durchführen'
T['guidesData.vacation-mode.steps.2.detail'] = 'Tiefgehend desinfizieren.'
T['guidesData.vacation-mode.steps.2.title'] = 'Am Vorabend Stoßchlor'
T['guidesData.vacation-mode.steps.3.detail'] = 'Für eine Abwesenheit < 1 Woche.'
T['guidesData.vacation-mode.steps.3.title'] = 'Langsamchlor-Spender befüllen'
T['guidesData.vacation-mode.steps.4.detail'] = 'Mindestens 4-6 Std./Tag, vorzugsweise nachts.'
T['guidesData.vacation-mode.steps.4.title'] = 'Filtrations-Zeitschaltuhr einstellen'
T['guidesData.vacation-mode.steps.5.detail'] = 'Plane oder Abdeckung: begrenzt Schmutz und Verdunstung.'
T['guidesData.vacation-mode.steps.5.title'] = 'Pool abdecken'
T['guidesData.vacation-mode.steps.6.detail'] = 'Kontrollieren lassen oder einen Roboter installieren.'
T['guidesData.vacation-mode.steps.6.title'] = 'Bei längerer Abwesenheit: Nachbar oder Roboter'
T['guidesData.vacation-mode.steps.7.detail'] = 'Im Sommer reicht reduzierte Filtration. Im Winter vollständige Überwinterung.'
T['guidesData.vacation-mode.steps.7.title'] = 'Je nach Saison: aktive oder passive Überwinterung'
T['guidesData.vacation-mode.summary'] = 'Den Pool auf eine Abwesenheit von mehreren Tagen/Wochen vorbereiten.'
T['guidesData.vacation-mode.title'] = 'Vor dem Urlaub'

T['guidesData.winterization.steps.1.detail'] = 'Aktiv: reduzierte Filtration. Passiv: kompletter Stillstand. Abhängig vom Klima.'
T['guidesData.winterization.steps.1.title'] = 'Aktive oder passive Überwinterung wählen'
T['guidesData.winterization.steps.2.detail'] = 'Wasser, Wände, Boden, Filter, Wasserlinie.'
T['guidesData.winterization.steps.2.title'] = 'Tiefenreinigung'
T['guidesData.winterization.steps.3.detail'] = 'Überwinterungsprodukt, algae- und kalkabweisend.'
T['guidesData.winterization.steps.3.title'] = 'Eine Winterbehandlung durchführen'
T['guidesData.winterization.steps.4.detail'] = '10-15 cm unter den Düsen für passiv.'
T['guidesData.winterization.steps.4.title'] = 'Wasserstand absenken'
T['guidesData.winterization.steps.5.detail'] = 'Vor Frost schützen.'
T['guidesData.winterization.steps.5.title'] = 'Sensible Leitungen entleeren'
T['guidesData.winterization.steps.6.detail'] = 'Winterplane oder Abdeckung.'
T['guidesData.winterization.steps.6.title'] = 'Pool abdecken'
T['guidesData.winterization.steps.7.detail'] = 'Besonders während der Frostperioden.'
T['guidesData.winterization.steps.7.title'] = 'Aktive Überwinterung: Filtration 2-3 Std./Tag'
T['guidesData.winterization.summary'] = 'Den Pool sicher überwintern, ohne die Ausrüstung zu beschädigen.'
T['guidesData.winterization.title'] = 'Den Pool überwintern'

# ============================================================
# landing.* (13 keys)
# ============================================================
T['landing.faqEyebrow'] = '12 — FAQ'
T['landing.footerBlog'] = 'Blog'
T['landing.footerProductFaq'] = 'FAQ'
T['landing.footerSupport'] = 'Support'
T['landing.footerVersion'] = 'v2.0 Copilot'
T['landing.heroPhoneChlorine'] = 'Chlor'
T['landing.navFaq'] = 'FAQ'
T['landing.navProblem'] = 'Das Problem'
T['landing.savingsBar1'] = 'AQWELIA Premium'
T['landing.spaBrandCategoryEco'] = 'Eco'
T['landing.spaBrandCategoryPremium'] = 'Premium'
T['landing.storyAquaWord'] = '(aqua)'
T['landing.variationsFactor6Title'] = 'UV'

# ============================================================
# legal.* (175 keys) — formal German (Sie-form)
# ============================================================
T['legal.backHome'] = 'Zurück zur Startseite'

T['legal.cgu.article1Body1'] = 'Diese Allgemeinen Nutzungsbedingungen ("<bold>AGB</bold>") definieren die Modalitäten und Bedingungen für den Zugang und die Nutzung der Anwendung AQWELIA ("<bold>der Dienst</bold>"), herausgegeben von der Gesellschaft AQWELIA, sowie die Rechte und Pflichten der Parteien in diesem Rahmen.'
T['legal.cgu.article1Body2'] = 'Die Nutzung des Dienstes impliziert die volle und vollständige Akzeptanz dieser AGB. Wenn Sie mit einer dieser Bedingungen nicht einverstanden sind, dürfen Sie den Dienst nicht nutzen.'
T['legal.cgu.article1Title'] = 'Artikel 1 — Gegenstand'

T['legal.cgu.article2Item1'] = '"<bold>Nutzer</bold>": jede natürliche Person, die den Dienst nutzt.'
T['legal.cgu.article2Item2'] = '"<bold>Konto</bold>": persönlicher Bereich, der vom Nutzer für den Zugang zum Dienst erstellt wird.'
T['legal.cgu.article2Item3'] = '"<bold>Daten</bold>": Informationen, die vom Nutzer eingegeben werden (Messwerte, Fotos, Poolprofil usw.).'
T['legal.cgu.article2Item4'] = '"<bold>Plan</bold>": Abonnementformel (Free, Premium oder Expert), die der Nutzer abonniert.'
T['legal.cgu.article2Item5'] = '"<bold>Inhalt</bold>": Empfehlungen, Aktionspläne, Analysen, Leitfäden und Texte, die vom Dienst generiert werden.'
T['legal.cgu.article2Title'] = 'Artikel 2 — Definitionen'

T['legal.cgu.article3Body1'] = 'AQWELIA ist ein intelligenter Copilot für die Poolpflege. Der Dienst ermöglicht dem Nutzer:'
T['legal.cgu.article3Body2'] = 'Der Dienst wird zu Informationszwecken bereitgestellt und ersetzt nicht das Eingreifen eines qualifizierten Fachmanns (Poolspezialist, Händler, Rettungsschwimmer).'
T['legal.cgu.article3Item1'] = 'die Qualität seines Poolwassers zu überwachen und zu analysieren (pH, Chlor, TAC, TH usw.);'
T['legal.cgu.article3Item2'] = 'personalisierte Aktionspläne zu erhalten (Dosierungen, Filtration, Badefähigkeit);'
T['legal.cgu.article3Item3'] = 'Wasser und Ausrüstung visuell per Foto zu diagnostizieren;'
T['legal.cgu.article3Item4'] = 'einen KI-Assistenten zu allen Pflegethemen zu konsultieren;'
T['legal.cgu.article3Item5'] = 'intelligente Erinnerungen zu erhalten (Wetter, Ausrüstung, Produktbestände);'
T['legal.cgu.article3Item6'] = 'Leitfäden und pädagogische Ressourcen zu konsultieren.'
T['legal.cgu.article3Title'] = 'Artikel 3 — Beschreibung des Dienstes'

T['legal.cgu.article4Body1'] = 'Die Registrierung für den Dienst erfordert die Erstellung eines Kontos über eine gültige E-Mail-Adresse und ein Passwort. Der Nutzer verpflichtet sich, genaue Informationen bereitzustellen und diese aktuell zu halten.'
T['legal.cgu.article4Body2'] = 'Der Nutzer ist allein verantwortlich für die Vertraulichkeit seiner Zugangsdaten und jede Nutzung seines Kontos. Jede Aktivität, die von seinem Konto aus durchgeführt wird, gilt als vom Nutzer ausgeführt.'
T['legal.cgu.article4Body3'] = 'AQWELIA behält sich das Recht vor, ein Konto bei Nichteinhaltung dieser AGB oder bei betrügerischem Verhalten abzulehnen oder zu schließen.'
T['legal.cgu.article4Title'] = 'Artikel 4 — Registrierung und Konto'

T['legal.cgu.article5Body1'] = 'Der Nutzer verpflichtet sich zu:'
T['legal.cgu.article5Body2'] = 'Der Nutzer anerkennt, dass die vom Dienst bereitgestellten Empfehlungen indikativen Charakter haben und dass er allein für die Handlungen verantwortlich bleibt, die er an seinem Pool vornimmt.'
T['legal.cgu.article5Item1'] = 'den Dienst gemäß seinem Zweck und dem geltenden Recht zu nutzen;'
T['legal.cgu.article5Item2'] = 'nicht zu versuchen, den Dienst abzuwenden, zu deaktivieren oder die Sicherheit zu gefährden;'
T['legal.cgu.article5Item3'] = 'keinen Inhalt hochzuladen, der rechtswidrig, verleumderisch ist oder die Rechte Dritter verletzt;'
T['legal.cgu.article5Item4'] = 'die Anweisungen der Chemieprodukte zu beachten, die für die Pflege seines Pools verwendet werden.'
T['legal.cgu.article5Title'] = 'Artikel 5 — Nutzung des Dienstes'

T['legal.cgu.article6Body1'] = 'Der Dienst bietet drei Pläne:'
T['legal.cgu.article6Body2'] = 'Die Funktionen und Preise der einzelnen Pläne sind auf der Seite <link>Preise</link> aufgeführt. AQWELIA behält sich das Recht vor, diese Angebote jederzeit zu ändern, vorbehaltlich der Information der abonnierten Nutzer mindestens 30 Tage vor Inkrafttreten.'
T['legal.cgu.article6Item1'] = '<bold>Free</bold>: kostenlos, umfasst 1 Pool, grundlegende manuelle Messungen, begrenzter Assistent.'
T['legal.cgu.article6Item2'] = '<bold>Premium</bold>: bis zu 3 Pools, unbegrenzte Fotodiagnose, vollständiger KI-Assistent, Wetter-Erinnerungen, erweiterte Leitfäden.'
T['legal.cgu.article6Item3'] = '<bold>Expert</bold>: unbegrenzt (professionelle Poolspezialisten), Multi-Kunden, Exporte, Priority-Support.'
T['legal.cgu.article6Title'] = 'Artikel 6 — Abonnements'

T['legal.cgu.article7Body1'] = 'Die Zahlung für Premium- und Expert-Abonnements erfolgt über die verwendete Plattform:'
T['legal.cgu.article7Body2'] = 'Die Verlängerung erfolgt automatisch am Ende der Abonnementperiode, sofern sie nicht vom Nutzer in den Einstellungen seines Apple/Google-Kontos oder über das Stripe-Kundenportal deaktiviert wird.'
T['legal.cgu.article7Item1'] = '<bold>Web</bold>: über Stripe (Bankkarte, sichere Zahlung).'
T['legal.cgu.article7Item2'] = '<bold>iOS</bold>: über Apple In-App Purchase (von Apple verwaltet).'
T['legal.cgu.article7Item3'] = '<bold>Android</bold>: über Google Play Billing (von Google verwaltet).'
T['legal.cgu.article7Title'] = 'Artikel 7 — Zahlung'

T['legal.cgu.article8Body1'] = 'Der Nutzer kann sein Abonnement jederzeit über die Anwendung (Seite <link>Einstellungen</link>) oder über die Einstellungen des App Store / Google Play kündigen. Die Kündigung wird am Ende der laufenden Abrechnungsperiode wirksam.'
T['legal.cgu.article8Body2'] = 'AQWELIA behält sich das Recht vor, den Zugang zum Dienst bei Verstoß gegen die AGB nach vorheriger Benachrichtigung zu beenden oder auszusetzen, außer in Notfällen.'
T['legal.cgu.article8Title'] = 'Artikel 8 — Kündigung'

T['legal.cgu.article9Body1'] = 'Die Verarbeitung der personenbezogenen Daten des Nutzers unterliegt unserer <link>Datenschutzerklärung</link> gemäß der Datenschutz-Grundverordnung (DSGVO, EU 2016/679).'
T['legal.cgu.article9Body2'] = 'Der Nutzer hat das Recht auf Zugang, Berichtigung, Löschung, Übertragbarkeit und Widerspruch. Diese Rechte können über die Seite <link>Einstellungen</link> oder per E-Mail an <alink>privacy@aqwelia.app</alink> ausgeübt werden.'
T['legal.cgu.article9Title'] = 'Artikel 9 — Personenbezogene Daten (DSGVO)'

T['legal.cgu.article10Body1'] = 'AQWELIA unternimmt alles, um die Verfügbarkeit und Zuverlässigkeit des Dienstes sicherzustellen, kann aber nicht garantieren, dass dieser vollständig frei von Fehlern oder Unterbrechungen ist.'
T['legal.cgu.article10Body2'] = 'Da der Dienst nur zu Informationszwecken bereitgestellt wird, kann AQWELIA nicht für direkte oder indirekte Schäden haftbar gemacht werden, die aus der Anwendung der Empfehlungen entstehen (insbesondere: Sachschäden, Badeverluste, Beschädigung von Ausrüstung, chemische Reaktionen). Im Zweifelsfall sollte der Nutzer einen Fachmann konsultieren.'
T['legal.cgu.article10Title'] = 'Artikel 10 — Haftung'

T['legal.cgu.article11Body1'] = 'Alle Elemente des Dienstes (Marke, Logo, Texte, Algorithmen, Design, Leitfäden) sind Eigentum von AQWELIA oder deren Partnern. Jede Vervielfältigung, Wiedergabe oder Verbreitung, ganz oder teilweise, ohne vorherige schriftliche Genehmigung ist untersagt.'
T['legal.cgu.article11Body2'] = 'Die vom Nutzer eingegebenen Daten bleiben sein Eigentum. Der Nutzer räumt AQWELIA eine nicht-exklusive Lizenz zur Nutzung dieser Daten in dem Umfang ein, der für die Erbringung und Verbesserung des Dienstes erforderlich ist.'
T['legal.cgu.article11Title'] = 'Artikel 11 — Geistiges Eigentum'

T['legal.cgu.article12Body1'] = 'AQWELIA kann diese AGB jederzeit ändern. Die anwendbaren AGB sind diejenigen, die zum Zeitpunkt der Nutzung des Dienstes gelten. Wesentliche Änderungen werden per E-Mail oder über die Anwendung mindestens 30 Tage vor Inkrafttreten mitgeteilt.'
T['legal.cgu.article12Title'] = 'Artikel 12 — Änderungen der AGB'

T['legal.cgu.article13Body1'] = 'Diese AGB unterliegen französischem Recht. Im Falle eines Streits verpflichten sich die Parteien, vor jeder gerichtlichen Maßnahme eine gütliche Einigung zu suchen. Ohne Einigung sind die französischen Gerichte ausschließlich zuständig.'
T['legal.cgu.article13Title'] = 'Artikel 13 — Anwendbares Recht'

T['legal.cgu.contactBody1'] = 'Bei Fragen zu diesen AGB: <alink>legal@aqwelia.app</alink>'
T['legal.cgu.contactBody2'] = 'Bei Fragen zu Ihren Daten: <alink>privacy@aqwelia.app</alink>'
T['legal.cgu.contactBody3'] = 'Bei Support-Anfragen: <link>Support-Seite</link>.'
T['legal.cgu.contactTitle'] = 'Kontakt'
T['legal.cgu.eyebrow'] = 'Rechtliche Hinweise'
T['legal.cgu.metaDescription'] = 'Nutzungsbedingungen des Dienstes AQWELIA.'
T['legal.cgu.metaTitle'] = 'Nutzungsbedingungen — AQWELIA'
T['legal.cgu.title'] = 'Allgemeine Nutzungsbedingungen'

T['legal.lastUpdatedLabel'] = 'Zuletzt aktualisiert:'

T['legal.privacy.eyebrow'] = 'DSGVO'
T['legal.privacy.metaDescription'] = 'Datenschutzerklärung von AQWELIA (DSGVO).'
T['legal.privacy.metaTitle'] = 'Datenschutzerklärung — AQWELIA'

T['legal.privacy.section1Body1'] = 'Der Verantwortliche für die über die AQWELIA-Anwendung erhobenen personenbezogenen Daten ist die Gesellschaft <bold>AQWELIA</bold>, Herausgeberin des Dienstes.'
T['legal.privacy.section1Body2'] = 'Kontakt DSB: <alink>privacy@aqwelia.app</alink>'
T['legal.privacy.section1Title'] = '1. Verantwortlicher'

T['legal.privacy.section2Body1'] = 'Der Dienst erhebt die folgenden Datenkategorien:'
T['legal.privacy.section2Item1'] = '<bold>Konto-IDs</bold>: E-Mail-Adresse, Name (optional), Passwort (gehasht).'
T['legal.privacy.section2Item2'] = '<bold>Poolprofil</bold>: Volumen, Form, Oberfläche, Behandlung, Filter, Ausrichtung, Region.'
T['legal.privacy.section2Item3'] = '<bold>Wasserdaten</bold>: Messwerte (pH, Chlor, TAC, TH, CYA, Salz, Temperatur usw.), eingegeben oder importiert.'
T['legal.privacy.section2Item4'] = '<bold>Fotos</bold>: Bilder von Wasser, Wänden, Filter, Elektrolyseuren und Produkten, verwendet für die visuelle KI-Diagnose.'
T['legal.privacy.section2Item5'] = '<bold>Ausrüstung & Bestand</bold>: Marke, Modell, Wartungsdaten, Chemikalien auf Lager.'
T['legal.privacy.section2Item6'] = '<bold>Verlauf</bold>: Konversationen mit dem KI-Assistenten, generierte Aktionspläne, Fotodiagnosen.'
T['legal.privacy.section2Item7'] = '<bold>Abrechnungsdaten</bold>: abonnierter Plan, Zeitraum, Status (Zahlungsinformationen werden von Stripe, Apple oder Google verarbeitet — AQWELIA speichert keine Kartennummern).'
T['legal.privacy.section2Item8'] = '<bold>Nutzungsdaten</bold>: Analytics-Ereignisse (Aufruf von Leitfäden, Paywall-Öffnungen, Nutzungshäufigkeit).'
T['legal.privacy.section2Title'] = '2. Erhobene Daten'

T['legal.privacy.section3Body1'] = 'Die Daten werden für folgende Zwecke verarbeitet:'
T['legal.privacy.section3Item1'] = 'Betrieb des Dienstes (Generierung von Aktionsplänen, Dosierungsberechnungen, Wasserüberwachung);'
T['legal.privacy.section3Item2'] = 'Verbesserung der KI-Modelle (Fotodiagnose, Empfehlungen) — auf Basis vorheriger Anonymisierung, wenn möglich;'
T['legal.privacy.section3Item3'] = 'Abrechnung und Abonnementverwaltung;'
T['legal.privacy.section3Item4'] = 'Nutzer-Support;'
T['legal.privacy.section3Item5'] = 'Nutzungsanalyse und Verbesserung der Erfahrung;'
T['legal.privacy.section3Item6'] = 'Einhaltung rechtlicher und buchhalterischer Pflichten.'
T['legal.privacy.section3Title'] = '3. Zwecke'

T['legal.privacy.section4Body1'] = 'Gemäß Artikel 6 der DSGVO beruhen die Verarbeitungen auf folgenden Rechtsgrundlagen:'
T['legal.privacy.section4Body2'] = 'Der Nutzer kann seine Einwilligung jederzeit über die Seite <link>Einstellungen</link> widerrufen, ohne die Rechtmäßigkeit der vorherigen Verarbeitung zu beeinträchtigen.'
T['legal.privacy.section4Item1'] = '<bold>Vertragserfüllung</bold> (Art. 6.1.b): Bereitstellung des abonnierten Dienstes.'
T['legal.privacy.section4Item2'] = '<bold>Einwilligung</bold> (Art. 6.1.a): Fotos für die Diagnose, Benachrichtigungen, mögliche Marketing-Kommunikation.'
T['legal.privacy.section4Item3'] = '<bold>Berechtigtes Interesse</bold> (Art. 6.1.f): Verbesserung des Dienstes, Sicherheit, Betrugsvorbeugung.'
T['legal.privacy.section4Item4'] = '<bold>Rechtliche Verpflichtung</bold> (Art. 6.1.c): Aufbewahrung von Rechnungen und Buchungsbelegen.'
T['legal.privacy.section4Title'] = '4. Rechtsgrundlage'

T['legal.privacy.section5Item1'] = '<bold>Aktives Konto</bold>: Dauer der Nutzung des Dienstes.'
T['legal.privacy.section5Item2'] = '<bold>Pooldaten, Messungen, Fotos</bold>: so lange aufbewahrt, wie das Konto aktiv ist, plus 90 Tage nach Löschung (für mögliche Wiederherstellung), dann endgültig gelöscht.'
T['legal.privacy.section5Item3'] = '<bold>Rechnungen</bold>: 10 Jahre (gesetzliche Buchführungspflicht in Frankreich).'
T['legal.privacy.section5Item4'] = '<bold>Sicherheits-Logs</bold>: 12 Monate.'
T['legal.privacy.section5Item5'] = '<bold>Inaktives Konto</bold>: nach 24 Monaten ohne Anmeldung Benachrichtigung per E-Mail und anschließende Löschung des Kontos und seiner Daten.'
T['legal.privacy.section5Title'] = '5. Aufbewahrungsdauer'

T['legal.privacy.section6Body1'] = 'Die Daten sind für folgende Empfänger zugänglich:'
T['legal.privacy.section6Body2'] = 'AQWELIA verkauft niemals Ihre Daten an Dritte zu Marketingzwecken.'
T['legal.privacy.section6Item1'] = '<bold>AQWELIA</bold>: autorisiertes Personal (Ingenieure, Support) unter Verschwiegenheitsvereinbarung.'
T['legal.privacy.section6Item2'] = '<bold>Cloud-Host</bold>: Speicherung und Berechnung (EU-Standort).'
T['legal.privacy.section6Item3'] = '<bold>Stripe</bold>: Web-Zahlungsabwicklung (unterliegt eigener DSGVO).'
T['legal.privacy.section6Item4'] = '<bold>RevenueCat</bold>: einheitliche iOS/Android-Abonnementverwaltung.'
T['legal.privacy.section6Item5'] = '<bold>Apple / Google</bold>: In-App-Zahlungen (unterliegen eigenen Bedingungen).'
T['legal.privacy.section6Item6'] = '<bold>KI-Anbieter</bold>: für Fotodiagnose und den Assistenten — nur zwingend erforderliche Daten, ohne Speicherung über die Sitzung hinaus.'
T['legal.privacy.section6Title'] = '6. Empfänger'

T['legal.privacy.section7Body1'] = 'Das Haupt-Hosting befindet sich in der Europäischen Union. Etwaige Übermittlungen außerhalb der EU (z. B. an einen KI-Anbieter mit Sitz in den Vereinigten Staaten) werden durch die Standardvertragsklauseln der Europäischen Kommission (Beschluss 2021/914) geregelt und durch angemessene Garantien begleitet (Verschlüsselung, Minimierung, Pseudonymisierung).'
T['legal.privacy.section7Title'] = '7. Übermittlungen außerhalb der EU'

T['legal.privacy.section8Body1'] = 'Gemäß den Artikeln 15 bis 22 der DSGVO haben Sie folgende Rechte:'
T['legal.privacy.section8Body2'] = 'Diese Rechte können direkt über die Seite <link>Einstellungen</link> (JSON-Export, Kontolöschung) oder per E-Mail an <alink>privacy@aqwelia.app</alink> ausgeübt werden.'
T['legal.privacy.section8Body3'] = 'Sie können auch Beschwerde bei der CNIL (www.cnil.fr) oder der Aufsichtsbehörde Ihres Landes einlegen.'
T['legal.privacy.section8Item1'] = '<bold>Auskunftsrecht</bold>: eine Kopie Ihrer Daten erhalten.'
T['legal.privacy.section8Item2'] = '<bold>Recht auf Berichtigung</bold>: ungenaue Daten korrigieren.'
T['legal.privacy.section8Item3'] = '<bold>Recht auf Löschung</bold> ("Recht auf Vergessenwerden"): Ihr Konto und Ihre Daten löschen.'
T['legal.privacy.section8Item4'] = '<bold>Recht auf Übertragbarkeit</bold>: Ihre Daten in einem strukturierten und wiederverwendbaren Format erhalten.'
T['legal.privacy.section8Item5'] = '<bold>Widerspruchsrecht</bold>: eine auf berechtigtem Interesse beruhende Verarbeitung ablehnen.'
T['legal.privacy.section8Item6'] = '<bold>Recht auf Einschränkung</bold>: eine Verarbeitung vorübergehend einfrieren.'
T['legal.privacy.section8Item7'] = '<bold>Recht, Ihre Einwilligung jederzeit zu widerrufen</bold>.'
T['legal.privacy.section8Title'] = '8. Ihre Rechte'

T['legal.privacy.section9Body1'] = 'AQWELIA verwendet ein Minimum an Trackern, die für den Betrieb des Dienstes strikt erforderlich sind (Authentifizierungssitzung, Sprach- und Theme-Einstellungen). Es werden keine Werbe- oder Tracking-Cookies Dritter ohne Einwilligung gesetzt.'
T['legal.privacy.section9Body2'] = 'Die Einstellungen können über die Seite <link>Einstellungen</link> verwaltet werden.'
T['legal.privacy.section9Title'] = '9. Cookies und Tracker'

T['legal.privacy.section10Body1'] = 'AQWELIA implementiert angemessene technische und organisatorische Maßnahmen, um Ihre Daten zu schützen:'
T['legal.privacy.section10Body2'] = 'Im Falle einer Datenverletzung, die ein Risiko für Ihre Rechte und Freiheiten darstellen könnte, wird AQWELIA Sie unverzüglich gemäß Artikel 34 der DSGVO benachrichtigen.'
T['legal.privacy.section10Item1'] = 'Passwortverschlüsselung (scrypt, brute-force-resistenter Algorithmus);'
T['legal.privacy.section10Item2'] = 'Verschlüsselung der Daten bei der Übertragung (TLS 1.2+) und im Ruhezustand (Datenbankverschlüsselung);'
T['legal.privacy.section10Item3'] = 'Authentifizierung über signiertes JWT, begrenzte Lebensdauer (30 Tage);'
T['legal.privacy.section10Item4'] = 'eingeschränkter Zugriff auf personenbezogene Daten (Prinzip der geringsten Privilegierung);'
T['legal.privacy.section10Item5'] = 'verschlüsselte Backups und regelmäßige Penetrationstests.'
T['legal.privacy.section10Title'] = '10. Sicherheit'

T['legal.privacy.section11Body1'] = 'Bei Fragen zum Schutz Ihrer Daten kontaktieren Sie unseren DSB:'
T['legal.privacy.section11Body2'] = 'Siehe auch unsere <link>AGB</link> und unsere <link2>Support-Seite</link2>.'
T['legal.privacy.section11Title'] = '11. Kontakt DSB'

T['legal.privacy.title'] = 'Datenschutzerklärung'

T['legal.support.cardAssistantDesc'] = 'Für eine schnelle Frage zu Ihrem Pool befragen Sie den Assistenten direkt in der App.'
T['legal.support.cardAssistantLink'] = 'App öffnen'
T['legal.support.cardAssistantTitle'] = 'Integrierter KI-Assistent'
T['legal.support.cardBugDesc'] = 'Haben Sie ein unerwartetes Verhalten bemerkt? Beschreiben Sie es uns mit einem Screenshot, falls möglich.'
T['legal.support.cardBugLink'] = 'Per E-Mail melden'
T['legal.support.cardBugTitle'] = 'Einen Bug melden'
T['legal.support.cardFaqDesc'] = 'Antworten auf die häufigsten Fragen: Abonnements, Daten, Pool, Kompatibilität.'
T['legal.support.cardFaqLink'] = 'FAQ ansehen'
T['legal.support.cardFaqTitle'] = 'FAQ'
T['legal.support.cardFeatureDesc'] = 'Eine Idee, um AQWELIA zu verbessern? Wir lesen alle Vorschläge.'
T['legal.support.cardFeatureLink'] = 'Meine Idee teilen'
T['legal.support.cardFeatureSubject'] = 'Feature-Idee AQWELIA'
T['legal.support.cardFeatureTitle'] = 'Ein Feature anfragen'
T['legal.support.cardKbDesc'] = 'Detaillierte Leitfäden, Video-Tutorials und Hilfe-Artikel. Bald verfügbar.'
T['legal.support.cardKbLink'] = 'Bald verfügbar'
T['legal.support.cardKbTitle'] = 'Wissensdatenbank'
T['legal.support.cardLegalDesc'] = 'Bei DSGVO-, Datenschutz- oder AGB-Themen schreiben Sie an privacy@aqwelia.app.'
T['legal.support.cardLegalLink'] = 'Den DSB kontaktieren'
T['legal.support.cardLegalTitle'] = 'Rechtliche Fragen'
T['legal.support.emailDesc'] = 'Der beste Weg, uns zu erreichen. Antwort innerhalb von 48 Geschäftsstunden.'
T['legal.support.emailTitle'] = 'E-Mail'
T['legal.support.eyebrow'] = 'Hilfe & Support'
T['legal.support.metaDescription'] = 'AQWELIA-Support kontaktieren, FAQ, Bug melden, Feature anfragen.'
T['legal.support.metaTitle'] = 'Support — AQWELIA'
T['legal.support.resourcesCguLink'] = 'Nutzungsbedingungen'
T['legal.support.resourcesPrivacyLink'] = 'Datenschutzerklärung'
T['legal.support.resourcesSettingsLink'] = 'Kontoeinstellungen'
T['legal.support.resourcesTitle'] = 'Zugehörige Ressourcen'
T['legal.support.responseTimeExpert'] = '<bold>Expert-Plan</bold>: Antwort innerhalb von 24 Std., Priority-Support.'
T['legal.support.responseTimeFree'] = '<bold>Free-Plan</bold>: Antwort innerhalb von 72 Geschäftsstunden.'
T['legal.support.responseTimePremium'] = '<bold>Premium-Plan</bold>: Antwort innerhalb von 48 Geschäftsstunden.'
T['legal.support.responseTimeTitle'] = 'Antwortzeit'
T['legal.support.subtitle'] = 'Unser Team steht Ihnen zur Verfügung, um das Beste aus AQWELIA herauszuholen.'
T['legal.support.title'] = 'Support kontaktieren'

# ============================================================
# metadata.* (7 keys)
# ============================================================
T['metadata.layoutDescription'] = 'AQWELIA — die revolutionäre KI-gestützte Pool-Management-App: Experten-Assistent, visuelle Wasseranalyse, deterministischer Aktionsplan und mehr.'
T['metadata.layoutKeywordAI'] = 'KI'
T['metadata.layoutKeywordMaintenance'] = 'Wartung'
T['metadata.layoutKeywordPool'] = 'Pool'
T['metadata.layoutKeywordSmartAssistant'] = 'intelligenter Assistent'
T['metadata.layoutKeywordWaterQuality'] = 'Wasserqualität'
T['metadata.layoutTitle'] = 'AQWELIA — Intelligenter Copilot für den Pool'

# ============================================================
# mobile.screens.* (18 keys)
# ============================================================
T['mobile.screens.analysesAriaSubtabs'] = 'Analyse-Untertabs'
T['mobile.screens.analysesSubtabLogbook'] = 'Logbuch'
T['mobile.screens.analysesSubtabMesures'] = 'Messungen'
T['mobile.screens.analysesSubtabPhoto'] = 'Foto'
T['mobile.screens.maintenanceAriaSubtabs'] = 'Wartungs-Untertabs'
T['mobile.screens.maintenanceSubtabActions'] = 'Aktionen'
T['mobile.screens.profileAriaPoolProfile'] = 'Poolprofil'
T['mobile.screens.profileAriaSettings'] = 'Einstellungen'
T['mobile.screens.profileAriaSubscription'] = 'Abonnement'
T['mobile.screens.profileConfigureToStart'] = 'Konfigurieren Sie Ihren Pool, um zu beginnen'
T['mobile.screens.profileElectrolysisSalt'] = 'Salzelektrolyse'
T['mobile.screens.profileFaqContact'] = 'FAQ + Kontakt'
T['mobile.screens.profileHelpSupport'] = 'Hilfe & Support'
T['mobile.screens.profileNotifReminders'] = 'Benachrichtigungen & Erinnerungen'
T['mobile.screens.profilePoolNotConfigured'] = 'Pool nicht konfiguriert'
T['mobile.screens.profilePrivacyData'] = 'Datenschutz & Daten'
T['mobile.screens.profileSubscriptionTitle'] = 'Abonnement'
T['mobile.screens.profileVersionLine'] = 'AQWELIA Pro · v1.0.0-mobile'

# ============================================================
# modules.* (17 keys)
# ============================================================
T['modules.dashboard.inHours'] = 'in {hours} Std.'
T['modules.dashboard.labelTac'] = 'TAC'
T['modules.dashboard.labelTemp'] = 'Temp.'
T['modules.dashboard.weatherIn'] = 'In {location}'
T['modules.guides.premiumBadge'] = 'PREMIUM'
T['modules.healthLog.alkalinity'] = 'TAC'
T['modules.maintenance.equipmentTypes.filter'] = 'Filter'
T['modules.maintenance.equipmentTypes.skimmer'] = 'Skimmer'
T['modules.maintenance.labels.status'] = 'Status'
T['modules.maintenance.productCategories.alkalinity_plus'] = 'TAC+'
T['modules.maintenance.productCategories.ph_minus'] = 'pH-'
T['modules.maintenance.productCategories.ph_plus'] = 'pH+'
T['modules.reminders.detailLabel'] = 'Detail (optional)'
T['modules.reminders.filterLabel'] = 'Filter:'
T['modules.reminders.inHours'] = 'in {n} Std.'
T['modules.waterTest.filtration'] = 'Filtr.'
T['modules.waterTest.status'] = 'Status'

# ============================================================
# nav.* (6 keys)
# ============================================================
T['nav.analyses'] = 'Analysen'
T['nav.premium'] = 'AQWELIA Premium'
T['nav.pro'] = 'Pro'
T['nav.shortPlan'] = 'Plan'
T['nav.shortPremium'] = 'Premium'
T['nav.shortPremiumBadge'] = 'PREMIUM'

# ============================================================
# navGroups.* (1 key)
# ============================================================
T['navGroups.analyses'] = 'Analysen'

# ============================================================
# onboarding.* (9 keys)
# ============================================================
T['onboarding.filter'] = 'Filter'
T['onboarding.filterSand'] = 'Sand'
T['onboarding.idealTemp'] = 'Ideal:'
T['onboarding.pool'] = 'Pool'
T['onboarding.shapeOval'] = 'Oval'
T['onboarding.spa'] = 'Spa'
T['onboarding.step1Label'] = 'Becken'
T['onboarding.step3'] = 'Filtration'
T['onboarding.treatmentUV'] = 'UV'

# ============================================================
# plans.* (36 keys)
# ============================================================
T['plans.expert.features.accountingExport'] = 'Buchhaltungs-Export'
T['plans.expert.features.advancedTechNotes'] = 'Erweiterte technische Notizen'
T['plans.expert.features.allPremium'] = 'Alles aus Premium'
T['plans.expert.features.apiIntegrations'] = 'API + Integrationen'
T['plans.expert.features.multiClients'] = 'Unbegrenzt Multi-Kunden'
T['plans.expert.features.photosBeforeAfter'] = 'Vorher-/Nachher-Fotos'
T['plans.expert.features.quotesVisits'] = 'Angebote und Besuchsplanung'
T['plans.free.features.1pool'] = '1 Pool'
T['plans.free.features.2scans'] = '2 Foto-Scans / Monat'
T['plans.free.features.5guides'] = '5 Basis-Anleitungen'
T['plans.free.features.clearWaterIndex'] = 'Kristallwasser-Index + Badesicherheit'
T['plans.free.features.history14'] = '14-Tage-Verlauf'
T['plans.free.features.simpleWeather'] = 'Einfaches Wetter'
T['plans.free.features.unlimitedManualTests'] = 'Unbegrenzte Wassertests (manuell)'
T['plans.gates.guides_premium'] = 'Premium-Leitfäden sind kostenpflichtigen Plänen vorbehalten.'
T['plans.gates.history_extended'] = 'Erweiterter Verlauf ist kostenpflichtigen Plänen vorbehalten.'
T['plans.gates.multi_pool'] = 'Multi-Pool ist Premium und Expert vorbehalten.'
T['plans.gates.pdf_report'] = 'PDF-Bericht ist Premium und Expert vorbehalten.'
T['plans.gates.photo_scan_limit'] = 'Limit von {n} Scans/Monat erreicht.'
T['plans.gates.pro_mode'] = 'Pro-Modus ist Premium und Expert vorbehalten.'
T['plans.gates.smart_reminders'] = 'Smarte Erinnerungen sind kostenpflichtigen Plänen vorbehalten.'
T['plans.gates.spa_support'] = 'Spa-Support ist dem Premium-Plan vorbehalten.'
T['plans.gates.weather_advanced'] = 'Erweitertes Wetter ist kostenpflichtigen Plänen vorbehalten.'
T['plans.offline'] = 'Offline'
T['plans.premium.features.3pools'] = '3 Pools'
T['plans.premium.features.advancedWeather'] = 'Erweitertes Wetter + Warnungen'
T['plans.premium.features.allGuidesVideos'] = 'Alle Anleitungen + Videos'
T['plans.premium.features.pdfReport'] = 'Teilbarer PDF-Bericht'
T['plans.premium.features.prioritySupport'] = 'Priority-Support'
T['plans.premium.features.proMode'] = 'Pro-Modus (erweitertes LSI)'
T['plans.premium.features.smartReminders'] = 'Smarte Erinnerungen'
T['plans.premium.features.spaSupport'] = 'Spa und Heißwasser (Brom, Aktivsauerstoff)'
T['plans.premium.features.unlimitedHistory'] = 'Unbegrenzter Verlauf'
T['plans.premium.features.unlimitedScans'] = 'Unbegrenzte Foto-Scans'
T['plans.premium.name'] = 'Premium'
T['plans.premiumLabel'] = 'AQWELIA Premium'

# ============================================================
# reminders.* (38 keys)
# ============================================================
T['reminders.cell_clean.action'] = 'Bauen Sie die Zelle aus, legen Sie sie 10-15 Min. in eine verdünnte Säurelösung ein, spülen Sie sie.'
T['reminders.cell_clean.detail'] = 'Die Zelle verkalkt mit der Zeit. Säurereinigung alle 3-6 Monate.'
T['reminders.cell_clean.title'] = 'Reinigung der Elektrolysezelle'
T['reminders.equipment_overdue.action'] = 'Planen Sie eine Wartung für diese Ausrüstung.'
T['reminders.equipment_overdue.detail'] = 'Wartung seit {days} Tagen überfällig.'
T['reminders.equipment_overdue.title'] = 'Wartung {type}'
T['reminders.filter_clean.actionCartridge'] = 'Patrone ausbauen und ausspülen.'
T['reminders.filter_clean.actionSand'] = 'Eine Rückspülung durchführen.'
T['reminders.filter_clean.detailCartridge'] = 'Spülen der Patrone empfohlen.'
T['reminders.filter_clean.detailGeneric'] = 'Filterprüfung empfohlen.'
T['reminders.filter_clean.detailSand'] = 'Rückspülen des Sandfilters empfohlen.'
T['reminders.filter_clean.title'] = 'Filterreinigung'
T['reminders.low_product.action'] = 'Denken Sie an den Nachkauf, bevor es ausgeht.'
T['reminders.low_product.detail'] = 'Von diesem Produkt ist nur noch wenig vorhanden.'
T['reminders.low_product.title'] = 'Niedriger Bestand: {name}'
T['reminders.retest_product.action'] = 'Innerhalb der nächsten Stunden einen weiteren pH- + Chlor-Test durchführen.'
T['reminders.retest_product.detail'] = 'Sie haben kürzlich ein Produkt hinzugefügt. Prüfen Sie die Wirkung.'
T['reminders.retest_product.title'] = 'Re-Test nach Behandlung'
T['reminders.skimmer_clean.action'] = 'Leeren Sie den Skimmerkorb und den Pumpenkorb.'
T['reminders.skimmer_clean.detail'] = 'Schmutz, Blätter und Insekten regelmäßig entfernen.'
T['reminders.skimmer_clean.title'] = 'Skimmer und Korb prüfen'
T['reminders.startup.action'] = 'Folgen Sie dem Leitfaden zur Inbetriebnahme: Reinigung, Behandlung, Filtration.'
T['reminders.startup.detail'] = 'Der Frühling kommt: Bereiten Sie den Pool auf die Saison vor.'
T['reminders.startup.title'] = 'Saisonale Inbetriebnahme'
T['reminders.test_first.action'] = 'Geben Sie Ihren ersten Test ein (mindestens pH).'
T['reminders.test_first.detail'] = 'Kein Test erfasst. Aktivieren Sie die Nachverfolgung.'
T['reminders.test_first.title'] = 'Erster Wassertest'
T['reminders.test_overdue.action'] = 'Führen Sie einen vollständigen Test durch: pH + Chlor + TAC.'
T['reminders.test_overdue.detail'] = 'Letzter Test vor {days} Tagen. Die Wasserqualität ändert sich schnell.'
T['reminders.test_overdue.title'] = 'Wassertest wiederholen'
T['reminders.test_soon.action'] = 'Prüfen Sie pH und freies Chlor.'
T['reminders.test_soon.detail'] = 'Letzter Test vor {days} Tagen.'
T['reminders.test_soon.title'] = 'Routine-Test'
T['reminders.winterize.action'] = 'Folgen Sie dem Leitfaden zur Überwinterung: kaltes Wasser, Winterprodukte, Abdeckung.'
T['reminders.winterize.detail'] = 'Der Herbst ist da: denken Sie an die Überwinterung.'
T['reminders.winterize.title'] = 'Überwinterung vorbereiten'
T['reminders.wx_test.action'] = 'Testen Sie pH und Chlor.'
T['reminders.wx_test.title'] = 'Test empfohlen (Wetter)'

# ============================================================
# settings.* (7 keys)
# ============================================================
T['settings.deleteFailedDesc'] = 'Löschen fehlgeschlagen'
T['settings.exportFailedDesc'] = 'Export fehlgeschlagen'
T['settings.imperialLower'] = 'imperial'
T['settings.imperialPlural'] = 'imperial'
T['settings.planPremium'] = 'Premium'
T['settings.unitsImperial'] = 'Imperial'
T['settings.unitsSystem'] = 'System'

# ============================================================
# spaData.* (18 keys)
# ============================================================
T['spaData.drainage_reason_intensive'] = 'Intensive Nutzung erkannt — Ablassen alle {months} Monate empfohlen, um eine Sättigung mit Chemikalien zu vermeiden.'
T['spaData.drainage_reason_standard'] = 'Ablassen alle {months} Monate empfohlen (wirtschaftlicher als Überbehandlung).'
T['spaData.freq.config'] = 'Konfiguration'
T['spaData.freq.daily'] = 'Täglich'
T['spaData.freq.every_3_4_months'] = 'Alle 3-4 Monate'
T['spaData.freq.per_drain'] = 'Bei jedem Ablassen'
T['spaData.freq.per_usage'] = 'Je nach Nutzung'
T['spaData.freq.weekly'] = 'Wöchentlich'
T['spaData.rec_chlorine_evaporates'] = '⚠️ Chlor verdunstet in heißem Wasser schnell. Wechseln Sie für mehr Effizienz zu Brom.'
T['spaData.rec_cover_after_use'] = 'Decken Sie den Spa nach jeder Nutzung ab, um Verdunstung und Photosynthese zu vermeiden.'
T['spaData.rec_drain_economic'] = 'Lassen Sie alle 3-4 Monate Wasser ab — das ist wirtschaftlicher als eine Überbehandlung.'
T['spaData.rec_temp_critical_health'] = '🔴 Kritische Temperatur (>38 °C) — Gesundheitsrisiko. Senken Sie die Temperatur.'
T['spaData.rec_temp_high_chlorine_warning'] = '⚠️ Hohe Temperatur — Chlor wird NICHT empfohlen. Verwenden Sie Brom.'
T['spaData.rec_temp_high_session_limit'] = 'Temperatur überwachen: über 38 °C, Sitzungen auf 15-20 Min. begrenzen.'
T['spaData.seats_label'] = 'Anzahl Sitzplätze'
T['spaData.usage_intensive'] = 'Intensiv (5+/Woche)'
T['spaData.usage_occasional'] = 'Gelegentlich (1-2x/Woche)'
T['spaData.usage_regular'] = 'Regelmäßig (3-4x/Woche)'

# ============================================================
# weather.* (42 keys)
# ============================================================
T['weather.alerts.frost_risk.action'] = 'Schützen Sie den Technikraum. Lassen Sie die Filtration nachts laufen, um Frost zu vermeiden. Überwintern Sie, falls noch nicht geschehen.'
T['weather.alerts.frost_risk.message'] = 'Negative Temperatur erwartet. Risiko für Ausrüstung und Leitungen.'
T['weather.alerts.frost_risk.title'] = 'Frostgefahr'
T['weather.alerts.frost_risk.when'] = 'Heute Nacht'
T['weather.alerts.heat_extreme.action'] = 'Filtration um 2 Std./Tag erhöhen. Jeden Morgen den Chlorwert prüfen. Präventives Anti-Algen-Mittel in Betracht ziehen.'
T['weather.alerts.heat_extreme.message'] = '{temp} °C erwartet. Sehr heißes Wasser = Chlor wird schneller verbraucht + Algenwachstum.'
T['weather.alerts.heat_extreme.title'] = 'Hitzewelle erwartet'
T['weather.alerts.heat_extreme.when'] = 'Ab sofort und während der Hitzewelle'
T['weather.alerts.heat_high.action'] = 'Filtration um 1 Std./Tag erhöhen und morgen Chlor testen.'
T['weather.alerts.heat_high.message'] = '{temp} °C erwartet. Wahrscheinlicher Chlor-Überverbrauch.'
T['weather.alerts.heat_high.title'] = 'Starke Hitze erwartet'
T['weather.alerts.heat_high.when'] = 'Morgen früh'
T['weather.alerts.heavy_rain.action'] = 'Nach dem Regen: pH und Chlor prüfen, Skimmer und Pumpenkorb reinigen.'
T['weather.alerts.heavy_rain.message'] = 'Regen verdünnt die Chemikalien, senkt den pH-Wert und bringt Schmutz.'
T['weather.alerts.heavy_rain.title'] = 'Starker Regen erwartet'
T['weather.alerts.heavy_rain.when'] = 'Nach dem Regen'
T['weather.alerts.storm_soon.action'] = 'Prüfen Sie heute Abend vor dem Gewitter das freie Chlor. Verstärken Sie morgen die Filtration.'
T['weather.alerts.storm_soon.message'] = '{percent}% Gewitterrisiko. Das Gewitter verdünnt das Chlor und erhöht den pH-Wert.'
T['weather.alerts.storm_soon.title'] = 'Morgen Gewitter erwartet'
T['weather.alerts.storm_soon.when'] = 'Heute Abend vor 20 Uhr'
T['weather.alerts.uv_high.action'] = 'Prüfen Sie Ihren Stabilisator (CYA) und das freie Chlor.'
T['weather.alerts.uv_high.message'] = 'Sonnenlicht baut nicht stabilisiertes Chlor schneller ab.'
T['weather.alerts.uv_high.title'] = 'Sehr hohe UV-Strahlung'
T['weather.alerts.uv_high.when'] = 'Diese Woche'
T['weather.alerts.wind_strong.action'] = 'Skimmer und Pumpenkorb prüfen. Wasserlinie reinigen.'
T['weather.alerts.wind_strong.message'] = '{wind} km/h. Schmutz, Blätter, Staub im Pool.'
T['weather.alerts.wind_strong.title'] = 'Starker Wind erwartet'
T['weather.alerts.wind_strong.when'] = 'Nach dem Wind'
T['weather.filtration.reason'] = 'Regel: Die Hälfte der Wassertemperatur ({temp} °C) in Filtrationsstunden.'
T['weather.filtration.scheduleDiurnal'] = 'Tägliche Filtration empfohlen.'
T['weather.filtration.scheduleNocturnal'] = 'Bevorzugen Sie nächtliche Filtration (weniger Verdunstung, bessere Chlor-Effizienz).'
T['weather.severity.info'] = 'Info'
T['weather.summary.calm'] = 'Mildes Wetter in {location}. Keine spezielle Warnung. {hours} Std./Tag filtern.'
T['weather.summary.withAlerts'] = '{count} Wetterwarnung(en): {titles}. Befolgen Sie die empfohlenen Aktionen.'
T['weather.swim.ideal'] = 'Ideal'
T['weather.testReason.after_rain'] = 'pH- + Chlor-Test nach dem Regen empfohlen.'
T['weather.testReason.before_storm'] = 'Test vor dem erwarteten Gewitter morgen empfohlen.'
T['weather.testReason.during_heatwave'] = 'Täglicher Test während der Hitzewelle empfohlen.'
T['weather.testReason.routine'] = 'Letzter Test vor {days} Tagen. Routine-Test empfohlen.'
T['weather.testReason.urgent'] = 'Letzter Test vor {days} Tagen: dringender Test empfohlen.'
T['weather.uvShort'] = 'UV'
T['weather.wind'] = 'Wind'

# ============================================================
# Final write
# ============================================================
OUT = '/home/z/my-project/.tmp/translated/de-part2.json'
with open(OUT, 'w', encoding='utf-8') as f:
    json.dump(T, f, ensure_ascii=False, indent=2, sort_keys=False)
    f.write('\n')

print(f'Wrote {len(T)} keys to {OUT}')
print(f'File size: {os.path.getsize(OUT)} bytes')
