#!/usr/bin/env python3
"""Build de-part1.json with German translations for all 501 keys."""
import json
import os

# German translations: dict of dotted.key -> German value
T = {
    # ===== admin (21) =====
    "admin.accessDenied": "Zugriff verweigert.",
    "admin.analyticsComingSoonFull": "Detaillierte Daten folgen — API-Verbindung /api/analytics",
    "admin.backToSiteArrow": "← Zurück zur Website",
    "admin.bannerDefaultText": "☀️ Sommer 2026 — 20 % Rabatt auf den Lagoon-Plan sichern!",
    "admin.bannerDescFull": "Passen Sie den Promo-Banner oben in der App an. Ideal für Saisons, Aktionen, Ankündigungen.",
    "admin.bannerLink": "Link (optional)",
    "admin.bannerSavedToast": "Banner gespeichert",
    "admin.bannerText": "Text",
    "admin.contentComingSoonFull": "Demnächst — WYSIWYG-Content-Editor für Landingpage, Ratgeber, E-Mails...",
    "admin.delete": "Löschen",
    "admin.learnMore": "Mehr erfahren →",
    "admin.popupDefaultBody": "Aktion Beschreibung...",
    "admin.popupDefaultCta": "Profitieren",
    "admin.popupDefaultTitle": "Neues Promo-Popup",
    "admin.popupDescFull": "Erstellen Sie Popups, die basierend auf Triggern erscheinen. Upload von Promo-Bildern folgt.",
    "admin.popupImagePlaceholder": "Promo-Bild-URL (Upload folgt)",
    "admin.popupsSavedToast": "Popups gespeichert",
    "admin.title": "AQWELIA Admin",
    "admin.usersComingSoonFull": "Demnächst — Benutzerliste, Abonnementverwaltung, Support...",
    "admin.usersDescFull": "Benutzer, Abonnements und Zugriffe verwalten.",
    "admin.wrongPassword": "Falsches Passwort",

    # ===== common (2) =====
    "common.name": "Name",
    "common.optional": "optional",

    # ===== auth (1) =====
    "auth.nameLabel": "Name (optional)",

    # ===== diagnostic (3) =====
    "diagnostic.filtrationHoursShort": "Filtr. {n}h",
    "diagnostic.offlineTitle": "Offline",
    "diagnostic.typeFilter": "Filter",

    # ===== diagnosticActionPlan (219) =====
    "diagnosticActionPlan.afterTreatment": "Nach der Behandlung",
    "diagnosticActionPlan.cancelValidation": "Validierung abbrechen",
    "diagnosticActionPlan.cloudyS1I1": "Schalten Sie die Pumpe vor jeder Sicherheitmaßnahme aus.",
    "diagnosticActionPlan.cloudyS1I2": "Druck am Manometer prüfen: bei > 0.3 bar über dem Ausgangswert → reinigen.",
    "diagnosticActionPlan.cloudyS1I3": "Sandfilter: 2-3 Min. rückspülen, dann 30 s nachspülen.",
    "diagnosticActionPlan.cloudyS1I4": "Kartuschenfilter: demontieren, mit dem Wasserschlauch abspritzen, bei > 2 Jahren ersetzen.",
    "diagnosticActionPlan.cloudyS1I5": "Skimmer- und Pumpenvorfilterkörbe leeren und reinigen.",
    "diagnosticActionPlan.cloudyS1I6": "Wieder einschalten und prüfen, ob der Durchfluss gut ist (Einlaufdüsen).",
    "diagnosticActionPlan.cloudyS1Intro": "Trübes Wasser entsteht meist durch unwirksame Filtration. Hier immer beginnen.",
    "diagnosticActionPlan.cloudyS1Title": "1. Filtration prüfen und reinigen",
    "diagnosticActionPlan.cloudyS2Dosage": "~{qty} g pH- / 0.1 Einheit (für {volume} m³)",
    "diagnosticActionPlan.cloudyS2I1": "pH in 30 cm Tiefe messen.",
    "diagnosticActionPlan.cloudyS2I2": "Wenn pH > 7.4 → pH- zugeben; wenn pH < 7.0 → pH+ zugeben.",
    "diagnosticActionPlan.cloudyS2I3": "Richtwert: ~{qty} g pH-, um 0.1 Einheit auf {volume} m³ zu senken.",
    "diagnosticActionPlan.cloudyS2I4": "In einem Eimer Poolwasser verdünnen, vor die Einlaufdüsen gießen.",
    "diagnosticActionPlan.cloudyS2I5": "Filtration 2 h laufen lassen, bevor erneut getestet wird.",
    "diagnosticActionPlan.cloudyS2Intro": "Ein unausgeglichener pH-Wert begünstigt Trübung und verringert die Wirksamkeit des Chlors.",
    "diagnosticActionPlan.cloudyS2Product": "pH- oder pH+ (je nach Messung)",
    "diagnosticActionPlan.cloudyS2Title": "2. pH messen und anpassen",
    "diagnosticActionPlan.cloudyS3Dosage": "{qty} mL Flockungsmittel (für {volume} m³)",
    "diagnosticActionPlan.cloudyS3I1": "⚠ NIEMALS Flockungsmittel bei Kartuschenfilter verwenden (Verstopfungsgefahr).",
    "diagnosticActionPlan.cloudyS3I2": "Dosierung: ~5 mL flüssiges Flockungsmittel pro m³.",
    "diagnosticActionPlan.cloudyS3I3": "Für {volume} m³: {qty} mL Flockungsmittel.",
    "diagnosticActionPlan.cloudyS3I4": "Vor die Einlaufdüsen gießen, Filtration 1 h laufen lassen.",
    "diagnosticActionPlan.cloudyS3I5": "Anschließend Filtration 12 h abschalten, damit es sich absetzen kann.",
    "diagnosticActionPlan.cloudyS3I6": "Die Flocken sinken auf den Boden — mit Roboter oder manuellem Bodensauger absaugen.",
    "diagnosticActionPlan.cloudyS3Intro": "Flockungsmittel verklumpt feine Partikel zu Flocken, die der Filter zurückhalten kann. ⚠ Nur für Sandfilter.",
    "diagnosticActionPlan.cloudyS3Product": "Flüssiges Flockungsmittel (nur Sandfilter)",
    "diagnosticActionPlan.cloudyS3Title": "3. Flockungsmittel zugeben (bei Sandfilter)",
    "diagnosticActionPlan.cloudyS4I1": "Pumpe nach dem Absaugen der Flocken im Dauerbetrieb wieder starten.",
    "diagnosticActionPlan.cloudyS4I2": "Filterdruck überwachen — bei Anstieg rückspülen.",
    "diagnosticActionPlan.cloudyS4I3": "Skimmerkorb alle 4 h prüfen.",
    "diagnosticActionPlan.cloudyS4I4": "Nach 12 h sollte das Wasser wieder klar sein.",
    "diagnosticActionPlan.cloudyS4Intro": "Filtration 12 h laufen lassen, um das Wasser nach Flockung/Absaugen zu klären.",
    "diagnosticActionPlan.cloudyS4Title": "4. Durchgehende Filtration 12 h",
    "diagnosticActionPlan.cloudyS5I1": "pH messen (Ziel: 7.0 - 7.4).",
    "diagnosticActionPlan.cloudyS5I2": "Freies Chlor messen (Ziel: 1 - 3 mg/L).",
    "diagnosticActionPlan.cloudyS5I3": "Geben Sie Ihre Werte unten ein — sie werden in Ihrem Logbuch gespeichert.",
    "diagnosticActionPlan.cloudyS5I4": "Wenn die Werte OK und das Wasser klar ist → Problem gelöst.",
    "diagnosticActionPlan.cloudyS5Intro": "Prüfen, dass das Wasser ausgeglichen ist und das Chlor aktiv ist.",
    "diagnosticActionPlan.cloudyS5Title": "5. Wasser erneut testen",
    "diagnosticActionPlan.compAlgae1Desc": "Die Algen sind trotz der ersten Behandlung noch vorhanden. Stoßbehandlung mit der 1.5-fachen vorherigen Dosis wiederholen. Zuvor unbedingt prüfen, dass der pH-Wert zwischen 7.0-7.4 liegt. Eine Stoßchlor-Marke anderer Marke bevorzugen (Algen können Resistenzen entwickeln).",
    "diagnosticActionPlan.compAlgae1Reason": "Algen können resistent sein. Eine stärkere Dosis und ein anderes Produkt sind erforderlich.",
    "diagnosticActionPlan.compAlgae1Title": "{n}. Stoßbehandlungs-Dosis verdoppeln",
    "diagnosticActionPlan.compAlgae2Desc": "Zählen Sie die Anzahl der Filterstunden pro Tag. Bei grünem Wasser muss mindestens 12 h/24 h gefiltert werden. Ideal ist 24 h/24 h an 3 aufeinanderfolgenden Tagen.",
    "diagnosticActionPlan.compAlgae2Reason": "Eine unzureichende Filtration verhindert das Entfernen toter Algen und die Klärung des Wassers.",
    "diagnosticActionPlan.compAlgae2Title": "{n}. Filterdauer prüfen",
    "diagnosticActionPlan.compAlgae3Desc": "Bei einem Sandfilter 3 Minuten rückspülen, gefolgt von 30 s Spülen. Bei einer Kartusche diese ausbauen und mit dem Schlauch abspritzen. Ein verstopfter Filter fängt keine Algen ab und leitet sie in den Pool zurück.",
    "diagnosticActionPlan.compAlgae3Reason": "Der Filter kann nach der ersten Behandlung mit Algen gesättigt sein.",
    "diagnosticActionPlan.compAlgae3Title": "{n}. Filter gründlich reinigen",
    "diagnosticActionPlan.compCloudy1Desc": "Das Wasser ist noch trüb. Flüssiges Flockungsmittel (nicht im Strumpf) direkt vor die Einlaufdüsen gießen, bei laufender Pumpe. 1 h filtern, dann 12 h abschalten, damit es sich absetzen kann. Die Partikel verklumpen und sinken auf den Boden.",
    "diagnosticActionPlan.compCloudy1Reason": "Flockungsmittel verklumpt feine Partikel, die der Filter nicht zurückhält.",
    "diagnosticActionPlan.compCloudy1Title": "{n}. Flüssiges Flockungsmittel zugeben",
    "diagnosticActionPlan.compCloudy2Desc": "Nach 12 h Absetzen liegen die Ablagerungen am Boden. Langsam in Stellung 'Abwasser' (waste) absaugen, um zu vermeiden, dass sie zurück in den Filter gelangen. Das Ventil erst nach Abschluss des Absaugens wieder auf Filtration schalten.",
    "diagnosticActionPlan.compCloudy2Reason": "Die Flocken sind zu schwer für den normalen Filter.",
    "diagnosticActionPlan.compCloudy2Title": "{n}. Boden nach Flockung absaugen",
    "diagnosticActionPlan.compCloudy3Desc": "Wenn das Wasser trotz Flockung + Filtration trüb bleibt: Sand/Kartusche muss eventuell ersetzt werden. Sand wird alle 5-7 Jahre, Kartuschen alle 2 Jahre gewechselt. Ein abgenutztes Filtermedium hält keine feinen Partikel mehr zurück.",
    "diagnosticActionPlan.compCloudy3Reason": "Ein Filter am Lebensende ist eine häufige Ursache für anhaltend trübes Wasser.",
    "diagnosticActionPlan.compCloudy3Title": "{n}. Filtermedium prüfen",
    "diagnosticActionPlan.compFallback1Desc": "Das Wasser verbessert sich, ist aber noch nicht perfekt. Filtration weitere 24 h durchgehend laufen lassen. Filterdruck überwachen (rückspülen bei Anstieg um +0.3 bar).",
    "diagnosticActionPlan.compFallback1Reason": "Die Behandlung ist im Gange, geben Sie ihr Zeit zu wirken.",
    "diagnosticActionPlan.compFallback1Title": "1. Filtration 24 h länger fortsetzen",
    "diagnosticActionPlan.compFallback2Desc": "In 24 h einen vollständigen Test (pH, Chlor, TAC) wiederholen und ein neues Foto zur Prüfung machen. Wenn der Zufriedenheitswert stagniert, erwägen Sie, 20-30 % des Wassers abzulassen, um mit einer gesunden Basis neu zu starten.",
    "diagnosticActionPlan.compFallback2Reason": "Die Behandlung braucht Zeit, um zu wirken, bevor sie als Fehlschlag eingestuft wird.",
    "diagnosticActionPlan.compFallback2Title": "2. In 24 h erneut testen",
    "diagnosticActionPlan.compNewIssuesDesc": "Neue(s) Problem(e) aufgetreten: {issues}. Analysieren Sie die wahrscheinliche Ursache (Überchlorung, Flockungsmittel-Überdosierung, Kalkausfällung usw.), bevor Sie handeln. Im Zweifel einen vollständigen pH/Chlor/TAC/TH-Test wiederholen.",
    "diagnosticActionPlan.compNewIssuesReason": "Einige Behandlungen können neue Ungleichgewichte schaffen. Diese müssen korrigiert werden, bevor sie die Situation verschlimmern.",
    "diagnosticActionPlan.compNewIssuesTitle": "{n}. Neu erkannte Probleme behandeln",
    "diagnosticActionPlan.dosage": "Dosierung",
    "diagnosticActionPlan.fieldChlorineLabel": "Gemessenes freies Chlor",
    "diagnosticActionPlan.fieldPhLabel": "Gemessenen pH-Wert eingeben",
    "diagnosticActionPlan.fieldTacLabel": "Gemessener TAC",
    "diagnosticActionPlan.genericInstruction1Default": "Folgen Sie den oben angezeigten Empfehlungen der KI.",
    "diagnosticActionPlan.genericInstruction2": "Vor jeder Behandlung pH messen (Ziel: 7.0 - 7.4).",
    "diagnosticActionPlan.genericInstruction2_1": "Mindestens 24 h durchgehende Filtration abwarten.",
    "diagnosticActionPlan.genericInstruction2_2": "Ein neues Foto unter denselben Bedingungen machen (gleiche Stelle, gleiche Beleuchtung).",
    "diagnosticActionPlan.genericInstruction2_3": "Unten im Plan auf „Ergebnis prüfen“ klicken.",
    "diagnosticActionPlan.genericInstruction2_4": "Die KI vergleicht und sagt, ob das Problem gelöst ist.",
    "diagnosticActionPlan.genericInstruction3": "Bei Bedarf mit pH- oder pH+ anpassen.",
    "diagnosticActionPlan.genericInstruction4": "Messung unten für die Historie erfassen.",
    "diagnosticActionPlan.genericInstruction5": "Prüfen, dass die Filtration mindestens 8 h/Tag läuft.",
    "diagnosticActionPlan.genericIntro1": "Die KI hat ein Problem erkannt, aber kein typisches Muster (grünes/trübes Wasser). Folgen Sie der untenstehenden Empfehlung.",
    "diagnosticActionPlan.genericIntro2": "Nach Anwendung der Empfehlungen ein neues Foto machen, um die Lösung zu bestätigen.",
    "diagnosticActionPlan.genericProduct": "Gemäß Empfehlung",
    "diagnosticActionPlan.genericTitle1": "1. Empfehlung befolgen",
    "diagnosticActionPlan.genericTitle2": "2. Ergebnis prüfen (24 h)",
    "diagnosticActionPlan.greenS1Dosage": "~{qty} g pH- / 0.1 Einheit zu senken (Pool von {volume} m³)",
    "diagnosticActionPlan.greenS1I1": "Test-Kit (Tropfen oder Streifen) oder elektronischen Tester nehmen.",
    "diagnosticActionPlan.greenS1I2": "Wasserprobe in 30 cm Tiefe, entfernt von den Einlaufdüsen, entnehmen.",
    "diagnosticActionPlan.greenS1I3": "Aktuellen pH messen und unten notieren.",
    "diagnosticActionPlan.greenS1I4": "Wenn pH > 7.4 → pH- (Säure) zugeben. Wenn pH < 7.0 → pH+ (Base) zugeben.",
    "diagnosticActionPlan.greenS1I5": "Richtdosis: ~{qty} g pH-, um 0.1 Einheit auf {volume} m³ zu senken.",
    "diagnosticActionPlan.greenS1I6": "Produkt in einem Eimer Poolwasser verdünnen, niemals pur.",
    "diagnosticActionPlan.greenS1I7": "Langsam vor die Einlaufdüsen gießen, bei laufender Pumpe.",
    "diagnosticActionPlan.greenS1I8": "2 Stunden bei laufender Filtration warten, bevor erneut getestet wird.",
    "diagnosticActionPlan.greenS1Intro": "Der pH-Wert muss VOR jeder Behandlung zwischen 7.0 und 7.4 liegen. Ein falscher pH-Wert macht Chlor unwirksam (bis zu -90 %).",
    "diagnosticActionPlan.greenS1Product": "pH- oder pH+ (je nach Messung)",
    "diagnosticActionPlan.greenS1Title": "1. pH messen und anpassen",
    "diagnosticActionPlan.greenS2Dosage": "Nachjustierung: halbe Anfangsdosis (~{qty} g max für {volume} m³)",
    "diagnosticActionPlan.greenS2I1": "Neue Wasserprobe in 30 cm Tiefe entnehmen.",
    "diagnosticActionPlan.greenS2I2": "pH erneut messen.",
    "diagnosticActionPlan.greenS2I3": "Wenn pH zwischen 7.0 und 7.4 → ✅ zum nächsten Schritt (Stoßbehandlung).",
    "diagnosticActionPlan.greenS2I4": "Wenn pH noch zu hoch/niedrig → erneut mit der HÄLFTE der vorherigen Dosis anpassen.",
    "diagnosticActionPlan.greenS2I5": "1 h nach dieser zweiten Anpassung erneut testen.",
    "diagnosticActionPlan.greenS2Intro": "Nach 2 h Filtration hatte der pH-Wert Zeit, sich zu stabilisieren. Prüfen, dass er jetzt im Zielbereich liegt.",
    "diagnosticActionPlan.greenS2Product": "pH- oder pH+ (reduzierte Dosis bei Nachjustierung)",
    "diagnosticActionPlan.greenS2Title": "2. pH erneut testen (nach 2 h)",
    "diagnosticActionPlan.greenS3Dosage": "{qty} g Stoßchlor (für {volume} m³)",
    "diagnosticActionPlan.greenS3I1": "⚠ Prüfen, dass der pH-Wert korrekt ist (Schritte 1-2). Sonst wird die Stoßbehandlung unwirksam sein.",
    "diagnosticActionPlan.greenS3I2": "Kurative Dosis berechnen: ca. 10 g Stoßchlor pro m³.",
    "diagnosticActionPlan.greenS3I3": "Für Ihren Pool von {volume} m³: {qty} g Stoßchlor (ca. {tablets} Tabletten à 20 g).",
    "diagnosticActionPlan.greenS3I4": "Abends bevorzugen, keine Badenden, Pumpe läuft.",
    "diagnosticActionPlan.greenS3I5": "Pulver-/Granulatchlor in einem Eimer Poolwasser verdünnen.",
    "diagnosticActionPlan.greenS3I6": "Vor die Einlaufdüsen gießen, niemals in den Skimmer.",
    "diagnosticActionPlan.greenS3I7": "🚫 BADEVERBOT für mindestens 8 Stunden.",
    "diagnosticActionPlan.greenS3Intro": "Stoßchlor zerstört Algen, Bakterien und Viren. Das ist der wichtigste Schritt gegen grünes Wasser.",
    "diagnosticActionPlan.greenS3Product": "Stoßchlor (65 % aktiv, Granulat oder Tabletten)",
    "diagnosticActionPlan.greenS3Title": "3. Chlor-Stoßbehandlung",
    "diagnosticActionPlan.greenS4Dosage": "{qty} mL Anti-Algen (für {volume} m³)",
    "diagnosticActionPlan.greenS4I1": "Mindestens 2 h nach der Stoßbehandlung warten (niemals direkt mischen).",
    "diagnosticActionPlan.greenS4I2": "Kurative Dosis: ~20 mL Anti-Algen pro m³.",
    "diagnosticActionPlan.greenS4I3": "Für {volume} m³: {qty} mL Anti-Algen (d. h. {liters} L).",
    "diagnosticActionPlan.greenS4I4": "Direkt vor die Einlaufdüsen gießen, bei laufender Pumpe.",
    "diagnosticActionPlan.greenS4I5": "Wände direkt danach bürsten (siehe nächsten Schritt), um die Algen zu lösen.",
    "diagnosticActionPlan.greenS4Intro": "Anti-Algen ergänzt Chlor, indem es resistente Algen zerstört und erneutes Wachstum verhindert.",
    "diagnosticActionPlan.greenS4Product": "Kuratives Anti-Algen",
    "diagnosticActionPlan.greenS4Title": "4. Anti-Algen (präventiv kurativ)",
    "diagnosticActionPlan.greenS5I1": "Bürste verwenden, die zum Belag passt: Nylonbürste für Folie/Schale, Stahlbürste für Beton.",
    "diagnosticActionPlan.greenS5I2": "🚫 Niemals Metallbürste auf Folie oder armierter Membran — Sie würden sie durchstechen.",
    "diagnosticActionPlan.greenS5I3": "Von oben nach unten bürsten, in 1-m²-Abschnitten.",
    "diagnosticActionPlan.greenS5I4": "Auf Ecken, Stufen, Düsen, Leitern und die Wasserlinie achten.",
    "diagnosticActionPlan.greenS5I5": "Bei Erreichbarkeit auch den Boden bürsten (Teleskopstange).",
    "diagnosticActionPlan.greenS5I6": "Das ist anstrengend (15-30 Min.), aber UNERLÄSSLICH — ohne das kommen die Algen in 48 h zurück.",
    "diagnosticActionPlan.greenS5Intro": "Bürsten löst festgesetzte Algen. Ohne diesen Schritt reicht die chemische Behandlung nicht aus.",
    "diagnosticActionPlan.greenS5Title": "5. Wände und Boden bürsten",
    "diagnosticActionPlan.greenS6I1": "Pumpe auf Dauerbetrieb (24 h/24) einstellen — kein Zeitprogramm.",
    "diagnosticActionPlan.greenS6I2": "Druck am Filtermanometer prüfen.",
    "diagnosticActionPlan.greenS6I3": "Wenn der Druck > 0.3 bar über dem Normalwert steigt → rückspülen.",
    "diagnosticActionPlan.greenS6I4": "Pumpenvorfilter (Korb) reinigen, wenn voller Schmutz.",
    "diagnosticActionPlan.greenS6I5": "Skimmer während dieser 24 h regelmäßig leeren.",
    "diagnosticActionPlan.greenS6I6": "Bei Kartuschenfilter: bei Durchflussabfall mittendrin spülen.",
    "diagnosticActionPlan.greenS6Intro": "Die Filtration muss 24 h ohne Unterbrechung laufen, um tote Algen und Partikel zu entfernen.",
    "diagnosticActionPlan.greenS6Title": "6. Durchgehende Filtration 24 h",
    "diagnosticActionPlan.greenS7I1": "Probe in 30 cm Tiefe entnehmen.",
    "diagnosticActionPlan.greenS7I2": "pH messen (Ziel: 7.0 - 7.4).",
    "diagnosticActionPlan.greenS7I3": "Freies Chlor messen (Ziel: 1 - 3 mg/L).",
    "diagnosticActionPlan.greenS7I4": "TAC / Alkalinität messen (Ziel: 80 - 120 mg/L).",
    "diagnosticActionPlan.greenS7I5": "Ihre 3 Werte unten eingeben — sie werden in Ihrem Logbuch gespeichert.",
    "diagnosticActionPlan.greenS7I6": "Wenn alles im Bereich → können Sie wieder baden. Sonst anpassen.",
    "diagnosticActionPlan.greenS7Intro": "Nach 24 h Filtration einen vollständigen Test durchführen, um zu prüfen, dass das Wasser sicher und ausgeglichen ist.",
    "diagnosticActionPlan.greenS7Title": "7. Vollständiger Wasser-Re-Test",
    "diagnosticActionPlan.immediate": "Sofort",
    "diagnosticActionPlan.initialState": "Ausgangszustand",
    "diagnosticActionPlan.instructionsTitle": "Detaillierte Anleitung",
    "diagnosticActionPlan.lastMeasureChlorine": "Chlor",
    "diagnosticActionPlan.lastMeasureDesc": "Wird als „vorher“-Wert verwendet, um Ihre neuen Messungen zu vergleichen.",
    "diagnosticActionPlan.lastMeasureTac": "TAC",
    "diagnosticActionPlan.lastMeasureTitle": "Zuletzt gespeicherte Messung",
    "diagnosticActionPlan.markAsDone": "Als erledigt markieren",
    "diagnosticActionPlan.noteActionPlan": "Aktionsplan-Schritt: {title}",
    "diagnosticActionPlan.phHigh": "Ihr pH-Wert {ph} ist zu hoch. {qty} pH- zugeben, um auf 7.4 zurückzukehren (Senkung um ~{delta} Einheit).",
    "diagnosticActionPlan.phHighWarning": "Vor die Einlaufdüsen gießen, Pumpe läuft. Niemals reines pH- direkt gießen.",
    "diagnosticActionPlan.phIdeal": "✅ pH im Idealbereich (7.0 - 7.4). Keine Anpassung erforderlich.",
    "diagnosticActionPlan.phLow": "Ihr pH-Wert {ph} ist zu niedrig. {qty} pH+ zugeben, um auf 7.0 anzuheben (Anstieg um ~{delta} Einheit).",
    "diagnosticActionPlan.phLowWarning": "In einem Eimer Poolwasser verdünnen, bevor es vor die Einlaufdüsen gegossen wird.",
    "diagnosticActionPlan.poolDetected": "Pool erkannt:",
    "diagnosticActionPlan.poolDetectedSuffix": "— Dosierungen automatisch berechnet.",
    "diagnosticActionPlan.poolState": "Zustand Ihres Pools",
    "diagnosticActionPlan.product": "Produkt",
    "diagnosticActionPlan.productPhMinus": "pH- (Pulver, Natriumhydrogensulfat)",
    "diagnosticActionPlan.productPhPlus": "pH+ (Natriumcarbonat)",
    "diagnosticActionPlan.progress": "Fortschritt",
    "diagnosticActionPlan.recheckAfter": "Nachher",
    "diagnosticActionPlan.recheckAgain": "Erneut prüfen",
    "diagnosticActionPlan.recheckAnalyze": "Analysieren und prüfen",
    "diagnosticActionPlan.recheckAnalyzeNewPhoto": "Analyse Ihres neuen Fotos",
    "diagnosticActionPlan.recheckAnalyzing": "Analyse läuft...",
    "diagnosticActionPlan.recheckBefore": "Vorher",
    "diagnosticActionPlan.recheckButton": "Ergebnis prüfen (neues Foto)",
    "diagnosticActionPlan.recheckClickToUpload": "Zum Hochladen eines Fotos klicken",
    "diagnosticActionPlan.recheckImprovement": "Verbesserung von +{n}%! Weiter so.",
    "diagnosticActionPlan.recheckLittleImprovement": "Wenig Verbesserung. Passen Sie Ihr Vorgehen mit dem neuen Plan unten an.",
    "diagnosticActionPlan.recheckNewPhotoAlt": "Neues Foto",
    "diagnosticActionPlan.recheckNewPlan": "Neuer ergänzender Plan",
    "diagnosticActionPlan.recheckNewPlanDesc": "Basierend auf der Analyse Ihres neuen Fotos sind hier die empfohlenen ergänzenden Schritte:",
    "diagnosticActionPlan.recheckPersistentIssues": "Weiterhin vorhandene Probleme:",
    "diagnosticActionPlan.recheckTakeNewPhoto": "Neues Foto zur Prüfung machen",
    "diagnosticActionPlan.recommendation": "Empfehlung für Ihre Messung",
    "diagnosticActionPlan.recordMeasures": "Messungen erfassen",
    "diagnosticActionPlan.reminderDesc": "Es verbleiben {count} Schritt(e). Befolgen Sie den Plan bis zum Ende, um das Problem dauerhaft zu lösen.",
    "diagnosticActionPlan.reminderTitle": "Erinnerung",
    "diagnosticActionPlan.resolvedDesc": "Ihr Pool ist jetzt gesund. Die Kontrollanalyse bestätigt, dass das Problem gelöst ist.",
    "diagnosticActionPlan.resolvedTitle": "✅ Mit AQWELIA gelöst",
    "diagnosticActionPlan.skipStep": "Diesen Schritt überspringen",
    "diagnosticActionPlan.stepsCount": "{done}/{total} Schritte",
    "diagnosticActionPlan.title": "Geführter Aktionsplan",
    "diagnosticActionPlan.toastMeasureSaved": "Messung gespeichert ✓",
    "diagnosticActionPlan.toastMeasureSavedDesc": "{measures} → Logbuch aktualisiert.",
    "diagnosticActionPlan.toastMissingRequired": "Pflichtfelder fehlen",
    "diagnosticActionPlan.toastMissingRequiredDesc": "Füllen Sie vor der Validierung alle Pflichtfelder (*) aus.",
    "diagnosticActionPlan.toastRecheckErrorDesc": "Analyse nicht möglich",
    "diagnosticActionPlan.toastRecheckErrorTitle": "Fehler",
    "diagnosticActionPlan.toastRecheckNotResolvedDesc": "Behandlung fortsetzen und später erneut prüfen.",
    "diagnosticActionPlan.toastRecheckNotResolvedTitle": "Noch nicht gelöst",
    "diagnosticActionPlan.toastRecheckResolvedDesc": "✅ Ihr Pool ist jetzt gesund.",
    "diagnosticActionPlan.toastRecheckResolvedTitle": "Problem gelöst!",
    "diagnosticActionPlan.toastSaveFailed": "Speichern nicht möglich",
    "diagnosticActionPlan.toastSaveFailedTitle": "Fehler beim Speichern",
    "diagnosticActionPlan.toastStepValidated": "Schritt validiert",
    "diagnosticActionPlan.toastStepValidatedNoMeasure": "Schritt validiert (ohne Messung)",
    "diagnosticActionPlan.urgencyCritical": "Dringend",
    "diagnosticActionPlan.urgencyImportant": "Wichtig",
    "diagnosticActionPlan.urgencyLow": "OK",
    "diagnosticActionPlan.urgencyModerate": "Beobachten",
    "diagnosticActionPlan.validateAndSave": "Validieren und speichern",
    "diagnosticActionPlan.validating": "Speichern…",
    "diagnosticActionPlan.waitTime": "Wartezeit",
    "diagnosticActionPlan.waterTestNote": "Messungen werden in Ihrem Logbuch gespeichert (",
    "diagnosticActionPlan.waterTestNoteSuffix": ") über die API.",

    # ===== guidesData (255) =====
    # after-storm
    "guidesData.after-storm.steps.1.detail": "Gewitter säuern oft das Wasser und verdünnen das Chlor.",
    "guidesData.after-storm.steps.1.title": "pH und Chlor testen",
    "guidesData.after-storm.steps.2.detail": "Durch Regen und Wind eingebrachte Trümmer.",
    "guidesData.after-storm.steps.2.title": "Skimmer und Korb reinigen",
    "guidesData.after-storm.steps.3.detail": "Vor jeder Chlorzugabe hat der pH Vorrang.",
    "guidesData.after-storm.steps.3.title": "pH bei Bedarf anpassen",
    "guidesData.after-storm.steps.4.detail": "Langsamchlor oder Stoßchlor je nach Abweichung.",
    "guidesData.after-storm.steps.4.title": "Chlor bei niedrigem Wert auffüllen",
    "guidesData.after-storm.steps.5.detail": "Korrekturen gut verteilen.",
    "guidesData.after-storm.steps.5.title": "4-6 h filtern",
    "guidesData.after-storm.summary": "Das Gewitter verdünnt das Chlor und verändert den pH. Routine nach dem Gewitter.",
    "guidesData.after-storm.title": "Was nach einem Gewitter tun?",

    # categories
    "guidesData.cat_equipment": "Ausrüstung",
    "guidesData.cat_faq": "FAQ",
    "guidesData.cat_getting_started": "Erste Schritte",
    "guidesData.cat_problems": "Wasserprobleme",
    "guidesData.cat_products": "Produkte & Dosierung",
    "guidesData.cat_safety": "Sicherheit & Baden",
    "guidesData.cat_treatments": "Behandlungen (Chlor/Salz/Brom)",
    "guidesData.cat_weather_seasons": "Wetter & Jahreszeiten",

    # cell-clean
    "guidesData.cell-clean.steps.1.detail": "Elektrolysegerät und Pumpe ausschalten.",
    "guidesData.cell-clean.steps.1.title": "Stromversorgung kappen",
    "guidesData.cell-clean.steps.1.warning": "Elektrische Sicherheit. Niemals die Zelle unter Spannung berühren.",
    "guidesData.cell-clean.steps.2.detail": "Je nach Modell abschrauben. Zustand der Elektroden prüfen.",
    "guidesData.cell-clean.steps.2.title": "Zelle ausbauen",
    "guidesData.cell-clean.steps.3.detail": "1/3 Salzsäure + 2/3 Wasser in einem Kunststoffbehälter.",
    "guidesData.cell-clean.steps.3.title": "Verdünnte Säurelösung ansetzen",
    "guidesData.cell-clean.steps.3.warning": "IMMER Säure ins Wasser gießen, niemals umgekehrt. Handschuhe und Schutzbrille obligatorisch. Belüftung.",
    "guidesData.cell-clean.steps.4.detail": "Der Kalk löst sich. Nicht zu lange einwirken lassen.",
    "guidesData.cell-clean.steps.4.title": "10-15 Min. einweichen",
    "guidesData.cell-clean.steps.5.detail": "Mit klarem Wasser, bis der Geruch verschwindet.",
    "guidesData.cell-clean.steps.5.title": "Gründlich spülen",
    "guidesData.cell-clean.steps.6.detail": "Produktion am Display prüfen.",
    "guidesData.cell-clean.steps.6.title": "Wieder montieren und neu starten",
    "guidesData.cell-clean.summary": "Zelle des Salzelektrolysegeräts entkalken, um die Chlorproduktion aufrechtzuerhalten.",
    "guidesData.cell-clean.title": "Zelle des Elektrolysegeräts reinigen",

    # chlorine-shock
    "guidesData.chlorine-shock.steps.1.detail": "Eine Stoßbehandlung ist unwirksam, wenn pH > 7.6. Zuerst ausgleichen.",
    "guidesData.chlorine-shock.steps.1.title": "pH VORHER prüfen",
    "guidesData.chlorine-shock.steps.1.warning": "NIEMALS stoßen, ohne vorher den pH geprüft zu haben.",
    "guidesData.chlorine-shock.steps.2.detail": "Abends, keine Badenden, Filtration läuft.",
    "guidesData.chlorine-shock.steps.2.title": "Den richtigen Zeitpunkt wählen",
    "guidesData.chlorine-shock.steps.3.detail": "AQWELIA berechnet die Menge anhand Ihres Beckenvolumens.",
    "guidesData.chlorine-shock.steps.3.title": "Nach Volumen dosieren",
    "guidesData.chlorine-shock.steps.4.detail": "Niemals Stoßpulver direkt am Rand gießen.",
    "guidesData.chlorine-shock.steps.4.title": "In einem Eimer auflösen",
    "guidesData.chlorine-shock.steps.5.detail": "Chlor muss gut verteilt sein.",
    "guidesData.chlorine-shock.steps.5.title": "Mindestens 4 h filtern",
    "guidesData.chlorine-shock.steps.6.detail": "Freies Chlor vor dem Baden prüfen (muss < 3 mg/L sein).",
    "guidesData.chlorine-shock.steps.6.title": "8 h vor dem Baden warten",
    "guidesData.chlorine-shock.steps.6.warning": "Badeverbot für mindestens 8 h.",
    "guidesData.chlorine-shock.summary": "Stoßbehandlung: Indikationen, Dosierung, Sicherheit, Badeverzögerungen.",
    "guidesData.chlorine-shock.title": "Wann und wie man einen Chlorstoß durchführt",

    # cloudy-water
    "guidesData.cloudy-water.steps.1.detail": "80 % des trüben Wassers stammen von einem Filtrationsproblem. Druck, Dauer, Sauberkeit des Filters prüfen.",
    "guidesData.cloudy-water.steps.1.title": "Filtration prüfen",
    "guidesData.cloudy-water.steps.2.detail": "pH außerhalb des Bereichs oder niedriges Chlor = trübes Wasser.",
    "guidesData.cloudy-water.steps.2.title": "pH und Chlor testen",
    "guidesData.cloudy-water.steps.3.detail": "Verstopfter Filter = trübes Wasser.",
    "guidesData.cloudy-water.steps.3.title": "Filter reinigen oder rückspülen",
    "guidesData.cloudy-water.steps.4.detail": "Flockungsmittel verklumpt feine Partikel, damit der Filter sie zurückhalten kann.",
    "guidesData.cloudy-water.steps.4.title": "Flockungsmittel verwenden (bei Sandfilter)",
    "guidesData.cloudy-water.steps.4.warning": "Flockungsmittel nur mit Sandfilter. Nicht mit Kartusche.",
    "guidesData.cloudy-water.steps.5.detail": "Nach der Flockung bilden sich Ablagerungen am Boden: absaugen.",
    "guidesData.cloudy-water.steps.5.title": "24 h filtern, dann Ablagerungen absaugen",
    "guidesData.cloudy-water.summary": "Ursachen für trübes Wasser unterscheiden und die richtige Behandlung anwenden.",
    "guidesData.cloudy-water.title": "Trübes oder milchiges Wasser",

    # combined-chlorine
    "guidesData.combined-chlorine.steps.1.detail": "Ein starker Chlurgeruch ist KEIN Chlorüberschuss: Es sind Chloramine (gebundenes Chlor), Desinfektionsnebenprodukte.",
    "guidesData.combined-chlorine.steps.1.title": "Ursache verstehen",
    "guidesData.combined-chlorine.steps.2.detail": "Gebundenes Chlor = Gesamtchlor - freies Chlor. Wenn > 0.4 mg/L, Behandlung erforderlich.",
    "guidesData.combined-chlorine.steps.2.title": "Freies UND Gesamtchlor messen",
    "guidesData.combined-chlorine.steps.3.detail": "Die Stoßbehandlung bricht Chloramine auf und setzt aktives freies Chlor frei.",
    "guidesData.combined-chlorine.steps.3.title": "Eine Stoßbehandlung durchführen",
    "guidesData.combined-chlorine.steps.4.detail": "Ein hoher pH-Wert verschlimmert Chloramine.",
    "guidesData.combined-chlorine.steps.4.title": "pH prüfen",
    "guidesData.combined-chlorine.summary": "Chloramine verstehen und wie man sie loswird.",
    "guidesData.combined-chlorine.title": "Starker Chlurgeruch und brennende Augen",

    # faq-cya-high
    "guidesData.faq-cya-high.steps.1.detail": "Ein zu hoher CYA-Wert „blockiert“ das Chlor: Es ist vorhanden, aber inaktiv. Algengefahr trotz normalem Chlor.",
    "guidesData.faq-cya-high.steps.1.title": "Warum das ein Problem ist",
    "guidesData.faq-cya-high.steps.2.detail": "Einzige Lösung: Wasser verdünnen.",
    "guidesData.faq-cya-high.steps.2.title": "Es gibt kein Produkt, um den CYA zu senken",
    "guidesData.faq-cya-high.steps.3.detail": "Teilweises Ablassen, dann auffüllen.",
    "guidesData.faq-cya-high.steps.3.title": "20-30 % des Wassers erneuern",
    "guidesData.faq-cya-high.steps.4.detail": "Den neuen Wert prüfen.",
    "guidesData.faq-cya-high.steps.4.title": "Nach Erneuerung erneut testen",
    "guidesData.faq-cya-high.steps.5.detail": "Nicht stabilisiertes Chlor oder Elektrolysegerät bevorzugen.",
    "guidesData.faq-cya-high.steps.5.title": "In Zukunft: weniger stabilisiertes Chlor verwenden",
    "guidesData.faq-cya-high.summary": "Was tun, wenn der CYA 50-60 mg/L überschreitet?",
    "guidesData.faq-cya-high.title": "Mein Stabilisator (CYA) ist zu hoch",

    # faq-test-frequency
    "guidesData.faq-test-frequency.steps.1.detail": "Mindestens 2-mal pro Woche, bei starker Hitze häufiger.",
    "guidesData.faq-test-frequency.steps.1.title": "In der warmen Jahreszeit",
    "guidesData.faq-test-frequency.steps.2.detail": "Einmal alle 2 Wochen.",
    "guidesData.faq-test-frequency.steps.2.title": "In der kalten Jahreszeit (aktive Überwinterung)",
    "guidesData.faq-test-frequency.steps.3.detail": "Innerhalb von 3-24 h je nach Produkt erneut testen.",
    "guidesData.faq-test-frequency.steps.3.title": "Nach jeder Behandlung",
    "guidesData.faq-test-frequency.steps.4.detail": "Systematischer Test.",
    "guidesData.faq-test-frequency.steps.4.title": "Nach einem Gewitter",
    "guidesData.faq-test-frequency.steps.5.detail": "Immer.",
    "guidesData.faq-test-frequency.steps.5.title": "Vor dem Baden im Zweifel",
    "guidesData.faq-test-frequency.summary": "Empfohlene Häufigkeit nach Jahreszeit und Nutzung.",
    "guidesData.faq-test-frequency.title": "Wie oft das Wasser testen?",

    # filter-backwash
    "guidesData.filter-backwash.steps.1.detail": "Wenn der Druck 0.3-0.5 bar über dem Betriebsdruck steigt, oder alle 2-4 Wochen.",
    "guidesData.filter-backwash.steps.1.title": "Wann rückspülen?",
    "guidesData.filter-backwash.steps.2.detail": "IMMER die Pumpe ausschalten, bevor das Ventil bedient wird.",
    "guidesData.filter-backwash.steps.2.title": "Pumpe ausschalten",
    "guidesData.filter-backwash.steps.2.warning": "Elektrisches und materielles Risiko.",
    "guidesData.filter-backwash.steps.3.detail": "Das Mehrwegventil fest umdrehen.",
    "guidesData.filter-backwash.steps.3.title": "Ventil auf RÜCKSPÜLEN stellen",
    "guidesData.filter-backwash.steps.4.detail": "Das Wasser fließt in den Abfluss, bis es wieder klar ist.",
    "guidesData.filter-backwash.steps.4.title": "Pumpe 2-3 Min. wieder einschalten",
    "guidesData.filter-backwash.steps.5.detail": "Spülen verdichtet den Sand wieder und verhindert die Rückkehr von Schmutz.",
    "guidesData.filter-backwash.steps.5.title": "Ausschalten, Ventil auf SPÜLEN 30 s",
    "guidesData.filter-backwash.steps.6.detail": "Ventil wieder auf normale Filtration stellen.",
    "guidesData.filter-backwash.steps.6.title": "Zurück auf Position FILTERN",
    "guidesData.filter-backwash.summary": "Wann und wie man eine effektive Rückspülung durchführt.",
    "guidesData.filter-backwash.title": "Rückspülen (Gegenspülen) des Sandfilters",

    # filter-cartridge-clean
    "guidesData.filter-cartridge-clean.steps.1.detail": "Stromversorgung kappen.",
    "guidesData.filter-cartridge-clean.steps.1.title": "Pumpe ausschalten",
    "guidesData.filter-cartridge-clean.steps.1.warning": "Elektrische Sicherheit obligatorisch.",
    "guidesData.filter-cartridge-clean.steps.2.detail": "Filtergehäuse je nach Modell öffnen.",
    "guidesData.filter-cartridge-clean.steps.2.title": "Kartusche ausbauen",
    "guidesData.filter-cartridge-clean.steps.3.detail": "Sanfter Wasserstrahl, von oben nach unten, zwischen den Falten.",
    "guidesData.filter-cartridge-clean.steps.3.title": "Mit dem Strahl spülen",
    "guidesData.filter-cartridge-clean.steps.4.detail": "Alle 2-3 Reinigungen entfetten und entkalken.",
    "guidesData.filter-cartridge-clean.steps.4.title": "In Filterreiniger einweichen (optional)",
    "guidesData.filter-cartridge-clean.steps.5.detail": "Dichtungen richtig wieder einsetzen.",
    "guidesData.filter-cartridge-clean.steps.5.title": "Wieder montieren und neu starten",
    "guidesData.filter-cartridge-clean.summary": "Demontage und Spülen einer Filterkartusche.",
    "guidesData.filter-cartridge-clean.title": "Kartuschenfilter reinigen",

    # getting-started-spa
    "guidesData.getting-started-spa.steps.1.detail": "Das Wasser kippt schnell. Häufigere Tests.",
    "guidesData.getting-started-spa.steps.1.title": "Geringeres Volumen = schnelle Reaktionen",
    "guidesData.getting-started-spa.steps.2.detail": "Brom ist bei Hitze stabiler und weniger geruchsintensiv.",
    "guidesData.getting-started-spa.steps.2.title": "Brom statt Chlor bevorzugen",
    "guidesData.getting-started-spa.steps.3.detail": "Der pH-Wert ändert sich mit der Temperatur. Bei Badetemperatur testen.",
    "guidesData.getting-started-spa.steps.3.title": "Temperatur und pH",
    "guidesData.getting-started-spa.steps.4.detail": "Notwendiger als im Pool.",
    "guidesData.getting-started-spa.steps.4.title": "Wöchentliche Stoßbehandlung",
    "guidesData.getting-started-spa.steps.5.detail": "Alle 3-4 Monate je nach Nutzung.",
    "guidesData.getting-started-spa.steps.5.title": "Regelmäßiges Ablassen",
    "guidesData.getting-started-spa.summary": "Das Spa hat eigene Regeln: warmes Wasser, geringeres Volumen, Brom statt Chlor.",
    "guidesData.getting-started-spa.title": "Besonderheiten des Spas",

    # getting-started
    "guidesData.getting-started.steps.1.detail": "Unverzichtbar für jede Dosierung. AQWELIA berechnet es aus den Maßen.",
    "guidesData.getting-started.steps.1.title": "Poolvolumen kennen",
    "guidesData.getting-started.steps.10.detail": "AQWELIA führt die Historie für Sie.",
    "guidesData.getting-started.steps.10.title": "Ein Logbuch führen",
    "guidesData.getting-started.steps.2.detail": "Der Parameter Nr. 1. Alles beginnt hier.",
    "guidesData.getting-started.steps.2.title": "pH verstehen",
    "guidesData.getting-started.steps.3.detail": "Frei, gesamt, gebunden. AQWELIA führt Sie.",
    "guidesData.getting-started.steps.3.title": "Chlor verstehen",
    "guidesData.getting-started.steps.4.detail": "Die Hälfte der Wassertemperatur in Stunden.",
    "guidesData.getting-started.steps.4.title": "Ausreichend filtern",
    "guidesData.getting-started.steps.5.detail": "Bei starker Hitze häufiger.",
    "guidesData.getting-started.steps.5.title": "1-2× pro Woche testen",
    "guidesData.getting-started.steps.6.detail": "Regelmäßiges Rückspülen oder Spülen.",
    "guidesData.getting-started.steps.6.title": "Filter warten",
    "guidesData.getting-started.steps.7.detail": "Zu niedrig = Pumpe gefährdet; zu hoch = unwirksamer Skimmer.",
    "guidesData.getting-started.steps.7.title": "Wasserstand überwachen",
    "guidesData.getting-started.steps.8.detail": "Verhindert Algen und Ablagerungen.",
    "guidesData.getting-started.steps.8.title": "Wasserlinie bürsten und reinigen",
    "guidesData.getting-started.steps.9.detail": "Gewitter, Hitzewelle, Urlaub: Vorbeugen statt heilen.",
    "guidesData.getting-started.steps.9.title": "Wetter vorausplanen",
    "guidesData.getting-started.summary": "Die ersten 10 Dinge, die man als neuer Poolbesitzer wissen muss.",
    "guidesData.getting-started.title": "Erste Schritte mit dem Pool",

    # green-water
    "guidesData.green-water.steps.1.detail": "Grünes Wasser ist fast immer auf fehlendes Desinfektionsmittel oder einen unausgeglichenen pH zurückzuführen.",
    "guidesData.green-water.steps.1.title": "pH und freies Chlor messen",
    "guidesData.green-water.steps.1.warning": "Niemals Anti-Algen zugeben, bevor der pH ausgeglichen ist.",
    "guidesData.green-water.steps.2.detail": "Wenn pH > 7.4, verdünntes pH- zugeben. 2-3 h Filtration abwarten.",
    "guidesData.green-water.steps.2.tip": "Chlor ist bei pH 7.2 10-mal so wirksam wie bei pH 8.0.",
    "guidesData.green-water.steps.2.title": "pH ausgleichen (7.0-7.4)",
    "guidesData.green-water.steps.3.detail": "Ablösen der Algen hilft der Behandlung, einzudringen.",
    "guidesData.green-water.steps.3.title": "Wände und Boden bürsten",
    "guidesData.green-water.steps.4.detail": "Stoßchlor (nach pH-Ausgleich). Durchgehende Filtration 24 h.",
    "guidesData.green-water.steps.4.title": "Eine Stoßbehandlung durchführen",
    "guidesData.green-water.steps.4.warning": "Badeverbot mindestens 8 h nach der Stoßbehandlung.",
    "guidesData.green-water.steps.5.detail": "Nach der Stoßbehandlung verhindert Anti-Algen erneutes Wachstum.",
    "guidesData.green-water.steps.5.title": "Kuratives Anti-Algen zugeben",
    "guidesData.green-water.steps.6.detail": "Die Filtration ist genauso wichtig wie die Chemikalien.",
    "guidesData.green-water.steps.6.title": "24-48 h durchgehend filtern",
    "guidesData.green-water.steps.7.detail": "pH und Chlor prüfen. Wenn das Wasser noch grün ist, muss der Filter eventuell gereinigt werden.",
    "guidesData.green-water.steps.7.title": "Nach 24 h erneut testen",
    "guidesData.green-water.summary": "Ursache für grünes Wasser erkennen und Schritt für Schritt ohne Überdosierung behandeln.",
    "guidesData.green-water.title": "Grünes Wasser: Diagnose und Aktionsplan",

    # guide_*
    "guidesData.guide_eq1_summary": "Wann und wie man eine effektive Rückspülung durchführt.",
    "guidesData.guide_eq1_title": "Rückspülen (Gegenspülen) des Sandfilters",
    "guidesData.guide_eq2_summary": "Demontage und Spülen einer Filterkartusche.",
    "guidesData.guide_eq2_title": "Kartuschenfilter reinigen",
    "guidesData.guide_gs1_summary": "Die ersten 10 Dinge, die man als neuer Poolbesitzer wissen muss.",
    "guidesData.guide_gs1_title": "Erste Schritte mit dem Pool",
    "guidesData.guide_pb1_summary": "Ursache für grünes Wasser erkennen und Schritt für Schritt ohne Überdosierung behandeln.",
    "guidesData.guide_pb1_title": "Grünes Wasser: Diagnose und Aktionsplan",
    "guidesData.guide_pb2_summary": "Ursachen für trübes Wasser unterscheiden und die richtige Behandlung anwenden.",
    "guidesData.guide_pb2_title": "Trübes oder milchiges Wasser",
    "guidesData.guide_pb3_summary": "Chloramine verstehen und wie man sie loswird.",
    "guidesData.guide_pb3_title": "Starker Chlurgeruch und brennende Augen",
    "guidesData.guide_pr1_summary": "Stoßbehandlung: Indikationen, Dosierung, Sicherheit, Badeverzögerungen.",
    "guidesData.guide_pr1_title": "Wann und wie man einen Chlorstoß durchführt",
    "guidesData.guide_tr1_summary": "Prinzip, Salzgehalt, Produktion, laufende Wartung.",
    "guidesData.guide_tr1_title": "Das Salzelektrolysegerät verstehen",

    # levels
    "guidesData.level_beginner": "Anfänger",
    "guidesData.level_expert": "Experte",
    "guidesData.level_intermediate": "Fortgeschritten",

    # ph-control
    "guidesData.ph-control.steps.1.detail": "Alles beginnt mit dem pH: Chlorwirksamkeit, Badekomfort, Geräteschutz.",
    "guidesData.ph-control.steps.1.title": "Der pH hat Vorrang",
    "guidesData.ph-control.steps.2.detail": "Näher an 7.2 = optimales Chlor.",
    "guidesData.ph-control.steps.2.title": "Idealbereich 7.0-7.4",
    "guidesData.ph-control.steps.3.detail": "Ein niedriger TAC macht den pH instabil.",
    "guidesData.ph-control.steps.3.title": "Bei Instabilität TAC vor dem pH anpassen",
    "guidesData.ph-control.steps.4.detail": "Den pH nie um mehr als 0.3 auf einmal verändern.",
    "guidesData.ph-control.steps.4.title": "In kleinen Mengen dosieren",
    "guidesData.ph-control.steps.5.detail": "Die Mischung muss homogen sein.",
    "guidesData.ph-control.steps.5.title": "2-3 h filtern, dann erneut testen",
    "guidesData.ph-control.summary": "Warum der pH der Parameter Nr. 1 ist und wie man ihn anpasst.",
    "guidesData.ph-control.title": "Den pH meistern",

    # product-safety
    "guidesData.product-safety.steps.1.detail": "Chlor + Säure = tödliches giftiges Gas. Immer getrennt verdünnen.",
    "guidesData.product-safety.steps.1.title": "NIEMALS Produkte mischen",
    "guidesData.product-safety.steps.1.warning": "Absolute Überlebensregel.",
    "guidesData.product-safety.steps.2.detail": "Niemals Wasser ins Säureprodukt (Spritzgefahr).",
    "guidesData.product-safety.steps.2.title": "Immer Produkt zum Wasser geben",
    "guidesData.product-safety.steps.3.detail": "Besonders bei Säuren und konzentriertem Chlor.",
    "guidesData.product-safety.steps.3.title": "Handschuhe und Schutzbrille tragen",
    "guidesData.product-safety.steps.4.detail": "Säuren und Chlor trennen. Außerhalb der Reichweite von Kindern.",
    "guidesData.product-safety.steps.4.title": "Trocken, kühl, belüftet lagern",
    "guidesData.product-safety.steps.5.detail": "Jedes Produkt hat seine Dosierungs- und Anwendungsregeln.",
    "guidesData.product-safety.steps.5.title": "Gebrauchsanweisungen beachten",
    "guidesData.product-safety.steps.6.detail": "Kein Erbrechen herbeiführen, sofort ärztliche Hilfe aufsuchen.",
    "guidesData.product-safety.steps.6.title": "Im Vorfallsfall: Notruf oder Giftnotruf anrufen",
    "guidesData.product-safety.summary": "Die goldenen Regeln für die Handhabung und Lagerung von Poolprodukten.",
    "guidesData.product-safety.title": "Sicherheit bei Chemieprodukten",

    # reminders
    "guidesData.reminder_after_storm_action": "Chlor und pH testen.",
    "guidesData.reminder_after_storm_detail": "Das Gewitter könnte Ihr Wasser aus dem Gleichgewicht gebracht haben.",
    "guidesData.reminder_after_storm_title": "Nach dem Gewitter",
    "guidesData.reminder_algae_prevent_action": "Aktion für algae_prevent",
    "guidesData.reminder_algae_prevent_detail": "Beschreibung für algae_prevent",
    "guidesData.reminder_algae_prevent_title": "Algen vorbeugen",
    "guidesData.reminder_cell_clean_action": "Aktion für cell_clean",
    "guidesData.reminder_cell_clean_detail": "Beschreibung für cell_clean",
    "guidesData.reminder_cell_clean_title": "Zelle reinigen",
    "guidesData.reminder_chlorine_check_action": "Aktion für chlorine_check",
    "guidesData.reminder_chlorine_check_detail": "Beschreibung für chlorine_check",
    "guidesData.reminder_chlorine_check_title": "Chlor prüfen",
    "guidesData.reminder_filter_clean": "Filterreinigung",
    "guidesData.reminder_filter_clean_action": "Eine Rückspülung (Gegenspülen) durchführen.",
    "guidesData.reminder_filter_clean_desc": "Rückspülen des Sandfilters empfohlen.",
    "guidesData.reminder_filter_clean_detail": "Rückspülen des Sandfilters empfohlen.",
    "guidesData.reminder_filter_clean_title": "Filterreinigung",
    "guidesData.reminder_open_pool_action": "Aktion für open_pool",
    "guidesData.reminder_open_pool_detail": "Beschreibung für open_pool",
    "guidesData.reminder_open_pool_title": "Pool öffnen",
    "guidesData.reminder_ph_check_action": "Aktion für ph_check",
    "guidesData.reminder_ph_check_detail": "Beschreibung für ph_check",
    "guidesData.reminder_ph_check_title": "pH prüfen",
    "guidesData.reminder_retest_after_product_action": "Aktion für retest_after_product",
    "guidesData.reminder_retest_after_product_detail": "Beschreibung für retest_after_product",
    "guidesData.reminder_retest_after_product_title": "Nach Produktdosierung erneut testen",
    "guidesData.reminder_shock_treatment_action": "Aktion für shock_treatment",
    "guidesData.reminder_shock_treatment_detail": "Beschreibung für shock_treatment",
    "guidesData.reminder_shock_treatment_title": "Stoßbehandlung",
}


def main():
    src_path = "/home/z/my-project/.tmp/worksheets/de-part1.json"
    out_path = "/home/z/my-project/.tmp/translated/de-part1.json"

    src = json.load(open(src_path))
    src_keys = set(src.keys())
    t_keys = set(T.keys())

    missing = src_keys - t_keys
    extra = t_keys - src_keys

    print(f"Source keys: {len(src_keys)}")
    print(f"Translated keys: {len(t_keys)}")
    print(f"Missing from T: {len(missing)}")
    if missing:
        for k in sorted(missing)[:30]:
            print(f"  MISSING: {k}")
    print(f"Extra in T: {len(extra)}")
    if extra:
        for k in sorted(extra)[:30]:
            print(f"  EXTRA: {k}")

    # Use only src keys order
    out = {}
    for k in src.keys():
        if k in T:
            out[k] = T[k]
        else:
            out[k] = "__TRANSLATE_NEEDED__"

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2, sort_keys=False)
        f.write("\n")
    print(f"\nWrote {len(out)} keys to {out_path}")


if __name__ == "__main__":
    main()
