#!/usr/bin/env python3
"""Build it-part1.json: Italian translations for AQWELIA i18n keys (part 1)."""
import json

translations = {
    # ===== admin.* =====
    "admin.accessDenied": "Accesso negato.",
    "admin.analyticsComingSoonFull": "Dati dettagliati in arrivo — Connessione API /api/analytics",
    "admin.backToSiteArrow": "← Torna al sito",
    "admin.bannerDefaultText": "☀️ Estate 2026 — Approfitta del -20% sul piano Lagoon!",
    "admin.bannerDescFull": "Personalizza il banner promozionale in alto nell'app. Ideale per stagioni, promozioni, annunci.",
    "admin.bannerSavedToast": "Banner salvato",
    "admin.contentComingSoonFull": "Modulo in arrivo — Editor di contenuti WYSIWYG per landing page, guide, email...",
    "admin.delete": "Elimina",
    "admin.learnMore": "Scopri di più →",
    "admin.popupDefaultBody": "Descrizione della promo...",
    "admin.popupDefaultCta": "Approfittane",
    "admin.popupDefaultTitle": "Nuovo popup promo",
    "admin.popupDescFull": "Crea popup che appaiono in base a trigger. Caricamento immagini promo in arrivo.",
    "admin.popupImagePlaceholder": "URL immagine promo (in arrivo: caricamento)",
    "admin.popupTrigger": "Trigger",
    "admin.popupsSavedToast": "Popup salvati",
    "admin.title": "AQWELIA Admin",
    "admin.usersComingSoonFull": "Modulo in arrivo — Lista utenti, gestione abbonamenti, supporto...",
    "admin.usersDescFull": "Gestisci utenti, abbonamenti e accessi.",
    "admin.wrongPassword": "Password errata",

    # ===== auth.* =====
    "auth.emailLabel": "Email",
    "auth.passwordLabel": "Password",

    # ===== common.* =====
    "common.email": "Email",
    "common.password": "Password",

    # ===== diagnostic.* =====
    "diagnostic.filtrationHoursShort": "Filtr. {n}h",
    "diagnostic.offlineTitle": "Offline",
    "diagnostic.typeOtherDesc": "Robot, skimmer…",
    "diagnostic.uploadHint": "JPG / PNG / WEBP — max 6 MB",

    # ===== diagnosticActionPlan.* =====
    "diagnosticActionPlan.afterTreatment": "Dopo il trattamento",
    "diagnosticActionPlan.cancelValidation": "Annulla la validazione",
    "diagnosticActionPlan.cloudyS1I1": "Spegni la pompa prima di qualsiasi intervento di sicurezza.",
    "diagnosticActionPlan.cloudyS1I2": "Controlla la pressione al manometro: se > 0.3 bar sopra il valore iniziale → pulire.",
    "diagnosticActionPlan.cloudyS1I3": "Filtro a sabbia: fai un backwash (contro-lavaggio) di 2-3 min poi risciacquo di 30 s.",
    "diagnosticActionPlan.cloudyS1I4": "Filtro a cartuccia: smonta, risciacqua con getto, sostituisci se > 2 anni.",
    "diagnosticActionPlan.cloudyS1I5": "Svuota e pulisci i cestelli dello skimmer e del pre-filtro della pompa.",
    "diagnosticActionPlan.cloudyS1I6": "Riavvia e verifica che la portata sia buona (ugelli di mandata).",
    "diagnosticActionPlan.cloudyS1Intro": "L'acqua torbida deriva quasi sempre da una filtrazione inefficace. Si inizia sempre da qui.",
    "diagnosticActionPlan.cloudyS1Title": "1. Verificare e pulire la filtrazione",
    "diagnosticActionPlan.cloudyS2Dosage": "~{qty} g di pH- / 0.1 unità (per {volume} m³)",
    "diagnosticActionPlan.cloudyS2I1": "Misura il pH a 30 cm di profondità.",
    "diagnosticActionPlan.cloudyS2I2": "Se pH > 7.4 → aggiungi pH-; se pH < 7.0 → aggiungi pH+.",
    "diagnosticActionPlan.cloudyS2I3": "Riferimento: ~{qty} g di pH- per abbassare di 0.1 unità su {volume} m³.",
    "diagnosticActionPlan.cloudyS2I4": "Diluisci in un secchio di acqua della piscina, versa davanti agli ugelli di mandata.",
    "diagnosticActionPlan.cloudyS2I5": "Filtrazione in funzione per 2h prima di un nuovo test.",
    "diagnosticActionPlan.cloudyS2Intro": "Un pH squilibrato favorisce la torbidità e riduce l'efficacia del cloro.",
    "diagnosticActionPlan.cloudyS2Product": "pH- o pH+ (secondo la tua misurazione)",
    "diagnosticActionPlan.cloudyS2Title": "2. Misurare e regolare il pH",
    "diagnosticActionPlan.cloudyS3Dosage": "{qty} mL di flocculante (per {volume} m³)",
    "diagnosticActionPlan.cloudyS3I1": "⚠ NON usare MAI flocculante con filtro a cartuccia (intasamento).",
    "diagnosticActionPlan.cloudyS3I2": "Dosaggio: ~5 mL di flocculante liquido per m³.",
    "diagnosticActionPlan.cloudyS3I3": "Per {volume} m³: {qty} mL di flocculante.",
    "diagnosticActionPlan.cloudyS3I4": "Versa davanti agli ugelli di mandata, filtrazione in funzione 1h.",
    "diagnosticActionPlan.cloudyS3I5": "Poi spegni la filtrazione 12h per lasciare decantare.",
    "diagnosticActionPlan.cloudyS3I6": "I fiocchi cadono sul fondo — aspirali con robot o aspiratore manuale.",
    "diagnosticActionPlan.cloudyS3Intro": "Il flocculante aggrega le particelle fini in fiocchi che il filtro può trattenere. ⚠ Solo per filtro a sabbia.",
    "diagnosticActionPlan.cloudyS3Product": "Flocculante liquido (solo filtro a sabbia)",
    "diagnosticActionPlan.cloudyS3Title": "3. Aggiungere un flocculante (se filtro a sabbia)",
    "diagnosticActionPlan.cloudyS4I1": "Riavvia la pompa in modalità forzata dopo l'aspirazione dei fiocchi.",
    "diagnosticActionPlan.cloudyS4I2": "Monitora la pressione del filtro — backwash se aumenta.",
    "diagnosticActionPlan.cloudyS4I3": "Controlla il cestello dello skimmer ogni 4h.",
    "diagnosticActionPlan.cloudyS4I4": "Dopo 12h, l'acqua dovrebbe tornare limpida.",
    "diagnosticActionPlan.cloudyS4Intro": "Lascia la filtrazione in funzione 12h per chiarire l'acqua dopo flocculazione/aspirazione.",
    "diagnosticActionPlan.cloudyS4Title": "4. Filtrazione continua 12h",
    "diagnosticActionPlan.cloudyS5I1": "Misura il pH (obiettivo: 7.0 - 7.4).",
    "diagnosticActionPlan.cloudyS5I2": "Misura il cloro libero (obiettivo: 1 - 3 mg/L).",
    "diagnosticActionPlan.cloudyS5I3": "Inserisci i tuoi valori qui sotto — saranno salvati nel tuo diario.",
    "diagnosticActionPlan.cloudyS5I4": "Se i valori sono OK e l'acqua è limpida → problema risolto.",
    "diagnosticActionPlan.cloudyS5Intro": "Verifica che l'acqua sia equilibrata e che il cloro sia attivo.",
    "diagnosticActionPlan.cloudyS5Title": "5. Nuovo test dell'acqua",

    "diagnosticActionPlan.compAlgae1Desc": "Le alghe sono ancora presenti nonostante il primo trattamento. Ripeti il trattamento shock con 1.5x la dose precedente. Verifica che il pH sia tra 7.0-7.4 PRIMA. Preferisci un cloro shock di marca diversa (le alghe possono sviluppare resistenza).",
    "diagnosticActionPlan.compAlgae1Reason": "Le alghe possono essere resistenti. È necessaria una dose più forte e un prodotto diverso.",
    "diagnosticActionPlan.compAlgae1Title": "{n}. Raddoppiare la dose di trattamento shock",
    "diagnosticActionPlan.compAlgae2Desc": "Conta il numero di ore di filtrazione al giorno. Per acqua verde, filtra almeno 12h/24. Idealmente 24h/24 per 3 giorni consecutivi.",
    "diagnosticActionPlan.compAlgae2Reason": "Una filtrazione insufficiente impedisce di eliminare le alghe morte e di chiarire l'acqua.",
    "diagnosticActionPlan.compAlgae2Title": "{n}. Verificare la durata della filtrazione",
    "diagnosticActionPlan.compAlgae3Desc": "Se hai un filtro a sabbia, fai un backwash (contro-lavaggio) di 3 minuti seguito da un risciacquo di 30s. Se è una cartuccia, smontala e puliscila con getto. Un filtro intasato non trattiene le alghe e le rimanda in vasca.",
    "diagnosticActionPlan.compAlgae3Reason": "Il filtro può essere saturo di alghe dopo il primo trattamento.",
    "diagnosticActionPlan.compAlgae3Title": "{n}. Pulire il filtro a fondo",
    "diagnosticActionPlan.compCloudy1Desc": "L'acqua è ancora torbida. Versa un flocculante LIQUIDO (non in calza) direttamente davanti agli ugelli di mandata, filtrazione in funzione. Filtra 1h, poi spegni 12h per lasciare decantare. Le particelle si aggregano e cadono sul fondo.",
    "diagnosticActionPlan.compCloudy1Reason": "Il flocculante aggrega le particelle fini che il filtro non trattiene.",
    "diagnosticActionPlan.compCloudy1Title": "{n}. Aggiungere un flocculante liquido",
    "diagnosticActionPlan.compCloudy2Desc": "Dopo 12h di decantazione, i detriti saranno sul fondo. Aspira lentamente in posizione 'scarico' (waste) per non rimandarli nel filtro. Rimetti la valvola in filtrazione solo dopo aver finito l'aspirazione.",
    "diagnosticActionPlan.compCloudy2Reason": "I fiocchi sono troppo pesanti per il filtro normale.",
    "diagnosticActionPlan.compCloudy2Title": "{n}. Aspirare il fondo dopo flocculazione",
    "diagnosticActionPlan.compCloudy3Desc": "Se l'acqua resta torbida nonostante flocculazione + filtrazione: la sabbia/cartuccia potrebbe essere da sostituire. La sabbia si cambia ogni 5-7 anni, la cartuccia ogni 2 anni. Un mezzo usurato non trattiene più le particelle fini.",
    "diagnosticActionPlan.compCloudy3Reason": "Un filtro a fine vita è una causa frequente di acqua torbida persistente.",
    "diagnosticActionPlan.compCloudy3Title": "{n}. Verificare il mezzo filtrante",
    "diagnosticActionPlan.compFallback1Desc": "L'acqua sta migliorando ma non è ancora perfetta. Lascia la filtrazione in funzione altre 24h continue. Monitora la pressione del filtro (backwash se aumenta di +0.3 bar).",
    "diagnosticActionPlan.compFallback1Reason": "Il trattamento è in corso, dagli tempo per agire.",
    "diagnosticActionPlan.compFallback1Title": "1. Continuare la filtrazione per altre 24h",
    "diagnosticActionPlan.compFallback2Desc": "Rifai un test completo (pH, cloro, TAC) tra 24h e fai una nuova foto per verificare. Se il punteggio di soddisfazione ristagna, considera di svuotare 20-30% dell'acqua per ripartire da una base sana.",
    "diagnosticActionPlan.compFallback2Reason": "Bisogna dare tempo al trattamento di fare effetto prima di concludere un fallimento.",
    "diagnosticActionPlan.compFallback2Title": "2. Nuovo test tra 24h",
    "diagnosticActionPlan.compNewIssuesDesc": "Nuovo(i) problema(i) apparso(i): {issues}. Analizza la causa probabile (sovraclorazione, sovradosaggio di flocculante, precipitazione di calcare, ecc.) prima di agire. In caso di dubbio, rifai un test completo pH/cloro/TAC/TH.",
    "diagnosticActionPlan.compNewIssuesReason": "Alcuni trattamenti possono creare nuovi squilibri. Vanno corretti prima che peggiorino la situazione.",
    "diagnosticActionPlan.compNewIssuesTitle": "{n}. Trattare i nuovi problemi rilevati",
    "diagnosticActionPlan.dosage": "Dosaggio",
    "diagnosticActionPlan.fieldChlorineLabel": "Cloro libero misurato",
    "diagnosticActionPlan.fieldPhLabel": "Inserisci il pH misurato",
    "diagnosticActionPlan.fieldTacLabel": "TAC misurato",
    "diagnosticActionPlan.genericInstruction1Default": "Segui i consigli dell'IA mostrati sopra.",
    "diagnosticActionPlan.genericInstruction2": "Misura il pH prima di qualsiasi trattamento (obiettivo: 7.0 - 7.4).",
    "diagnosticActionPlan.genericInstruction2_1": "Attendi almeno 24h di filtrazione continua.",
    "diagnosticActionPlan.genericInstruction2_2": "Fai una nuova foto nelle stesse condizioni (stesso punto, stessa illuminazione).",
    "diagnosticActionPlan.genericInstruction2_3": "Clicca su Verifica risultato in fondo al piano.",
    "diagnosticActionPlan.genericInstruction2_4": "L'IA confronterà e dirà se il problema è risolto.",
    "diagnosticActionPlan.genericInstruction3": "Regola se necessario con pH- o pH+.",
    "diagnosticActionPlan.genericInstruction4": "Registra la tua misurazione qui sotto per lo storico.",
    "diagnosticActionPlan.genericInstruction5": "Verifica che la filtrazione funzioni almeno 8h/giorno.",
    "diagnosticActionPlan.genericIntro1": "L'IA ha identificato un problema ma senza schema tipico (acqua verde / torbida). Segui il consiglio sotto.",
    "diagnosticActionPlan.genericIntro2": "Dopo aver applicato i consigli, fai una nuova foto per confermare la risoluzione.",
    "diagnosticActionPlan.genericProduct": "Secondo consiglio",
    "diagnosticActionPlan.genericTitle1": "1. Seguire il consiglio",
    "diagnosticActionPlan.genericTitle2": "2. Verificare il risultato (24h)",

    "diagnosticActionPlan.greenS1Dosage": "~{qty} g di pH- / 0.1 unità da abbassare (piscina di {volume} m³)",
    "diagnosticActionPlan.greenS1I1": "Prendi il kit di test (gocce o strisce) o un tester elettronico.",
    "diagnosticActionPlan.greenS1I2": "Preleva un campione d'acqua a 30 cm di profondità, lontano dagli ugelli di mandata.",
    "diagnosticActionPlan.greenS1I3": "Misura il pH attuale e annotalo sotto.",
    "diagnosticActionPlan.greenS1I4": "Se pH > 7.4 → aggiungi pH- (acido). Se pH < 7.0 → aggiungi pH+ (base).",
    "diagnosticActionPlan.greenS1I5": "Dosaggio di riferimento: ~{qty} g di pH- per abbassare di 0.1 unità su {volume} m³.",
    "diagnosticActionPlan.greenS1I6": "Diluisci il prodotto in un secchio di acqua della piscina, mai puro direttamente.",
    "diagnosticActionPlan.greenS1I7": "Versa lentamente davanti agli ugelli di mandata, filtrazione in funzione.",
    "diagnosticActionPlan.greenS1I8": "Attendi 2 ore con la filtrazione in funzione prima di un nuovo test.",
    "diagnosticActionPlan.greenS1Intro": "Il pH deve essere tra 7.0 e 7.4 PRIMA di qualsiasi trattamento. Un pH errato rende il cloro inefficace (fino a -90%).",
    "diagnosticActionPlan.greenS1Product": "pH- o pH+ (secondo la tua misurazione)",
    "diagnosticActionPlan.greenS1Title": "1. Misurare e regolare il pH",
    "diagnosticActionPlan.greenS2Dosage": "Riaggiustamento: metà della dose iniziale (~{qty} g max per {volume} m³)",
    "diagnosticActionPlan.greenS2I1": "Preleva un nuovo campione d'acqua a 30 cm di profondità.",
    "diagnosticActionPlan.greenS2I2": "Misura di nuovo il pH.",
    "diagnosticActionPlan.greenS2I3": "Se pH tra 7.0 e 7.4 → ✅ passa alla fase successiva (trattamento shock).",
    "diagnosticActionPlan.greenS2I4": "Se pH ancora troppo alto/basso → regola di nuovo con la METÀ della dose precedente.",
    "diagnosticActionPlan.greenS2I5": "Nuovo test 1h dopo questo secondo aggiustamento.",
    "diagnosticActionPlan.greenS2Intro": "Dopo 2h di filtrazione, il pH ha avuto tempo di stabilizzarsi. Verifica che ora sia nel range target.",
    "diagnosticActionPlan.greenS2Product": "pH- o pH+ (dose ridotta se riaggiusti)",
    "diagnosticActionPlan.greenS2Title": "2. Nuovo test del pH (dopo 2h)",

    "diagnosticActionPlan.greenS3Dosage": "{qty} g di cloro shock (per {volume} m³)",
    "diagnosticActionPlan.greenS3I1": "⚠ Verifica che il pH sia corretto (fasi 1-2). Altrimenti lo shock sarà inefficace.",
    "diagnosticActionPlan.greenS3I2": "Calcola la dose curativa: circa 10 g di cloro shock per m³.",
    "diagnosticActionPlan.greenS3I3": "Per la tua piscina di {volume} m³: {qty} g di cloro shock (cioè ~{tablets} pastiglie da 20 g).",
    "diagnosticActionPlan.greenS3I4": "Preferisci la sera, senza bagnanti, filtrazione in funzione.",
    "diagnosticActionPlan.greenS3I5": "Diluisci il cloro in polvere/granuli in un secchio di acqua della piscina.",
    "diagnosticActionPlan.greenS3I6": "Versa davanti agli ugelli di mandata, mai nello skimmer.",
    "diagnosticActionPlan.greenS3I7": "🚫 DIVIETO DI BALNEAZIONE per almeno 8 ore.",
    "diagnosticActionPlan.greenS3Intro": "Il cloro shock distrugge alghe, batteri e virus. È la fase più importante contro l'acqua verde.",
    "diagnosticActionPlan.greenS3Product": "Cloro shock (65% attivo, granuli o pastiglie)",
    "diagnosticActionPlan.greenS3Title": "3. Trattamento shock al cloro",

    "diagnosticActionPlan.greenS4Dosage": "{qty} mL di anti-alghe (per {volume} m³)",
    "diagnosticActionPlan.greenS4I1": "Attendi almeno 2h dopo il trattamento shock (non mescolare mai direttamente).",
    "diagnosticActionPlan.greenS4I2": "Dosaggio curativo: ~20 mL di anti-alghe per m³.",
    "diagnosticActionPlan.greenS4I3": "Per {volume} m³: {qty} mL di anti-alghe (cioè {liters} L).",
    "diagnosticActionPlan.greenS4I4": "Versa direttamente davanti agli ugelli di mandata, filtrazione in funzione.",
    "diagnosticActionPlan.greenS4I5": "Spazzola le pareti subito dopo (vedi fase successiva) per staccare le alghe.",
    "diagnosticActionPlan.greenS4Intro": "L'anti-alghe completa il cloro distruggendo le alghe resistenti e impedendo la ricrescita.",
    "diagnosticActionPlan.greenS4Product": "Anti-alghe curativo",
    "diagnosticActionPlan.greenS4Title": "4. Anti-alghe (preventivo curativo)",

    "diagnosticActionPlan.greenS5I1": "Usa una spazzola adatta al tuo rivestimento: spazzola in nylon per liner/coque, spazzola in acciaio per calcestruzzo.",
    "diagnosticActionPlan.greenS5I2": "🚫 Mai usare spazzola metallica su liner o membrana armata — la bucheresti.",
    "diagnosticActionPlan.greenS5I3": "Spazza dall'alto verso il basso, in sezioni di 1 m².",
    "diagnosticActionPlan.greenS5I4": "Insisti sugli angoli, gradini, ugelli, scale e la linea dell'acqua.",
    "diagnosticActionPlan.greenS5I5": "Spazza anche il fondo se accessibile (asta telescopica).",
    "diagnosticActionPlan.greenS5I6": "È faticoso (15-30 min) ma INDISPENSABILE — senza le alghe tornano in 48h.",
    "diagnosticActionPlan.greenS5Intro": "La spazzolatura stacca le alghe incrostate. Senza questa fase, il trattamento chimico non basta.",
    "diagnosticActionPlan.greenS5Title": "5. Spazzolare le pareti e il fondo",

    "diagnosticActionPlan.greenS6I1": "Imposta la pompa in modalità forzata (24h/24) — nessun programma orario.",
    "diagnosticActionPlan.greenS6I2": "Controlla la pressione del manometro del filtro.",
    "diagnosticActionPlan.greenS6I3": "Se la pressione sale > 0.3 bar sopra il normale → fai un backwash (contro-lavaggio).",
    "diagnosticActionPlan.greenS6I4": "Pulisci il pre-filtro della pompa (cestello) se pieno di detriti.",
    "diagnosticActionPlan.greenS6I5": "Svuota gli skimmer regolarmente durante queste 24h.",
    "diagnosticActionPlan.greenS6I6": "Per un filtro a cartuccia: risciacquala a metà percorso se la portata cala.",
    "diagnosticActionPlan.greenS6Intro": "La filtrazione deve funzionare 24h senza interruzione per eliminare le alghe morte e le particelle.",
    "diagnosticActionPlan.greenS6Title": "6. Filtrazione continua 24h",

    "diagnosticActionPlan.greenS7I1": "Preleva un campione a 30 cm di profondità.",
    "diagnosticActionPlan.greenS7I2": "Misura il pH (obiettivo: 7.0 - 7.4).",
    "diagnosticActionPlan.greenS7I3": "Misura il cloro libero (obiettivo: 1 - 3 mg/L).",
    "diagnosticActionPlan.greenS7I4": "Misura il TAC / alcalinità (obiettivo: 80 - 120 mg/L).",
    "diagnosticActionPlan.greenS7I5": "Inserisci i tuoi 3 valori qui sotto — saranno salvati nel tuo diario.",
    "diagnosticActionPlan.greenS7I6": "Se tutto è nei range → puoi nuotare di nuovo. Altrimenti, regola.",
    "diagnosticActionPlan.greenS7Intro": "Dopo 24h di filtrazione, fai un test completo per verificare che l'acqua sia sana ed equilibrata.",
    "diagnosticActionPlan.greenS7Title": "7. Nuovo test completo dell'acqua",

    "diagnosticActionPlan.immediate": "Immediato",
    "diagnosticActionPlan.initialState": "Stato iniziale",
    "diagnosticActionPlan.instructionsTitle": "Istruzioni dettagliate",
    "diagnosticActionPlan.lastMeasureChlorine": "cloro",
    "diagnosticActionPlan.lastMeasureDesc": "Sarà usata come valore « prima » per confrontare le tue nuove misurazioni.",
    "diagnosticActionPlan.lastMeasureTac": "TAC",
    "diagnosticActionPlan.lastMeasureTitle": "Ultima misurazione salvata",
    "diagnosticActionPlan.markAsDone": "Segna come fatto",
    "diagnosticActionPlan.noteActionPlan": "Fase del piano d'azione: {title}",
    "diagnosticActionPlan.phHigh": "Il tuo pH {ph} è troppo alto. Aggiungi {qty} di pH- per tornare a 7.4 (calo di ~{delta} unità).",
    "diagnosticActionPlan.phHighWarning": "Versa davanti agli ugelli di mandata, filtrazione in funzione. Non versare mai pH- puro direttamente.",
    "diagnosticActionPlan.phIdeal": "✅ pH nel range ideale (7.0 - 7.4). Nessun aggiustamento necessario.",
    "diagnosticActionPlan.phLow": "Il tuo pH {ph} è troppo basso. Aggiungi {qty} di pH+ per risalire a 7.0 (aumento di ~{delta} unità).",
    "diagnosticActionPlan.phLowWarning": "Diluisci in un secchio di acqua della piscina prima di versare davanti agli ugelli di mandata.",
    "diagnosticActionPlan.poolDetected": "Piscina rilevata:",
    "diagnosticActionPlan.poolDetectedSuffix": "— dosaggi calcolati automaticamente.",
    "diagnosticActionPlan.poolState": "Stato della tua piscina",
    "diagnosticActionPlan.product": "Prodotto",
    "diagnosticActionPlan.productPhMinus": "pH- (polvere, bisolfito di sodio)",
    "diagnosticActionPlan.productPhPlus": "pH+ (carbonato di sodio)",
    "diagnosticActionPlan.progress": "Avanzamento",
    "diagnosticActionPlan.recheckAfter": "Dopo",
    "diagnosticActionPlan.recheckAgain": "Rifai una verifica",
    "diagnosticActionPlan.recheckAnalyze": "Analizza e verifica",
    "diagnosticActionPlan.recheckAnalyzeNewPhoto": "Analisi della tua nuova foto",
    "diagnosticActionPlan.recheckAnalyzing": "Analisi in corso...",
    "diagnosticActionPlan.recheckBefore": "Prima",
    "diagnosticActionPlan.recheckButton": "Verifica risultato (nuova foto)",
    "diagnosticActionPlan.recheckClickToUpload": "Clicca per caricare una foto",
    "diagnosticActionPlan.recheckImprovement": "Miglioramento di +{n}%! Continua così.",
    "diagnosticActionPlan.recheckLittleImprovement": "Poco miglioramento. Regola il tuo approccio con il nuovo piano sotto.",
    "diagnosticActionPlan.recheckNewPhotoAlt": "Nuova foto",
    "diagnosticActionPlan.recheckNewPlan": "Nuovo piano complementare",
    "diagnosticActionPlan.recheckNewPlanDesc": "In base all'analisi della tua nuova foto, ecco le fasi complementari consigliate:",
    "diagnosticActionPlan.recheckPersistentIssues": "Problemi ancora presenti:",
    "diagnosticActionPlan.recheckTakeNewPhoto": "Fai una nuova foto per verificare",
    "diagnosticActionPlan.recommendation": "Consiglio per la tua misurazione",
    "diagnosticActionPlan.recordMeasures": "Registra le tue misurazioni",
    "diagnosticActionPlan.reminderDesc": "Ti restano {count} fase(i) da completare. Segui il piano fino in fondo per risolvere definitivamente il problema.",
    "diagnosticActionPlan.reminderTitle": "Promemoria",
    "diagnosticActionPlan.resolvedDesc": "La tua piscina è ora sana. L'analisi di controllo conferma che il problema è risolto.",
    "diagnosticActionPlan.resolvedTitle": "✅ Risolto con AQWELIA",
    "diagnosticActionPlan.skipStep": "Salta questa fase",
    "diagnosticActionPlan.stepsCount": "{done}/{total} fasi",
    "diagnosticActionPlan.title": "Piano d'azione guidato",
    "diagnosticActionPlan.toastMeasureSaved": "Misurazione salvata ✓",
    "diagnosticActionPlan.toastMeasureSavedDesc": "{measures} → diario aggiornato.",
    "diagnosticActionPlan.toastMissingRequired": "Campi obbligatori mancanti",
    "diagnosticActionPlan.toastMissingRequiredDesc": "Compila tutti i campi obbligatori (*) prima di validare.",
    "diagnosticActionPlan.toastRecheckErrorDesc": "Analisi impossibile",
    "diagnosticActionPlan.toastRecheckErrorTitle": "Errore",
    "diagnosticActionPlan.toastRecheckNotResolvedDesc": "Continua il trattamento e verifica di nuovo più tardi.",
    "diagnosticActionPlan.toastRecheckNotResolvedTitle": "Non ancora risolto",
    "diagnosticActionPlan.toastRecheckResolvedDesc": "✅ La tua piscina è ora sana.",
    "diagnosticActionPlan.toastRecheckResolvedTitle": "Problema risolto!",
    "diagnosticActionPlan.toastSaveFailed": "Salvataggio impossibile",
    "diagnosticActionPlan.toastSaveFailedTitle": "Errore di salvataggio",
    "diagnosticActionPlan.toastStepValidated": "Fase validata",
    "diagnosticActionPlan.toastStepValidatedNoMeasure": "Fase validata (senza misurazione)",
    "diagnosticActionPlan.urgencyCritical": "Urgente",
    "diagnosticActionPlan.urgencyImportant": "Importante",
    "diagnosticActionPlan.urgencyLow": "OK",
    "diagnosticActionPlan.urgencyModerate": "Da monitorare",
    "diagnosticActionPlan.validateAndSave": "Valida e salva",
    "diagnosticActionPlan.validating": "Salvataggio…",
    "diagnosticActionPlan.waitTime": "Tempo di attesa",
    "diagnosticActionPlan.waterTestNote": "Le misurazioni sono salvate nel tuo diario (",
    "diagnosticActionPlan.waterTestNoteSuffix": ") via API.",

    # ===== guidesData.after-storm =====
    "guidesData.after-storm.steps.1.detail": "I temporali spesso acidificano l'acqua e diluiscono il cloro.",
    "guidesData.after-storm.steps.1.title": "Testare pH e cloro",
    "guidesData.after-storm.steps.2.detail": "Detriti portati da pioggia e vento.",
    "guidesData.after-storm.steps.2.title": "Pulire skimmer e cestello",
    "guidesData.after-storm.steps.3.detail": "Priorità al pH prima di qualsiasi aggiunta di cloro.",
    "guidesData.after-storm.steps.3.title": "Regolare il pH se necessario",
    "guidesData.after-storm.steps.4.detail": "Cloro lento o shock secondo lo scarto.",
    "guidesData.after-storm.steps.4.title": "Integrare il cloro se basso",
    "guidesData.after-storm.steps.5.detail": "Distribuisci bene le correzioni.",
    "guidesData.after-storm.steps.5.title": "Filtrare 4-6h",
    "guidesData.after-storm.summary": "Il temporale diluisce il cloro e modifica il pH. Routine post-temporale.",
    "guidesData.after-storm.title": "Cosa fare dopo un temporale?",

    # ===== guidesData.cat_* =====
    "guidesData.cat_equipment": "Attrezzature",
    "guidesData.cat_faq": "FAQ",
    "guidesData.cat_getting_started": "Iniziare",
    "guidesData.cat_problems": "Problemi dell'acqua",
    "guidesData.cat_products": "Prodotti & dosaggi",
    "guidesData.cat_safety": "Sicurezza e balneazione",
    "guidesData.cat_treatments": "Trattamenti (cloro/sale/bromo)",
    "guidesData.cat_weather_seasons": "Meteo e stagioni",

    # ===== guidesData.cell-clean =====
    "guidesData.cell-clean.steps.1.detail": "Spegni l'elettrolizzatore e la pompa.",
    "guidesData.cell-clean.steps.1.title": "Tagliare l'alimentazione",
    "guidesData.cell-clean.steps.1.warning": "Sicurezza elettrica. Non manipolare mai la cella sotto tensione.",
    "guidesData.cell-clean.steps.2.detail": "Svita secondo il modello. Verifica lo stato degli elettrodi.",
    "guidesData.cell-clean.steps.2.title": "Smontare la cella",
    "guidesData.cell-clean.steps.3.detail": "1/3 acido cloridrico + 2/3 acqua in un recipiente di plastica.",
    "guidesData.cell-clean.steps.3.title": "Preparare una soluzione acida diluita",
    "guidesData.cell-clean.steps.3.warning": "VERSARE SEMPRE l'acido nell'acqua, mai il contrario. Guanti e occhiali obbligatori. Aerazione.",
    "guidesData.cell-clean.steps.4.detail": "Il tartaro si scioglie. Non lasciare troppo a lungo.",
    "guidesData.cell-clean.steps.4.title": "Immersione 10-15 min",
    "guidesData.cell-clean.steps.5.detail": "Con acqua pulita fino a sparizione dell'odore.",
    "guidesData.cell-clean.steps.5.title": "Risciacquare abbondantemente",
    "guidesData.cell-clean.steps.6.detail": "Verifica la produzione sul display.",
    "guidesData.cell-clean.steps.6.title": "Rimontare e riavviare",
    "guidesData.cell-clean.summary": "Decalcificare la cella dell'elettrolizzatore al sale per mantenere la produzione di cloro.",
    "guidesData.cell-clean.title": "Pulire la cella dell'elettrolizzatore",

    # ===== guidesData.chlorine-shock =====
    "guidesData.chlorine-shock.steps.1.detail": "Uno shock è inefficace se pH > 7.6. Equilibra prima.",
    "guidesData.chlorine-shock.steps.1.title": "Verificare il pH PRIMA",
    "guidesData.chlorine-shock.steps.1.warning": "Non fare MAI uno shock senza aver verificato il pH.",
    "guidesData.chlorine-shock.steps.2.detail": "La sera, senza bagnanti, filtrazione in funzione.",
    "guidesData.chlorine-shock.steps.2.title": "Scegliere il momento giusto",
    "guidesData.chlorine-shock.steps.3.detail": "AQWELIA calcola la quantità in base al volume della tua vasca.",
    "guidesData.chlorine-shock.steps.3.title": "Dosare in base al volume",
    "guidesData.chlorine-shock.steps.4.detail": "Non versare mai lo shock in polvere direttamente a bordo vasca.",
    "guidesData.chlorine-shock.steps.4.title": "Sciogliere in un secchio",
    "guidesData.chlorine-shock.steps.5.detail": "Il cloro deve essere ben distribuito.",
    "guidesData.chlorine-shock.steps.5.title": "Filtrare almeno 4h",
    "guidesData.chlorine-shock.steps.6.detail": "Verifica il cloro libero prima di nuotare (deve essere < 3 mg/L).",
    "guidesData.chlorine-shock.steps.6.title": "Attendere 8h prima della balneazione",
    "guidesData.chlorine-shock.steps.6.warning": "Balneazione vietata per almeno 8h.",
    "guidesData.chlorine-shock.summary": "Il trattamento shock: indicazioni, dosaggio, sicurezza, tempi di balneazione.",
    "guidesData.chlorine-shock.title": "Quando e come fare un cloro shock",

    # ===== guidesData.cloudy-water =====
    "guidesData.cloudy-water.steps.1.detail": "L'80% delle acque torbide deriva da un problema di filtrazione. Verifica pressione, durata, pulizia del filtro.",
    "guidesData.cloudy-water.steps.1.title": "Verificare la filtrazione",
    "guidesData.cloudy-water.steps.2.detail": "pH fuori range o cloro basso = acqua torbida.",
    "guidesData.cloudy-water.steps.2.title": "Testare pH e cloro",
    "guidesData.cloudy-water.steps.3.detail": "Filtro intasato = acqua torbida.",
    "guidesData.cloudy-water.steps.3.title": "Pulire o backwash il filtro",
    "guidesData.cloudy-water.steps.4.detail": "Il flocculante aggrega le particelle fini affinché il filtro le trattenga.",
    "guidesData.cloudy-water.steps.4.title": "Usare un flocculante (se filtro a sabbia)",
    "guidesData.cloudy-water.steps.4.warning": "Flocculante solo con filtro a sabbia. Non con cartuccia.",
    "guidesData.cloudy-water.steps.5.detail": "Dopo la flocculazione, dei depositi si formano sul fondo: aspirali.",
    "guidesData.cloudy-water.steps.5.title": "Filtrare 24h poi aspirare i depositi",
    "guidesData.cloudy-water.summary": "Distinguere le cause di un'acqua torbida e applicare il trattamento giusto.",
    "guidesData.cloudy-water.title": "Acqua torbida o lattiginosa",

    # ===== guidesData.combined-chlorine =====
    "guidesData.combined-chlorine.steps.1.detail": "Il forte odore di cloro NON è un eccesso di cloro: sono le clorammine (cloro combinato), sottoprodotti della disinfezione.",
    "guidesData.combined-chlorine.steps.1.title": "Capire la causa",
    "guidesData.combined-chlorine.steps.2.detail": "Cloro combinato = cloro totale - cloro libero. Se > 0.4 mg/L, trattamento necessario.",
    "guidesData.combined-chlorine.steps.2.title": "Misurare il cloro libero E totale",
    "guidesData.combined-chlorine.steps.3.detail": "Lo shock rompe le clorammine e libera cloro libero attivo.",
    "guidesData.combined-chlorine.steps.3.title": "Fare un trattamento shock",
    "guidesData.combined-chlorine.steps.4.detail": "Un pH alto aggrava le clorammine.",
    "guidesData.combined-chlorine.steps.4.title": "Verificare il pH",
    "guidesData.combined-chlorine.summary": "Capire le clorammine e come sbarazzarsene.",
    "guidesData.combined-chlorine.title": "Forte odore di cloro e occhi che bruciano",

    # ===== guidesData.faq-cya-high =====
    "guidesData.faq-cya-high.steps.1.detail": "Un CYA troppo alto \"blocca\" il cloro: è presente ma inattivo. Rischio alghe nonostante un cloro normale.",
    "guidesData.faq-cya-high.steps.1.title": "Perché è un problema",
    "guidesData.faq-cya-high.steps.2.detail": "Unica soluzione: diluire l'acqua.",
    "guidesData.faq-cya-high.steps.2.title": "Non esiste un prodotto per abbassare il CYA",
    "guidesData.faq-cya-high.steps.3.detail": "Svuotamento parziale poi reintegro.",
    "guidesData.faq-cya-high.steps.3.title": "Rinnovare 20-30% dell'acqua",
    "guidesData.faq-cya-high.steps.4.detail": "Verifica il nuovo valore.",
    "guidesData.faq-cya-high.steps.4.title": "Nuovo test dopo il rinnovo",
    "guidesData.faq-cya-high.steps.5.detail": "Preferisci cloro non stabilizzato o elettrolizzatore.",
    "guidesData.faq-cya-high.steps.5.title": "In futuro: usare meno cloro stabilizzato",
    "guidesData.faq-cya-high.summary": "Cosa fare quando il CYA supera 50-60 mg/L?",
    "guidesData.faq-cya-high.title": "Il mio stabilizzante (CYA) è troppo alto",

    # ===== guidesData.faq-test-frequency =====
    "guidesData.faq-test-frequency.steps.1.detail": "Almeno 2 volte a settimana, più con caldo forte.",
    "guidesData.faq-test-frequency.steps.1.title": "In stagione calda",
    "guidesData.faq-test-frequency.steps.2.detail": "Una volta ogni 2 settimane.",
    "guidesData.faq-test-frequency.steps.2.title": "In stagione fredda (svernamento attivo)",
    "guidesData.faq-test-frequency.steps.3.detail": "Nuovo test entro 3-24h secondo il prodotto.",
    "guidesData.faq-test-frequency.steps.3.title": "Dopo qualsiasi trattamento",
    "guidesData.faq-test-frequency.steps.4.detail": "Test sistematico.",
    "guidesData.faq-test-frequency.steps.4.title": "Dopo un temporale",
    "guidesData.faq-test-frequency.steps.5.detail": "Sempre.",
    "guidesData.faq-test-frequency.steps.5.title": "Prima di nuotare se in dubbio",
    "guidesData.faq-test-frequency.summary": "Frequenza consigliata secondo stagione e utilizzo.",
    "guidesData.faq-test-frequency.title": "Con quale frequenza testare la propria acqua?",

    # ===== guidesData.filter-backwash =====
    "guidesData.filter-backwash.steps.1.detail": "Quando la pressione sale di 0.3-0.5 bar sopra la pressione di esercizio, o ogni 2-4 settimane.",
    "guidesData.filter-backwash.steps.1.title": "Quando fare il backwash?",
    "guidesData.filter-backwash.steps.2.detail": "SPEGNI SEMPRE la pompa prima di manovrare la valvola.",
    "guidesData.filter-backwash.steps.2.title": "Spegnere la pompa",
    "guidesData.filter-backwash.steps.2.warning": "Rischio elettrico e materiale.",
    "guidesData.filter-backwash.steps.3.detail": "Gira con decisione la valvola multivie.",
    "guidesData.filter-backwash.steps.3.title": "Mettere la valvola su BACKWASH",
    "guidesData.filter-backwash.steps.4.detail": "L'acqua scorre nello scarico finché non torna limpida.",
    "guidesData.filter-backwash.steps.4.title": "Riaccendere la pompa 2-3 min",
    "guidesData.filter-backwash.steps.5.detail": "Il risciacquo compatta la sabbia ed evita il ritorno dello sporco.",
    "guidesData.filter-backwash.steps.5.title": "Spegnere, valvola su RINSE 30s",
    "guidesData.filter-backwash.steps.6.detail": "Rimetti la valvola in filtrazione normale.",
    "guidesData.filter-backwash.steps.6.title": "Tornare in posizione FILTER",
    "guidesData.filter-backwash.summary": "Quando e come fare un backwash efficace.",
    "guidesData.filter-backwash.title": "Backwash (contro-lavaggio) del filtro a sabbia",

    # ===== guidesData.filter-cartridge-clean =====
    "guidesData.filter-cartridge-clean.steps.1.detail": "Tagliare l'alimentazione elettrica.",
    "guidesData.filter-cartridge-clean.steps.1.title": "Spegnere la pompa",
    "guidesData.filter-cartridge-clean.steps.1.warning": "Sicurezza elettrica obbligatoria.",
    "guidesData.filter-cartridge-clean.steps.2.detail": "Apri il corpo del filtro secondo il modello.",
    "guidesData.filter-cartridge-clean.steps.2.title": "Smontare la cartuccia",
    "guidesData.filter-cartridge-clean.steps.3.detail": "Getto d'acqua delicato, dall'alto verso il basso, tra le pieghe.",
    "guidesData.filter-cartridge-clean.steps.3.title": "Risciacquare con getto",
    "guidesData.filter-cartridge-clean.steps.4.detail": "Ogni 2-3 pulizie, sgrassaggio e decalcificazione.",
    "guidesData.filter-cartridge-clean.steps.4.title": "Immergere in un detergente per filtri (opzionale)",
    "guidesData.filter-cartridge-clean.steps.5.detail": "Riposiziona bene le guarnizioni.",
    "guidesData.filter-cartridge-clean.steps.5.title": "Rimontare e riavviare",
    "guidesData.filter-cartridge-clean.summary": "Smontaggio e risciacquo di una cartuccia di filtrazione.",
    "guidesData.filter-cartridge-clean.title": "Pulire un filtro a cartuccia",

    # ===== guidesData.getting-started-spa =====
    "guidesData.getting-started-spa.steps.1.detail": "L'acqua si guasta in fretta. Test più frequenti.",
    "guidesData.getting-started-spa.steps.1.title": "Volume ridotto = reazioni veloci",
    "guidesData.getting-started-spa.steps.2.detail": "Il bromo è più stabile a caldo e meno odoroso.",
    "guidesData.getting-started-spa.steps.2.title": "Preferire il bromo al cloro",
    "guidesData.getting-started-spa.steps.3.detail": "Il pH cambia con la temperatura. Testa a temperatura di bagno.",
    "guidesData.getting-started-spa.steps.3.title": "Temperatura e pH",
    "guidesData.getting-started-spa.steps.4.detail": "Più necessario che in piscina.",
    "guidesData.getting-started-spa.steps.4.title": "Shock settimanale",
    "guidesData.getting-started-spa.steps.5.detail": "Ogni 3-4 mesi secondo l'utilizzo.",
    "guidesData.getting-started-spa.steps.5.title": "Svuotamento periodico",
    "guidesData.getting-started-spa.summary": "La spa ha le sue regole: acqua calda, volume ridotto, bromo piuttosto che cloro.",
    "guidesData.getting-started-spa.title": "Specificità della spa",

    # ===== guidesData.getting-started =====
    "guidesData.getting-started.steps.1.detail": "Indispensabile per ogni dosaggio. AQWELIA lo calcola a partire dalle dimensioni.",
    "guidesData.getting-started.steps.1.title": "Conoscere il volume della propria piscina",
    "guidesData.getting-started.steps.10.detail": "AQWELIA conserva lo storico per te.",
    "guidesData.getting-started.steps.10.title": "Tenere un diario",
    "guidesData.getting-started.steps.2.detail": "Il parametro n°1. Tutto parte da qui.",
    "guidesData.getting-started.steps.2.title": "Capire il pH",
    "guidesData.getting-started.steps.3.detail": "Libero, totale, combinato. AQWELIA ti guida.",
    "guidesData.getting-started.steps.3.title": "Capire il cloro",
    "guidesData.getting-started.steps.4.detail": "Metà della temperatura dell'acqua in ore.",
    "guidesData.getting-started.steps.4.title": "Filtrare a sufficienza",
    "guidesData.getting-started.steps.5.detail": "Più spesso con caldo forte.",
    "guidesData.getting-started.steps.5.title": "Testare 1-2x a settimana",
    "guidesData.getting-started.steps.6.detail": "Backwash o risciacquo regolare.",
    "guidesData.getting-started.steps.6.title": "Manutenere il filtro",
    "guidesData.getting-started.steps.7.detail": "Troppo basso = pompa a rischio; troppo alto = skimmer inefficiente.",
    "guidesData.getting-started.steps.7.title": "Monitorare il livello dell'acqua",
    "guidesData.getting-started.steps.8.detail": "Evita alghe e depositi.",
    "guidesData.getting-started.steps.8.title": "Spazzolare e pulire la linea dell'acqua",
    "guidesData.getting-started.steps.9.detail": "Temporale, ondata di calore, vacanze: prevenire piuttosto che curare.",
    "guidesData.getting-started.steps.9.title": "Anticipare il meteo",
    "guidesData.getting-started.summary": "Le prime 10 cose da sapere quando si diventa proprietari di una piscina.",
    "guidesData.getting-started.title": "Iniziare con la propria piscina",

    # ===== guidesData.green-water =====
    "guidesData.green-water.steps.1.detail": "Un'acqua verde è quasi sempre dovuta a mancanza di disinfettante o pH squilibrato.",
    "guidesData.green-water.steps.1.title": "Misurare pH e cloro libero",
    "guidesData.green-water.steps.1.warning": "Non aggiungere mai anti-alghe prima di aver equilibrato il pH.",
    "guidesData.green-water.steps.2.detail": "Se il pH > 7.4, aggiungi pH- diluito. Attendi 2-3h di filtrazione.",
    "guidesData.green-water.steps.2.tip": "Il cloro è 10x più efficace a pH 7.2 che a pH 8.0.",
    "guidesData.green-water.steps.2.title": "Equilibrare il pH (7.0-7.4)",
    "guidesData.green-water.steps.3.detail": "Staccare le alghe aiuta il trattamento a penetrare.",
    "guidesData.green-water.steps.3.title": "Spazzolare le pareti e il fondo",
    "guidesData.green-water.steps.4.detail": "Cloro shock (dopo pH equilibrato). Filtrazione continua 24h.",
    "guidesData.green-water.steps.4.title": "Fare un trattamento shock",
    "guidesData.green-water.steps.4.warning": "Balneazione vietata almeno 8h dopo lo shock.",
    "guidesData.green-water.steps.5.detail": "Dopo lo shock, l'anti-alghe previene la ricrescita.",
    "guidesData.green-water.steps.5.title": "Aggiungere un anti-alghe curativo",
    "guidesData.green-water.steps.6.detail": "La filtrazione è importante quanto i prodotti chimici.",
    "guidesData.green-water.steps.6.title": "Filtrare in continuo 24-48h",
    "guidesData.green-water.steps.7.detail": "Verifica pH e cloro. Se l'acqua resta verde, il filtro potrebbe essere da pulire.",
    "guidesData.green-water.steps.7.title": "Nuovo test dopo 24h",
    "guidesData.green-water.summary": "Identificare la causa di un'acqua verde e trattarla passo dopo passo senza sovradosare.",
    "guidesData.green-water.title": "Acqua verde: diagnosi e piano d'azione",

    # ===== guidesData.guide_* =====
    "guidesData.guide_eq1_summary": "Quando e come fare un backwash efficace.",
    "guidesData.guide_eq1_title": "Backwash (contro-lavaggio) del filtro a sabbia",
    "guidesData.guide_eq2_summary": "Smontaggio e risciacquo di una cartuccia di filtrazione.",
    "guidesData.guide_eq2_title": "Pulire un filtro a cartuccia",
    "guidesData.guide_gs1_summary": "Le prime 10 cose da sapere quando si diventa proprietari di una piscina.",
    "guidesData.guide_gs1_title": "Iniziare con la propria piscina",
    "guidesData.guide_pb1_summary": "Identificare la causa di un'acqua verde e trattarla passo dopo passo senza sovradosare.",
    "guidesData.guide_pb1_title": "Acqua verde: diagnosi e piano d'azione",
    "guidesData.guide_pb2_summary": "Distinguere le cause di un'acqua torbida e applicare il trattamento giusto.",
    "guidesData.guide_pb2_title": "Acqua torbida o lattiginosa",
    "guidesData.guide_pb3_summary": "Capire le clorammine e come sbarazzarsene.",
    "guidesData.guide_pb3_title": "Forte odore di cloro e occhi che bruciano",
    "guidesData.guide_pr1_summary": "Il trattamento shock: indicazioni, dosaggio, sicurezza, tempi di balneazione.",
    "guidesData.guide_pr1_title": "Quando e come fare un cloro shock",
    "guidesData.guide_tr1_summary": "Principio, tenore di sale, produzione, manutenzione corrente.",
    "guidesData.guide_tr1_title": "Capire il proprio elettrolizzatore al sale",

    # ===== guidesData.level_* =====
    "guidesData.level_beginner": "Principiante",
    "guidesData.level_expert": "Esperto",
    "guidesData.level_intermediate": "Intermedio",

    # ===== guidesData.ph-control =====
    "guidesData.ph-control.steps.1.detail": "Tutto parte dal pH: efficacia del cloro, comfort di balneazione, protezione delle attrezzature.",
    "guidesData.ph-control.steps.1.title": "Il pH è prioritario",
    "guidesData.ph-control.steps.2.detail": "Più vicino a 7.2 = cloro ottimale.",
    "guidesData.ph-control.steps.2.title": "Range ideale 7.0-7.4",
    "guidesData.ph-control.steps.3.detail": "Un TAC basso rende il pH instabile.",
    "guidesData.ph-control.steps.3.title": "Regolare il TAC prima del pH se instabile",
    "guidesData.ph-control.steps.4.detail": "Non modificare mai il pH di più di 0.3 in una volta.",
    "guidesData.ph-control.steps.4.title": "Dosare in piccole quantità",
    "guidesData.ph-control.steps.5.detail": "Il miscuglio deve essere omogeneo.",
    "guidesData.ph-control.steps.5.title": "Filtrare 2-3h poi nuovo test",
    "guidesData.ph-control.summary": "Perché il pH è il parametro n°1, come regolarlo.",
    "guidesData.ph-control.title": "Padroneggiare il proprio pH",

    # ===== guidesData.product-safety =====
    "guidesData.product-safety.steps.1.detail": "Cloro + acido = gas tossico mortale. Diluire sempre separatamente.",
    "guidesData.product-safety.steps.1.title": "NON MISCHIARE MAI i prodotti",
    "guidesData.product-safety.steps.1.warning": "Regola assoluta di sopravvivenza.",
    "guidesData.product-safety.steps.2.detail": "Mai acqua nel prodotto acido (schizzi).",
    "guidesData.product-safety.steps.2.title": "Aggiungere sempre il prodotto nell'acqua",
    "guidesData.product-safety.steps.3.detail": "Soprattutto per acidi e cloro concentrato.",
    "guidesData.product-safety.steps.3.title": "Indossare guanti e occhiali",
    "guidesData.product-safety.steps.4.detail": "Separare acidi e clori. Fuori dalla portata dei bambini.",
    "guidesData.product-safety.steps.4.title": "Conservare al secco, al fresco, ventilato",
    "guidesData.product-safety.steps.5.detail": "Ogni prodotto ha le sue regole di dosaggio e applicazione.",
    "guidesData.product-safety.steps.5.title": "Seguire le istruzioni",
    "guidesData.product-safety.steps.6.detail": "Non provocare vomito, consulta immediatamente.",
    "guidesData.product-safety.steps.6.title": "In caso di incidente: chiamare il 112 o il centro antiveleni",
    "guidesData.product-safety.summary": "Le regole d'oro per manipolare e conservare i prodotti per piscina.",
    "guidesData.product-safety.title": "Sicurezza dei prodotti chimici",

    # ===== guidesData.reminder_* =====
    "guidesData.reminder_after_storm_action": "Testa il cloro e il pH.",
    "guidesData.reminder_after_storm_detail": "Il temporale può aver squilibrato la tua acqua.",
    "guidesData.reminder_after_storm_title": "Dopo il temporale",
    "guidesData.reminder_algae_prevent_action": "Azione per algae_prevent",
    "guidesData.reminder_algae_prevent_detail": "Dettaglio per algae_prevent",
    "guidesData.reminder_algae_prevent_title": "Algae Prevent",
    "guidesData.reminder_cell_clean_action": "Azione per cell_clean",
    "guidesData.reminder_cell_clean_detail": "Dettaglio per cell_clean",
    "guidesData.reminder_cell_clean_title": "Cell Clean",
    "guidesData.reminder_chlorine_check_action": "Azione per chlorine_check",
    "guidesData.reminder_chlorine_check_detail": "Dettaglio per chlorine_check",
    "guidesData.reminder_chlorine_check_title": "Chlorine Check",
    "guidesData.reminder_filter_clean": "Pulizia del filtro",
    "guidesData.reminder_filter_clean_action": "Fai un backwash (contro-lavaggio).",
    "guidesData.reminder_filter_clean_desc": "Backwash del filtro a sabbia consigliato.",
    "guidesData.reminder_filter_clean_detail": "Backwash del filtro a sabbia consigliato.",
    "guidesData.reminder_filter_clean_title": "Pulizia del filtro",
    "guidesData.reminder_open_pool_action": "Azione per open_pool",
    "guidesData.reminder_open_pool_detail": "Dettaglio per open_pool",
    "guidesData.reminder_open_pool_title": "Open Pool",
    "guidesData.reminder_ph_check_action": "Azione per ph_check",
    "guidesData.reminder_ph_check_detail": "Dettaglio per ph_check",
    "guidesData.reminder_ph_check_title": "Ph Check",
}

# Validate against worksheet
src = json.load(open('/home/z/my-project/.tmp/worksheets/it-part1.json'))
src_keys = set(src.keys())
out_keys = set(translations.keys())

missing = src_keys - out_keys
extra = out_keys - src_keys
assert not missing, f"MISSING {len(missing)} keys: {list(missing)[:5]}"
assert not extra, f"EXTRA {len(extra)} keys: {list(extra)[:5]}"
assert len(translations) == len(src), f"Count mismatch: {len(translations)} vs {len(src)}"

# Write JSON with UTF-8 + ensure_ascii=False
with open('/home/z/my-project/.tmp/translated/it-part1.json', 'w', encoding='utf-8') as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)

print(f"OK: wrote {len(translations)} keys to it-part1.json")
