export const toolWorkspaceMessages = {
  fr: {
    unauthorized: 'Non autorisé', readonly: 'Accès en lecture seule', technicianUnauthorized: 'Technicien non autorisé', memberUnauthorized: 'Collaborateur non autorisé',
    organizationRequired: 'Configurez votre organisation avant de continuer.', companyNameRequired: 'Nom de société requis', companySetupRequired: 'Configurez d’abord votre société', userMustRegister: 'Ce collaborateur doit d’abord créer son compte AQWELIA',
    lastIntervention: 'Dernière intervention', notProvided: 'Non renseigné', notProvidedF: 'Non renseignée', recentInterventions: 'Interventions récentes', notAssociated: 'Non associé', scheduledDate: 'Date planifiée', unfinished: 'Non terminée', unassigned: 'Non assigné', actionsDone: 'Actions réalisées', productsUsed: 'Produits utilisés', timestampedPhotos: 'Photos horodatées',
    upcomingAppointments: 'Rendez-vous à venir', acceptedQuoteRevenue: 'CA des devis acceptés', appointmentUpdated: 'Rendez-vous mis à jour.', updateFailed: 'Mise à jour impossible.', appointmentsSubtitle: 'Créneaux proposés, confirmations et suivi des visites.', appointmentsEmpty: 'Aucun rendez-vous. Créez-en depuis une fiche lead.', areaUnknown: 'Zone non précisée',
    slotProposedNote: 'Créneau proposé depuis Growth Inbox', slotCreated: 'Créneau proposé et journalisé.', appointmentCreateFailed: 'Impossible de créer le rendez-vous.', draftCreated: 'Brouillon de devis créé et journalisé.', quoteCreateFailed: 'Impossible de créer le devis.', leadCreateFailed: 'Impossible de créer la demande.', quoteUpdated: 'Devis mis à jour.', organizationSaved: 'Organisation enregistrée.', reportSaved: 'Rapport enregistré.', waterTestSaved: 'Analyse d’eau enregistrée.', temperature: 'Température (°C)', cityUnknown: 'Ville non renseignée', changesSaved: 'Modifications enregistrées.',
    qualificationDone: 'Qualification calculée et journalisée.', qualificationFailed: 'La qualification a échoué.', assignmentDone: 'Attribution humaine confirmée et journalisée.', assignmentFailed: 'L’attribution a échoué.', qualificationDescription: 'Priorisation déterministe des demandes entrantes consenties.', assignmentDescription: 'Affectation à un collaborateur après validation humaine.', serviceUnknown: 'Service non précisé', confirmed: 'confirmé', suggestionReady: 'Suggestion prête — validation humaine requise avant attribution.',
  },
  en: {
    unauthorized: 'Unauthorized', readonly: 'Read-only access', technicianUnauthorized: 'Technician not authorized', memberUnauthorized: 'Team member not authorized', organizationRequired: 'Set up your organization before continuing.', companyNameRequired: 'Company name required', companySetupRequired: 'Set up your company first', userMustRegister: 'This team member must create an AQWELIA account first',
    lastIntervention: 'Last intervention', notProvided: 'Not provided', notProvidedF: 'Not provided', recentInterventions: 'Recent interventions', notAssociated: 'Not linked', scheduledDate: 'Scheduled date', unfinished: 'Not completed', unassigned: 'Unassigned', actionsDone: 'Actions completed', productsUsed: 'Products used', timestampedPhotos: 'Timestamped photos',
    upcomingAppointments: 'Upcoming appointments', acceptedQuoteRevenue: 'Accepted quote revenue', appointmentUpdated: 'Appointment updated.', updateFailed: 'Update failed.', appointmentsSubtitle: 'Proposed slots, confirmations and visit tracking.', appointmentsEmpty: 'No appointments. Create one from a lead record.', areaUnknown: 'Area not provided',
    slotProposedNote: 'Slot proposed from Growth Inbox', slotCreated: 'Slot proposed and logged.', appointmentCreateFailed: 'Could not create the appointment.', draftCreated: 'Quote draft created and logged.', quoteCreateFailed: 'Could not create the quote.', leadCreateFailed: 'Could not create the request.', quoteUpdated: 'Quote updated.', organizationSaved: 'Organization saved.', reportSaved: 'Report saved.', waterTestSaved: 'Water test saved.', temperature: 'Temperature (°C)', cityUnknown: 'City not provided', changesSaved: 'Changes saved.',
    qualificationDone: 'Qualification calculated and logged.', qualificationFailed: 'Qualification failed.', assignmentDone: 'Human assignment confirmed and logged.', assignmentFailed: 'Assignment failed.', qualificationDescription: 'Deterministic prioritization of consented inbound requests.', assignmentDescription: 'Assignment to a team member after human approval.', serviceUnknown: 'Service not provided', confirmed: 'confirmed', suggestionReady: 'Suggestion ready — human approval required before assignment.',
  },
  es: {
    unauthorized: 'No autorizado', readonly: 'Acceso de solo lectura', technicianUnauthorized: 'Técnico no autorizado', memberUnauthorized: 'Colaborador no autorizado', organizationRequired: 'Configura tu organización antes de continuar.', companyNameRequired: 'Nombre de empresa obligatorio', companySetupRequired: 'Configura primero tu empresa', userMustRegister: 'Este colaborador debe crear primero una cuenta AQWELIA',
    lastIntervention: 'Última intervención', notProvided: 'No indicado', notProvidedF: 'No indicada', recentInterventions: 'Intervenciones recientes', notAssociated: 'Sin asociar', scheduledDate: 'Fecha prevista', unfinished: 'No finalizada', unassigned: 'Sin asignar', actionsDone: 'Acciones realizadas', productsUsed: 'Productos utilizados', timestampedPhotos: 'Fotos con fecha y hora', upcomingAppointments: 'Próximas citas', acceptedQuoteRevenue: 'Ingresos de presupuestos aceptados', appointmentUpdated: 'Cita actualizada.', updateFailed: 'No se pudo actualizar.', appointmentsSubtitle: 'Horarios propuestos, confirmaciones y seguimiento.', appointmentsEmpty: 'No hay citas. Crea una desde una ficha de lead.', areaUnknown: 'Zona no indicada', slotProposedNote: 'Horario propuesto desde Growth Inbox', slotCreated: 'Horario propuesto y registrado.', appointmentCreateFailed: 'No se pudo crear la cita.', draftCreated: 'Borrador creado y registrado.', quoteCreateFailed: 'No se pudo crear el presupuesto.', leadCreateFailed: 'No se pudo crear la solicitud.', quoteUpdated: 'Presupuesto actualizado.', organizationSaved: 'Organización guardada.', reportSaved: 'Informe guardado.', waterTestSaved: 'Análisis de agua guardado.', temperature: 'Temperatura (°C)', cityUnknown: 'Ciudad no indicada', changesSaved: 'Cambios guardados.', qualificationDone: 'Calificación calculada y registrada.', qualificationFailed: 'La calificación falló.', assignmentDone: 'Asignación humana confirmada y registrada.', assignmentFailed: 'La asignación falló.', qualificationDescription: 'Priorización determinista de solicitudes entrantes consentidas.', assignmentDescription: 'Asignación a un colaborador tras validación humana.', serviceUnknown: 'Servicio no indicado', confirmed: 'confirmado', suggestionReady: 'Sugerencia lista — se requiere validación humana antes de asignar.',
  },
  de: {
    unauthorized: 'Nicht autorisiert', readonly: 'Nur Lesezugriff', technicianUnauthorized: 'Techniker nicht autorisiert', memberUnauthorized: 'Teammitglied nicht autorisiert', organizationRequired: 'Richten Sie Ihre Organisation ein, bevor Sie fortfahren.', companyNameRequired: 'Firmenname erforderlich', companySetupRequired: 'Richten Sie zuerst Ihr Unternehmen ein', userMustRegister: 'Dieses Teammitglied muss zuerst ein AQWELIA-Konto erstellen', lastIntervention: 'Letzter Einsatz', notProvided: 'Nicht angegeben', notProvidedF: 'Nicht angegeben', recentInterventions: 'Letzte Einsätze', notAssociated: 'Nicht zugeordnet', scheduledDate: 'Geplanter Termin', unfinished: 'Nicht abgeschlossen', unassigned: 'Nicht zugewiesen', actionsDone: 'Durchgeführte Arbeiten', productsUsed: 'Verwendete Produkte', timestampedPhotos: 'Fotos mit Zeitstempel', upcomingAppointments: 'Bevorstehende Termine', acceptedQuoteRevenue: 'Umsatz angenommener Angebote', appointmentUpdated: 'Termin aktualisiert.', updateFailed: 'Aktualisierung fehlgeschlagen.', appointmentsSubtitle: 'Vorgeschlagene Zeiten, Bestätigungen und Besuchsverfolgung.', appointmentsEmpty: 'Keine Termine. Erstellen Sie einen aus einem Lead.', areaUnknown: 'Gebiet nicht angegeben', slotProposedNote: 'Termin aus Growth Inbox vorgeschlagen', slotCreated: 'Termin vorgeschlagen und protokolliert.', appointmentCreateFailed: 'Termin konnte nicht erstellt werden.', draftCreated: 'Angebotsentwurf erstellt und protokolliert.', quoteCreateFailed: 'Angebot konnte nicht erstellt werden.', leadCreateFailed: 'Anfrage konnte nicht erstellt werden.', quoteUpdated: 'Angebot aktualisiert.', organizationSaved: 'Organisation gespeichert.', reportSaved: 'Bericht gespeichert.', waterTestSaved: 'Wasseranalyse gespeichert.', temperature: 'Temperatur (°C)', cityUnknown: 'Stadt nicht angegeben', changesSaved: 'Änderungen gespeichert.', qualificationDone: 'Qualifizierung berechnet und protokolliert.', qualificationFailed: 'Qualifizierung fehlgeschlagen.', assignmentDone: 'Menschliche Zuweisung bestätigt und protokolliert.', assignmentFailed: 'Zuweisung fehlgeschlagen.', qualificationDescription: 'Deterministische Priorisierung eingehender Anfragen mit Einwilligung.', assignmentDescription: 'Zuweisung an ein Teammitglied nach menschlicher Freigabe.', serviceUnknown: 'Service nicht angegeben', confirmed: 'bestätigt', suggestionReady: 'Vorschlag bereit — vor der Zuweisung ist eine menschliche Freigabe erforderlich.',
  },
  it: {
    unauthorized: 'Non autorizzato', readonly: 'Accesso in sola lettura', technicianUnauthorized: 'Tecnico non autorizzato', memberUnauthorized: 'Collaboratore non autorizzato', organizationRequired: 'Configura la tua organizzazione prima di continuare.', companyNameRequired: 'Nome azienda obbligatorio', companySetupRequired: 'Configura prima la tua azienda', userMustRegister: 'Questo collaboratore deve prima creare un account AQWELIA', lastIntervention: 'Ultimo intervento', notProvided: 'Non indicato', notProvidedF: 'Non indicata', recentInterventions: 'Interventi recenti', notAssociated: 'Non associato', scheduledDate: 'Data pianificata', unfinished: 'Non completato', unassigned: 'Non assegnato', actionsDone: 'Azioni eseguite', productsUsed: 'Prodotti utilizzati', timestampedPhotos: 'Foto con data e ora', upcomingAppointments: 'Prossimi appuntamenti', acceptedQuoteRevenue: 'Ricavi da preventivi accettati', appointmentUpdated: 'Appuntamento aggiornato.', updateFailed: 'Aggiornamento non riuscito.', appointmentsSubtitle: 'Fasce proposte, conferme e monitoraggio visite.', appointmentsEmpty: 'Nessun appuntamento. Creane uno da un lead.', areaUnknown: 'Zona non indicata', slotProposedNote: 'Fascia proposta da Growth Inbox', slotCreated: 'Fascia proposta e registrata.', appointmentCreateFailed: 'Impossibile creare l’appuntamento.', draftCreated: 'Bozza di preventivo creata e registrata.', quoteCreateFailed: 'Impossibile creare il preventivo.', leadCreateFailed: 'Impossibile creare la richiesta.', quoteUpdated: 'Preventivo aggiornato.', organizationSaved: 'Organizzazione salvata.', reportSaved: 'Rapporto salvato.', waterTestSaved: 'Analisi dell’acqua salvata.', temperature: 'Temperatura (°C)', cityUnknown: 'Città non indicata', changesSaved: 'Modifiche salvate.', qualificationDone: 'Qualificazione calcolata e registrata.', qualificationFailed: 'Qualificazione non riuscita.', assignmentDone: 'Assegnazione umana confermata e registrata.', assignmentFailed: 'Assegnazione non riuscita.', qualificationDescription: 'Prioritizzazione deterministica delle richieste in entrata con consenso.', assignmentDescription: 'Assegnazione a un collaboratore dopo la convalida umana.', serviceUnknown: 'Servizio non indicato', confirmed: 'confermato', suggestionReady: 'Suggerimento pronto — è richiesta la convalida umana prima dell’assegnazione.',
  },
  pt: {
    unauthorized: 'Não autorizado', readonly: 'Acesso apenas de leitura', technicianUnauthorized: 'Técnico não autorizado', memberUnauthorized: 'Colaborador não autorizado', organizationRequired: 'Configure a sua organização antes de continuar.', companyNameRequired: 'Nome da empresa obrigatório', companySetupRequired: 'Configure primeiro a sua empresa', userMustRegister: 'Este colaborador deve primeiro criar uma conta AQWELIA', lastIntervention: 'Última intervenção', notProvided: 'Não indicado', notProvidedF: 'Não indicada', recentInterventions: 'Intervenções recentes', notAssociated: 'Não associado', scheduledDate: 'Data prevista', unfinished: 'Não concluída', unassigned: 'Não atribuído', actionsDone: 'Ações realizadas', productsUsed: 'Produtos utilizados', timestampedPhotos: 'Fotografias com data e hora', upcomingAppointments: 'Próximos compromissos', acceptedQuoteRevenue: 'Receita de orçamentos aceites', appointmentUpdated: 'Compromisso atualizado.', updateFailed: 'Não foi possível atualizar.', appointmentsSubtitle: 'Horários propostos, confirmações e acompanhamento.', appointmentsEmpty: 'Sem compromissos. Crie um a partir de um lead.', areaUnknown: 'Zona não indicada', slotProposedNote: 'Horário proposto pela Growth Inbox', slotCreated: 'Horário proposto e registado.', appointmentCreateFailed: 'Não foi possível criar o compromisso.', draftCreated: 'Rascunho de orçamento criado e registado.', quoteCreateFailed: 'Não foi possível criar o orçamento.', leadCreateFailed: 'Não foi possível criar o pedido.', quoteUpdated: 'Orçamento atualizado.', organizationSaved: 'Organização guardada.', reportSaved: 'Relatório guardado.', waterTestSaved: 'Análise da água guardada.', temperature: 'Temperatura (°C)', cityUnknown: 'Cidade não indicada', changesSaved: 'Alterações guardadas.', qualificationDone: 'Qualificação calculada e registada.', qualificationFailed: 'A qualificação falhou.', assignmentDone: 'Atribuição humana confirmada e registada.', assignmentFailed: 'A atribuição falhou.', qualificationDescription: 'Priorização determinística de pedidos recebidos com consentimento.', assignmentDescription: 'Atribuição a um colaborador após validação humana.', serviceUnknown: 'Serviço não indicado', confirmed: 'confirmado', suggestionReady: 'Sugestão pronta — é necessária validação humana antes da atribuição.',
  },
  nl: {
    unauthorized: 'Niet geautoriseerd', readonly: 'Alleen-lezen toegang', technicianUnauthorized: 'Monteur niet geautoriseerd', memberUnauthorized: 'Teamlid niet geautoriseerd', organizationRequired: 'Stel uw organisatie in voordat u doorgaat.', companyNameRequired: 'Bedrijfsnaam verplicht', companySetupRequired: 'Stel eerst uw bedrijf in', userMustRegister: 'Dit teamlid moet eerst een AQWELIA-account aanmaken', lastIntervention: 'Laatste interventie', notProvided: 'Niet opgegeven', notProvidedF: 'Niet opgegeven', recentInterventions: 'Recente interventies', notAssociated: 'Niet gekoppeld', scheduledDate: 'Geplande datum', unfinished: 'Niet voltooid', unassigned: 'Niet toegewezen', actionsDone: 'Uitgevoerde acties', productsUsed: 'Gebruikte producten', timestampedPhotos: 'Foto’s met tijdstempel', upcomingAppointments: 'Komende afspraken', acceptedQuoteRevenue: 'Omzet uit geaccepteerde offertes', appointmentUpdated: 'Afspraak bijgewerkt.', updateFailed: 'Bijwerken mislukt.', appointmentsSubtitle: 'Voorgestelde tijdsloten, bevestigingen en bezoekopvolging.', appointmentsEmpty: 'Geen afspraken. Maak er een aan vanuit een lead.', areaUnknown: 'Gebied niet opgegeven', slotProposedNote: 'Tijdslot voorgesteld vanuit Growth Inbox', slotCreated: 'Tijdslot voorgesteld en gelogd.', appointmentCreateFailed: 'Afspraak kon niet worden aangemaakt.', draftCreated: 'Offerteconcept aangemaakt en gelogd.', quoteCreateFailed: 'Offerte kon niet worden aangemaakt.', leadCreateFailed: 'Aanvraag kon niet worden aangemaakt.', quoteUpdated: 'Offerte bijgewerkt.', organizationSaved: 'Organisatie opgeslagen.', reportSaved: 'Rapport opgeslagen.', waterTestSaved: 'Wateranalyse opgeslagen.', temperature: 'Temperatuur (°C)', cityUnknown: 'Stad niet opgegeven', changesSaved: 'Wijzigingen opgeslagen.', qualificationDone: 'Kwalificatie berekend en gelogd.', qualificationFailed: 'Kwalificatie mislukt.', assignmentDone: 'Menselijke toewijzing bevestigd en gelogd.', assignmentFailed: 'Toewijzing mislukt.', qualificationDescription: 'Deterministische prioritering van inkomende aanvragen met toestemming.', assignmentDescription: 'Toewijzing aan een teamlid na menselijke goedkeuring.', serviceUnknown: 'Service niet opgegeven', confirmed: 'bevestigd', suggestionReady: 'Suggestie gereed — menselijke goedkeuring vereist vóór toewijzing.',
  },
} as const

export type ToolWorkspaceKey = keyof typeof toolWorkspaceMessages.fr

export function toolWorkspaceText(locale: string | undefined, key: ToolWorkspaceKey): string {
  const language = (locale || 'fr').split('-')[0] as keyof typeof toolWorkspaceMessages
  const messages = toolWorkspaceMessages[language] || toolWorkspaceMessages.fr
  return messages[key] || toolWorkspaceMessages.fr[key]
}
